### ISSUE TITLE
Add Ability to replace Bing with Search Engine of Choice

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#1]
**Describe the bug**
Currently all search results open in Bing

**To Reproduce**
1. Run MSEdgeRedirect
2. Search for web results in the start menu

**Expected behavior**
N/A

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.1.0.0

**Additional context**
N/A

**Comment by rcmaehl** [comment]
## Original Search URL:

https://www.bing.com/search?q=web%20test&form=WNSGPH&qs=AS&cvid=baecc21bf5e34cba9253af9426bb7d2c&pq=web%20test&cc=US&setlang=en-US&nclid=0120C2E5AB7D89B30E7CC4E0C9254CD2&ts=1636689928398&wsso=Moderate

1. Split string at &
2. Remove https://www.bing.com/search?q=
3. Apply need format

### Ask Formatting:
https://www.ask.com/web?q=<query>

### Baidu Formatting:
https://www.baidu.com/s?wd=<query>

### DuckDuckGo Formatting:
https://duckduckgo.com/?q=<query>

### Ecosia Formatting:
https://www.ecosia.org/search?q=<query>

### Google Formatting:
https://www.google.com/search?q=<query>

### Sogou Formatting:
https://www.sogou.com/web?query=<query>

### Yahoo Formatting:
https://search.yahoo.com/search?p=<query>

### Yandex Formatting:
https://yandex.com/search/?text=<query>

**Comment by gnpaone** [comment]
Actually I use Chrometana pro extension available in Chrome store for this purpose (it redirects Bing to default search engine in Chrome) but it will be awesome if MSEdgeRedirect could do this. The only problem I faced with Chrometana extension is if I manually want to open and search in Bing then that extension will not allow it and redirects the search results via default search engine (which is Google in my case)

**Comment by rcmaehl** [comment]
> Actually I use Chrometana pro extension available in Chrome store for this purpose (it redirects Bing to default search engine in Chrome) but it will be awesome if MSEdgeRedirect could do this. The only problem I faced with Chrometana extension is if I manually want to open and search in Bing then that extension will not allow it and redirects the search results via default search engine (which is Google in my case)
> 
> PS: Is it possible to add "options" or "settings" to change these settings as per user preferences (for example "Redirect to default browser" option turned on by default but could be turned off via settings) but default will be turned on something like that?

A settings GUI will be created. By default, MSER will only redirect search results to whatever the default browser is, but search engine and other settings will allowed to be customized.
