### ISSUE TITLE
Chocolatey + Winget badges

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#102]
Add Badges for "Get MSEdgeRedirect on" Chocolately and Winget. Create badge images if public ones don't exist

**Comment by rcmaehl** [comment]
## For Microsoft Store:
![image](https://user-images.githubusercontent.com/716581/158251211-faa8adc8-79ac-4b38-a68d-0688cc79ad2c.png)

# For WinGet:
* Similar to Microsoft Store.
* Replace Windows Logo with Powershell 7 icon?
* Replace Microsoft with Winget

# For Chocolatey:
* Use this bar
![image](https://user-images.githubusercontent.com/716581/158251415-45e5998f-288e-45e5-aebd-0c784ad7c50f.png)

* Use this "C"
![image](https://user-images.githubusercontent.com/716581/158251522-1534ad0a-741f-497f-bd13-ceed8130679e.png)

* "Get it from Chocolately"
* Reduce transparent border padding

## For All:

* Standardize Sizes (200px, 300px, and 400px)
* Run PNG Optimization

**Comment by WilloIzCitron** [comment]
oh yes my photoshop power is ready

**Comment by WilloIzCitron** [comment]
i already found only powershell core 6 not 7

**Comment by WilloIzCitron** [comment]
- Winget: Done

Capitallized G

![158251211-faa8adc8-79ac-4b38-a68d-0688cc79ad2c](https://user-images.githubusercontent.com/49786146/159123313-3bdafdd3-5130-4b0d-9003-40618390943a.png)


or 

Uncapitalized G

![uncappitalized g](https://user-images.githubusercontent.com/49786146/159123331-729ae9f2-4cf9-439b-8515-16a4ef991089.png)

**Comment by WilloIzCitron** [comment]
- Chocolatey: Done

![choco](https://user-images.githubusercontent.com/49786146/159124825-d266e61e-a69e-4f90-9a0a-9b4b9188be18.png)

**Comment by WilloIzCitron** [comment]
but i forgot to resize

**Comment by WilloIzCitron** [comment]
![choco](https://user-images.githubusercontent.com/49786146/159124866-b9394c8e-9623-460b-bc6a-fe045bd65902.png)
 
resize done

**Comment by itsmeboy0** [comment]
> * Winget: Done
> 
> Capitallized G
> 
> ![158251211-faa8adc8-79ac-4b38-a68d-0688cc79ad2c](https://user-images.githubusercontent.com/49786146/159123313-3bdafdd3-5130-4b0d-9003-40618390943a.png)
> 
> or
> 
> Uncapitalized G
> 
> ![uncappitalized g](https://user-images.githubusercontent.com/49786146/159123331-729ae9f2-4cf9-439b-8515-16a4ef991089.png)

Kinda weird that you used the PowerShell logo for Winget (its not connected to PowerShell at all).

**Comment by WilloIzCitron** [comment]
> > * Winget: Done
> > 
> > Capitallized G
> > ![158251211-faa8adc8-79ac-4b38-a68d-0688cc79ad2c](https://user-images.githubusercontent.com/49786146/159123313-3bdafdd3-5130-4b0d-9003-40618390943a.png)
> > or
> > Uncapitalized G
> > ![uncappitalized g](https://user-images.githubusercontent.com/49786146/159123331-729ae9f2-4cf9-439b-8515-16a4ef991089.png)
> 
> @WilloIzCitron Kinda weird that you used the PowerShell logo for Winget (it's a standalone program and thus has no connection to PowerShell).

winget hasn't logo yet

**Comment by WilloIzCitron** [comment]
and winget its a cli program

**Comment by itsmeboy0** [comment]
Like I said before, Winget is a standalone program and can be used in anything other than PowerShell (cmd, git bash), so I'm suggesting not to use the PowerShell logo for it.

**Comment by WilloIzCitron** [comment]
ok i refactor the badge soon

**Comment by WilloIzCitron** [comment]
wait 

i use all cli programs logo to make winget badge?

**Comment by itsmeboy0** [comment]
Since Winget does not have a logo yet, how bout use the Microsoft logo for it (like the Microsoft Store badge)

**Comment by WilloIzCitron** [comment]
ok thats better

**Comment by rcmaehl** [comment]
> Since Winget does not have a logo yet, how bout use the Microsoft logo for it (like the Microsoft Store badge)

I had considered that but for users that don't use Winget they might be a bit confused.

**Comment by itsmeboy0** [comment]
Scoop doesn't have a logo yet (https://github.com/ScoopInstaller/Scoop/issues/2261)

**Comment by rcmaehl** [comment]
Closing for now. I don't see scoop getting a logo anytime soon.
