### ISSUE TITLE
Convert Apps to Firefox/Chrome Apps

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#104]
**Describe the request**
Add drop down to Redirect Apps to allow them to be converted to Chrome or Firefox Apps.

**Chrome:**
`chrome -app=<url>`

**Firefox:**
`firefox -url 'data:text/html;charset=utf-8,<!DOCTYPE html><html><body><script>window.open("<url>", "_blank","height=400,width=600,menubar=no,location=no,toolbar=no,left=100,top=100")<%2Fscript><%2Fbody><%2Fhtml>'`

Credit @subzeronexii

**Comment by SubZeroNexii** [comment]
Did you check the firefox command aswell? I am not entierly sure it is working properly.

**Comment by JMVS** [comment]
I've also checked Firefox and cannot make it work

**Comment by rcmaehl** [comment]
I've asked the wrong question to try to get the right answer elsewhere. Hopefully I'll get some replies.

**Comment by rcmaehl** [comment]
Firefox no longer has this feature and it's not planned to be added back in. I may add something like this EVENTUALLY by using an .html page included with the application but I'll be closing out this issue for now.

**Comment by WilloIzCitron** [comment]
If it's ported to Chrome it will be ChromeRedirect
