### ISSUE TITLE
High Memory Consumption

### ISSUE THREAD

**Issue by megamorphg** [rcmaehl/MSEdgeRedirect#109]
**Check List**
- [ x ] Microsoft Edge is still installed (see issue 26)
- [ x ] Running `microsoft-edge:https://google.com` redirects successfully
- [ x ] Reinstall or `/repair` was attempted for System Errors (see issues 25 & 77)
- [ x ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

**Install Type**
- [ ] New Install
- [ ] New Deployment (winget/chocolatey/sccm)
- [ ] Update
- [ ] Managed Update (winget/chocolatey/sccm)

**Installed Mode**
- [ x ] Active Mode
- [ x ] Service Mode
- [ ] Unsure

**Describe the bug**
Whether in Active or Service Mode, the memory consumption of the msedge_no_ifeo.exe process is fairly high, 200MB+:

- In Service mode:
![image](https://user-images.githubusercontent.com/1782353/159507084-ce0baa91-ad7f-4ced-8788-06d5240dac38.png)
![image](https://user-images.githubusercontent.com/1782353/159506704-fa7a116a-01b6-4af3-9da8-220f19ab6a47.png)
- In Active mode: (after several hours of using it)
![image](https://user-images.githubusercontent.com/1782353/159506977-f3bd6b59-a525-4243-aeb7-bf0e71925dac.png)

**To Reproduce**
1. Check Process Explorer
2. Scroll down to 'msedge_no_ifeo.exe'
4. Observe memory Private Bytes and Working Set

**⚠️ File Upload ⚠️**
Haven't done below since I think this is a generic issue but let me know if required.

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Windows Build: 19044.1586

**Comment by rcmaehl** [comment]
msedge_no_ifeo.exe is Microsoft Edge, not MSEdgeRedirect. This appears to be on par with it's normal usage:

![image](https://user-images.githubusercontent.com/716581/159525653-0da09182-e42e-489d-899f-dc7e7ff69c27.png)

https://github.com/rcmaehl/MSEdgeRedirect/blob/d033c8bca27b3ad2b151d2642637f3150e170aa7/MSEdgeRedirect_Wrapper.au3#L781

**Comment by rcmaehl** [comment]
The _no_ifeo.exe process shouldn't exist during Service Mode however. It was likely still running when Active Mode was uninstalled. I'll correct that.
