### ISSUE TITLE
Add ability to hide the tray icon

### ISSUE THREAD

**Issue by jed84** [rcmaehl/MSEdgeRedirect#11]
Enhancement suggestion:

Add ability to hide the tray icon

**Comment by rcmaehl** [comment]
On it.

Todo list:

- [ ] Add tray menu item
- [ ] Add command line parameter
- [ ] Add option to have setting persist

**Comment by rcmaehl** [comment]
This has been added. You can grab the build with this option here:

https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1454538638

The icon can be hidden using the menu item:

![image](https://user-images.githubusercontent.com/716581/141527376-14e72a25-9cc0-4db7-99cc-c28f12c4fe17.png)

Or by running the script using the `/h` or `/hide` parameter

![image](https://user-images.githubusercontent.com/716581/141527512-72428de5-6e72-4c4c-8222-3c106301b96d.png)

If you have any feedback let me know!

**Comment by rcmaehl** [comment]
Darn github desktop keywords... reopening until shipped in a release.

**Comment by rcmaehl** [comment]
Closing. Releasing patched build in less than 24 hours

**Comment by gnpaone** [comment]
> This has been added. You can grab the build with this option here:
> 
> https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1454564188
> 
> The icon can be hidden using the menu item:
> 
> ![image](https://user-images.githubusercontent.com/716581/141527376-14e72a25-9cc0-4db7-99cc-c28f12c4fe17.png)
> 
> Or by running the script using the `/h` or `/hide` parameter
> 
> ![image](https://user-images.githubusercontent.com/716581/141527512-72428de5-6e72-4c4c-8222-3c106301b96d.png)
> 
> If you have any feedback let me know!

Is there any way to show icon again after hiding it?

**Comment by rcmaehl** [comment]
> > This has been added. You can grab the build with this option here:
> > https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1454564188
> > The icon can be hidden using the menu item:
> > ![image](https://user-images.githubusercontent.com/716581/141527376-14e72a25-9cc0-4db7-99cc-c28f12c4fe17.png)
> > Or by running the script using the `/h` or `/hide` parameter
> > ![image](https://user-images.githubusercontent.com/716581/141527512-72428de5-6e72-4c4c-8222-3c106301b96d.png)
> > If you have any feedback let me know!
> 
> Is there any way to show icon again after hiding it?

Forgot to add last night. Added in the latest dev build. Start a new instance / relaunch the app. The new session will close itself and the old one will show it's icon.

**Comment by 0ibaba** [comment]
> Forgot to add last night. Added in the latest dev build. Start a new instance / relaunch the app. The new session will close itself and the old one will show it's icon.

It doesn't stay hidden after reboots. I tried using a shortcut with /hide to the startup folder (this worked with the github actions build) but it doesn't open and shows this https://imgur.com/QRIensu

**Comment by rcmaehl** [comment]
@0ibaba Oops, left some debugging in. Try https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1469128229 or https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/mser/main/mser.zip

**Comment by bonn2** [comment]
@rcmaehl I'm not @0ibaba but that actions build now yields this.
![image](https://user-images.githubusercontent.com/42011672/142134776-f98d5ffe-f066-4ef1-98cb-a747fd34460e.png)

**Comment by rcmaehl** [comment]
I need to investigate the _ArraySearch then. Shouldn't be passing the check for `/hide`. Should be fixed in https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1471766469

**Comment by 0ibaba** [comment]
@rcmaehl Yeah, this build is working properly :)
