### ISSUE TITLE
Microsoft Sabotage & EdgeDeflector Discontinuation

### ISSUE THREAD

**Issue by Malix-Off** [rcmaehl/MSEdgeRedirect#112]
Hello
I have just seen that [EdgeDeflector](https://github.com/da2x/EdgeDeflector) [was just discontinued](https://github.com/da2x/EdgeDeflector/commit/23ab3f6c12f3dd56be629a93d247fbe5a4fe62a6).
Does [this sabotage ](https://www.ctrl.blog/entry/microsoft-edge-protocol-competition.html) will affect this project as well?
Thanks!

**Comment by Masamune3210** [comment]
Almost the entire point of this being made was to replace EdgeDeflector after that patch came out

**Comment by rcmaehl** [comment]
> Almost the entire point of this being made was to replace EdgeDeflector after that patch came out

This is correct. They've done minor changes to sabotage this project, namely new command line flags but we're keeping on
