### ISSUE TITLE
Widgets panel search still opening in Edge. URI likely failed URL check

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#12]
Found one more issue, it opens in edge (dev, stable etc) if searched via widgets panel in Windows 11, it doesn't open in Chrome

PS: It doesn't open in Edge too sometimes if mser is running in background

_Originally posted by @gnpaone in https://github.com/rcmaehl/MSEdgeRedirect/issues/8#issuecomment-967277570_

**Comment by rcmaehl** [comment]
@gnpaone I made some enhancements to URI handling. Please grab this build and let me know if the problem still exists.

https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1454518619

**Comment by gnpaone** [comment]
> @gnpaone I made some enhancements to URI decoding. Please grab this build and let me know if the problem still exists.
> 
> https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1454518619

No, it's still the same, either opening in edge or not opening at all, I used [this build](https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1454564188) as well as your above mentioned [build](https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1454518619) too

**Comment by FaviousM** [comment]
Same issue here with Widgets. For me, no links open at all, where Edge Deflector worked fine. I'm on the latest stable build of this new solution

**Comment by rcmaehl** [comment]
I've added logging to the latest dev build. Likely some formatting has gone wrong that is failing to pass as a valid URL. For anyone who would like to test you can download this dev build and try to use a widget:

https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1457309123

Logs will be in `%localappdata%\MSEdgeRedirect\logs`

I'm still waiting for an additional SSD to arrive from Amazon to install Windows 11 dev on.

**Comment by gnpaone** [comment]
Same issue. Here are the logs 👍�
[URIFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/7533145/URIFailures.log)
�
AppFailures and AppGeneral logs are empty so it's not uploading in Github

**Comment by gnpaone** [comment]
I have found another issue, some coding in x86 version makes Windows Defender and other antivirus think it's a virus
![Screenshot (4858)](https://user-images.githubusercontent.com/78990165/141666742-6c62c5c7-40e6-478a-9438-def8dfb79cf5.png)

**Comment by rcmaehl** [comment]
> I have found another issue, some coding in x86 version makes Windows Defender and other antivirus think it's a virus ![Screenshot (4858)](https://user-images.githubusercontent.com/78990165/141666742-6c62c5c7-40e6-478a-9438-def8dfb79cf5.png)

Unfortunately, known issue with AutoIt 32 bit applications. Tempted to end support for 32-bit entirely.

**Comment by rcmaehl** [comment]
Should be improved in https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1458164722

**Comment by gnpaone** [comment]
> Should be improved in https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1458164722

Yes, all kinds of link from widgets tab now opens in chrome, but that [failing issue](https://github.com/rcmaehl/MSEdgeRedirect/issues/8#issuecomment-967265230) mentioned by me exists for widgets links too.

**Comment by gnpaone** [comment]
> > I have found another issue, some coding in x86 version makes Windows Defender and other antivirus think it's a virus
> 
> Unfortunately, known issue with AutoIt 32 bit applications. Tempted to end support for 32-bit entirely.

Maybe, since Windows 11 don't have 32 bit version, but it may be useful for other 32 bit users
