### ISSUE TITLE
Start menu shortcut

### ISSUE THREAD

**Issue by lorenzo-filomena** [rcmaehl/MSEdgeRedirect#120]
I would reccomend change the name of the shortcut that the installer add to the Start Menu in MSEdgeRedirect or something similar, because "Setting" is just too generic and confusing.

**Comment by rcmaehl** [comment]
> I would reccomend change the name of the shortcut that the installer add to the Start Menu in MSEdgeRedirect or something similar, because "Setting" is just too generic and confusing.

Already fixed for next release. You can download the dev build if you want to update.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
