### ISSUE TITLE
[Spin Off] Redirecting other sources, automatically changing other URLs

### ISSUE THREAD

**Issue by donnyk781** [rcmaehl/MSEdgeRedirect#126]
**Describe the request**
The one thing I have notice is that MSEdgeRedirect does not redirect the weather in apps like Microsoft outlook app. I changed the default weather in MSEdgeRedirect to weather underground but in outlook it still brings up msn weather.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Desktop (please complete the following information):**
 - OS: windows 11 
 - Build 22000.613

**Additional context**
when in the calendar part of outlook the weather does not redirect to weather underground but to msn weather .

**Comment by rcmaehl** [comment]
It looks like the weather within outlook respects the default browser, at least in the version I've tested (`Microsoft® Outlook® for Microsoft 365 MSO (16.0.14326.20908) 32-bit`). As such it isn't captured currently.

This is out of scope for this project, however, I have an upcoming spin-off program that will be able to handle this.

**Comment by rp1231** [comment]
If possible, I would like to be tagged for the spin of project beta as well.
Thanks

**Comment by rcmaehl** [comment]
Spin off aim: 

* Add similar functionality to Benjamin Schmidt (@bluefirex) Redirector
https://apps.apple.com/us/app/id1523685797

**Comment by rcmaehl** [comment]
Created the repo at [rcmaehl/AppLockerPlus](https://github.com/rcmaehl/AppLockerPlus) will be a bit before I start work on it.
