### ISSUE TITLE
is any one have this problem? win+search the format of open an picture is

### ISSUE THREAD

**Issue by ThomasQAQOUO** [rcmaehl/MSEdgeRedirect#128]

**Comment by ThomasQAQOUO** [comment]
is any one have this problem? win+search the format of open an picture is an printing mode.
![image](https://user-images.githubusercontent.com/89352852/166137229-6b09376a-df96-44c2-aeda-5d35fd74fae5.png)
![image](https://user-images.githubusercontent.com/89352852/166137234-d9aeb093-28a7-490c-bdd7-737cc681f9ce.png)

**Comment by rcmaehl** [comment]
Closing, need more info, never received.
