### ISSUE TITLE
Cannot start Edge with multiple account

### ISSUE THREAD

**Issue by doufu3344** [rcmaehl/MSEdgeRedirect#129]
I have multiple accounts set up on my computer, some of which require Edge to be the default browser, some do not. 

I found Edge cannot be start  in the account that set Edget as default:
![mse](https://user-images.githubusercontent.com/1912467/167245592-294e467b-eeb0-4e61-b671-0b707f963d92.png)

my setting(I'm not sure which mode of MSEdgeRedirect is running on):
![setting](https://user-images.githubusercontent.com/1912467/167245607-77fd7e2e-9fd0-4439-a8e9-bd64b4eef7f2.png)

how can I make MSEdgeRedirect only works under the users who need it?

**Comment by rcmaehl** [comment]
I'd recommend a Service Mode install per user then. Due to how Active Mode works, it can only be applied system wide. The features should work the same between modes.

**Comment by doufu3344** [comment]
Thanks, I changed it to Service Mode and it worked fine.
