### ISSUE TITLE
Opening Pdfs opens popups

### ISSUE THREAD

**Issue by Nirgranth** [rcmaehl/MSEdgeRedirect#132]
**Check List**
- [x] Microsoft Edge is still installed (see issue 26)
- [x] Running `microsoft-edge:https://google.com` redirects successfully
- [x] Reinstall or `/repair` was attempted for System Errors (see issues 25 & 77)
- [x] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

**Install Type**
- [ ] New Install
- [ ] New Deployment (winget/chocolatey/sccm)
- [ ] Update
- [x] Managed Update (winget/chocolatey/sccm)

**Installed Mode**
- [x] Active Mode
- [ ] Service Mode
- [ ] Unsure

**Describe the bug**
opening pdfs opens a popup everytime

**To Reproduce**
open any pdf file with default settings

**⚠️ File Upload ⚠️**

[URIFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8666331/URIFailures.log)
[edge.txt](https://github.com/rcmaehl/MSEdgeRedirect/files/8666335/edge.txt)
[AppGeneral.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8666337/AppGeneral.log)
[AppSecurity.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8666338/AppSecurity.log)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/48947296/167758746-65a0652e-2c07-46eb-84b5-fa34369aec79.png)
**Additional context**
![image](https://user-images.githubusercontent.com/48947296/167758709-b7dc35c1-3fae-4a8d-a42a-aa0c682555f9.png)

**Comment by rcmaehl** [comment]
Oops. Just commited a fix now. Give it about 5 minutes for program to be compiled by github then download the latest dev build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
