### ISSUE TITLE
Exlude certain apps that fail to work with MSEdgeRedirect "on"

### ISSUE THREAD

**Issue by pashza** [rcmaehl/MSEdgeRedirect#133]
**Describe the request**
Some apps like SoundCloud - wont work it tries to load but just throws an error:
The application was unable to start correctly
(0xc0000017). Click OK to  close the application.

so i end up using it in browser instead of an app... not a huge loss.
but made me think that other apps might have similar issues,
would be great to have a mechanism to exclude apps or pause Redirection.

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Version: 21H2
 - Build 22000.675
 - Experience: Windows Feature Experience Pack 1000.22000.675.0

**Additional context**
Is there a hard way, eg registry or any other workaround to exclude an app or pause the service temporary?
That way i can at least automate it and make a run script for Soundcloud to do the actions before its launched.

**Comment by rcmaehl** [comment]
Please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
