### ISSUE TITLE
Bugged redirect

### ISSUE THREAD

**Issue by Nach677** [rcmaehl/MSEdgeRedirect#135]
Hi!
So I installed this on 4 Windows Machines, 1 Win 11, 3 Win 10. My Win 11 machine works perfectly with this tool, so does 1 of my Win 10 Machines, but the 2 other Win 10 machines when trying to redirect get pushed to the "open with" dialogue box which gives me options of edge or edge or picking an app from the MS Store. Any help would be greatly appreciated, if you need hardware specs or sys models lemme know. I've uninstalled the package and reinstall both before and after restarts to no avail.

**Comment by rcmaehl** [comment]
> chine works perfectly with this tool, so does 1 of my Win 10 Machines, but the 2 other Win 10 machines when trying to redirect get pushed t

Make sure to select "Always open with" and the "Recommended" edge. It should then redirect properly.

**Comment by Nach677** [comment]
Hi, so I might be blind or not looking in the right place. I don't see an open with option. In the MSedgeredirect updater settings tool I don't see that option. With a search it gives me the dialogue box "how do you want to open this?" gives me edge and "other options" edge. Not showing firefox or brave. Which is odd since on my win 11 machine it redirect to brave with no issues, and my other win 10 box redirect to opera gx no issues.

**Comment by Nach677** [comment]
Or maybe I just misread & misunderstood what you said. Lemme try the featured edge again hold on

**Comment by rcmaehl** [comment]
> Hi, so I might be blind or not looking in the right place. I don't see an open with option. In the MSedgeredirect updater settings tool I don't see that option. With a search it gives me the dialogue box "how do you want to open this?" gives me edge and "other options" edge. Not showing firefox or brave. Which is odd since on my win 11 machine it redirect to brave with no issues, and my other win 10 box redirect to opera gx no issues.

Yeah, you're likely getting this menu for `microsoft-edge:`

![image](https://user-images.githubusercontent.com/716581/168839552-6da6df80-1007-4416-8677-7609b6a45294.png)

Instead of this screen for `http:`

![image](https://user-images.githubusercontent.com/716581/168839651-1e414aee-56f4-44a6-a8fe-2bcce092aed4.png)

**Comment by Nach677** [comment]
Huzzah, thank you!
