### ISSUE TITLE
Canary Inop

### ISSUE THREAD

**Issue by 22350** [rcmaehl/MSEdgeRedirect#137]
I have windows 10 19044.1706

I have set my default apps and installed this as admin.  Not working.  

Thanks for any help

**Comment by rcmaehl** [comment]
> I have windows 10 19044.1706
> 
> I have set my default apps and installed this as admin. Not working.
> 
> Thanks for any help

Are there any log files in `%localappdata%\MSEdgeRedirect`?

**Comment by 22350** [comment]
@rcmaehl  All the log files are empty

**Comment by rcmaehl** [comment]
What happens when you run this:

![image](https://user-images.githubusercontent.com/716581/169940617-ecb7db7b-7516-4b33-ba10-4b9ecbe8fcea.png)

**Comment by 22350** [comment]
> What happens when you run this:
> 
> ![image](https://user-images.githubusercontent.com/716581/169940617-ecb7db7b-7516-4b33-ba10-4b9ecbe8fcea.png)
![2022-05-23 20_18_55-Window](https://user-images.githubusercontent.com/2864726/169942184-93d119e4-ee0a-4fde-b800-e6f4e9a2d2ed.png)

**Comment by 22350** [comment]
Oh shit!  Do I have to have microsoft edge installed?

**Comment by rcmaehl** [comment]
> Oh shit! Do I have to have microsoft edge installed?

Yes per #27. The recommended work around is to install edge canary.

**Comment by 22350** [comment]
> > Oh shit! Do I have to have microsoft edge installed?
> 
> Yes per #27. The recommended work around is to install edge canary as it's a per user install and doesn't hook as deep.

Was being a bit dim

**Comment by 22350** [comment]
> > Oh shit! Do I have to have microsoft edge installed?
> 
> Yes per #27. The recommended work around is to install edge canary as it's a per user install and doesn't hook as deep.

OK,  just installed.  same issue

**Comment by 22350** [comment]
deleted, cleared registry files, reinstalled .... zip

**Comment by rcmaehl** [comment]
> deleted, cleared registry files, reinstalled .... zip

Odd. I'll check out Canary and see what's up. Do you still get the error?

> > ![2022-05-23 20_18_55-Window](https://user-images.githubusercontent.com/2864726/169942184-93d119e4-ee0a-4fde-b800-e6f4e9a2d2ed.png)

**Comment by rcmaehl** [comment]
Will be a non-issue once #27 is fixed. Test build is now available.
