### ISSUE TITLE
Doesn't work with the new search bar

### ISSUE THREAD

**Issue by iMonZ** [rcmaehl/MSEdgeRedirect#138]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Deployment (Chocolatey, Winget, Etc)

### Install Mode

Service Mode

### Steps to reproduce

Searching in the new Desktop search bar

![image](https://user-images.githubusercontent.com/11319871/170020989-3836d3d2-045b-41a7-ad89-dc332f462fd0.png)
![image](https://user-images.githubusercontent.com/11319871/170021026-c742129b-c223-4926-aed1-dd965f83aa81.png)
![image](https://user-images.githubusercontent.com/11319871/170021058-5c61c326-d3c7-4654-bd10-5b4c4f29069a.png)
![image](https://user-images.githubusercontent.com/11319871/170021091-43dea592-27c4-4474-bad4-283b9a234164.png)
![image](https://user-images.githubusercontent.com/11319871/170021116-a81c0995-fe41-4a6d-995e-47f486f7ce99.png)

### ✔️ Expected Behavior

Should redirect to DuckDuckGo

### ❌ Actual Behavior

Opens Firefox with Bing

### Microsoft Windows version

22H2

**Comment by rcmaehl** [comment]
Good to know, I'll take a look

**Comment by rcmaehl** [comment]
It looks like this is an optional dev branch feature. I won't be adding support for this until it enters the Stable Branch
