### ISSUE TITLE
Remove web:

### ISSUE THREAD

**Issue by kysterics** [rcmaehl/MSEdgeRedirect#140]
### Description of the new feature / enhancement

Remove `web:` from the search string

### Scenario when this would be used?

If you want to do a web search only, windows search has an option to do that task without searching applications/files.
The way to do that is to type `web:` before the search term.
However, `web:` will then be included in the search.

**Comment by rcmaehl** [comment]
I am unable to reproduce? I'm assuming that's why you closed this? If not, let me know.
