### ISSUE TITLE
[Bug] Breaks Progressive Web Apps

### ISSUE THREAD

**Issue by schlagmichdoch** [rcmaehl/MSEdgeRedirect#142]
App breaks any installed progressive webapps.

In windows PWAs can only be installed via edge, so whenever a pwa is started, a stand-alone edge window is opened.

When MSEdgeRedirect is configured to redirect searches, whenever a pwa is started, MSEdgeRedirect is stuck in a loop of opening itself. I am only able to kill the process via console, as it is nearly uncatchable in Task Manager.

System: Windows 11 (KB5013943)
PWA used for testing: [snapdrop](https://snapdrop.net/)

**Comment by schlagmichdoch** [comment]
well, pwas only being installable via edge is obviously not true. Quick search provides an alternative for firefox:
https://addons.mozilla.org/de/firefox/addon/pwas-for-firefox/
I'm fine with that.

As this is still a bug, I will not close this issue yet.

**Comment by rcmaehl** [comment]
> well, pwas only being installable via edge is obviously not true. Quick search provides an alternative for firefox: https://addons.mozilla.org/de/firefox/addon/pwas-for-firefox/ I'm fine with that.
> 
> As this is still a bug, I will not close this issue yet.

Please try the latest test build in the readme. I'm pretty sure I fixed this, but I'm finalizing some changes for 0.6.7.0

**Comment by schlagmichdoch** [comment]
When updating with the "latest testing release" from the readme it really does work. Perfect! Thanks!

I will keep my PWAs at firefox now anyways ;-)
