### ISSUE TITLE
Some Features Broken after ChrEdgeFkOff uninstalled

### ISSUE THREAD

**Issue by RaXorX** [rcmaehl/MSEdgeRedirect#145]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

I just tried with AveYo's removal script and as far as his script is intended, it removes edge and redirects all the searches to the default browser (redicrection via chredgefkoff script)

If I use chredgefkoff script again, redirection is disabled and using it once more it's back there.

Afterwards when I try to use msedgeredirect, I installed it and nothing happens. By nothing, I meant the said above redirection still happens but the search engine preference from msedgeredirect does not take into effect at all. Maybe I am missing something or maybe I misunderstood what the search engine preference is for. I still get all the results in bing only.

So on that note, could you perhaps explain what it is meant to do?
To my understanding it was that it would use selected Search Engine to list the search results within the search bar and when opening one, it'll open in the default web browser with the preferred search engine.

Also my browser is vivaldi snapshot Vivaldi.5.3.2679.50.x64.exe

### 
Cannot give an expected behaviour until I understand the purpose of search engine preference.

###
Browser doesn't show results in the preferred search engine (DuckDuckGo)

### Microsoft Windows version

"22H2 Build 22621"

### Other Software

AveYo's Edge Removal Script
PS.: No Microsoft Edge is not installed anymore, uninstalled/removed using AveYo's Removal Script. I can't proceed with opening the issue unless I tick the `Microsoft Edge is still installed (see issue 26) *`
above

**Comment by rcmaehl** [comment]
Rerun the MSEdgeRedirect installer after running the Aveyo uninstaller as it removes needed entries. I'm working on a troubleshooter / automatic repair for stuff like this.

**Comment by RaXorX** [comment]
I actually reran it multiple times, even tried the service mode to no avail actually. Gladly since I am in a VB I can test plenty. Right now I turned off the chredgefkoff portion from the removal script. I think that is what messes it up as msedgeredirect works totally fine if I hadn't used AveYo's script yet.

**Comment by rcmaehl** [comment]
Please try the latest test build if you aren't already:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by RaXorX** [comment]
> Please try the latest test build if you aren't already:
> 
> https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

Hi the latest test build works. I had it downloaded but didn't try. It detects Edge being removed already and works taking that into consideration.

**Comment by rcmaehl** [comment]
> > Please try the latest test build if you aren't already:
> > https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
> 
> Hi the latest test build works. I had it downloaded but didn't try. It detects Edge being removed already and works taking that into consideration.
> 
> EDIT: Also, I just noticed the title change. I think you only implemented the checks for Aveyo's scripts recently. And the last stable release is a month old build.

Yep. I'm gong to close out this issue then. Probably dropping a new stable beta this weekend.
