### ISSUE TITLE
MS Edge Update Message

### ISSUE THREAD

**Issue by Soldier1st** [rcmaehl/MSEdgeRedirect#146]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Whenever MS Edge gets updated. A message comes up saying " Microsoft Edge has updated, as such the IFEO exclusion file is out of date and needs to be updated. Update Now?[
![ms edge update msg](https://user-images.githubusercontent.com/107595393/173974626-815b05c7-3050-4728-bc4f-781e36dc782d.png)
](url)

### ✔️ Expected Behavior

I was expecting this to be updated automatically.

### ❌ Actual Behavior

Whenever MS Edge gets updated, i have to click on a box to update the exclusion.

### Microsoft Windows version

" 21H2 (OS Build 19044.1766"

**Comment by johndc7** [comment]
Would it be possible to do this with a scheduled task in Windows? I have a scheduled task created per [the documentation](https://github.com/rcmaehl/MSEdgeRedirect/wiki/Deploying-MSEdgeRedirect#maintaining-edge-when-using-active-mode) already.

Thanks for all the work on this so far 🙂

**Comment by rcmaehl** [comment]
> Would it be possible to do this with a scheduled task in Windows? I have a scheduled task created per [the documentation](https://github.com/rcmaehl/MSEdgeRedirect/wiki/Deploying-MSEdgeRedirect#maintaining-edge-when-using-active-mode) already.
> 
> Thanks for all the work on this so far 🙂

Yeah, I can add in an option for running the scheduled task instead of the prompt.

**Comment by ZaLiTHkA** [comment]
just to propose an alternative here, since I personally (and I believe many others) prefer to check software update changelogs before installing, perhaps the "update check behaviour" should be an option in the installer?

---

just a quick note for context: the first few times that update dialog box popped up, I thought it was something from MS Edge itself, so I selected "No" each time (at least, I did when I saw it before the super-secret timeout before the dialog closes itself). so if the dialog _does_ stick around, please could you make the user message a little clearer? and maybe also remove the auto dismiss action..?

**Comment by rcmaehl** [comment]
> **edit**: hang on, just to clarify, this popup message doesn't mean that MSEdgeRedirect has an update, this means that MSEdgeRedirect needs to update the contents of a file somewhere, is that correct?

Yes. Otherwise #115 occurs. The task scheduler task is probably the best way to resolve this honestly.

I'll improve the dialog box though

**Comment by ZaLiTHkA** [comment]
thanks for the clarification. 👍🏼 

> Yes. Otherwise #115 occurs. The task scheduler task is probably the best way to resolve this honestly.

I've got no objections with that.

> I'll improve the dialog box though

if _this_ dialog box is going to stick around, then this sounds like a good plan..

**Comment by rcmaehl** [comment]
> if _this_ dialog box is going to stick around, then this sounds like a good plan..

It _probably_ will if the scheduled task doesn't exist as a fall back.

**Comment by jerone** [comment]
We already installed this software, agreeing to it's functionality.
With Microsoft releasing new version Edge on a very regular schedule, this popup comes up very often now.
It would be great if the IFEO update happens automatically.
