### ISSUE TITLE
Facebook/Instagram/TikTok apps (Microsoft Store) can't work with MSEdgeRedirect installed. Please implement possibility.

### ISSUE THREAD

**Issue by PIRATAONE** [rcmaehl/MSEdgeRedirect#149]
### Description of the new feature / enhancement

Those apps require Edge to be launched (as they work inside it).
Is it possible to let Edge be launched for those apps to work?
Thank you.

### Scenario when this would be used?

It is nice to have those apps loaded separately and floating around the desktop (as it is possible if used with no Edge deflector) without the need to use the default browser installed, specially in a dual monitor scenario.

### Supporting information

I have tried with another Edge deflector, and it works, so I see that it is possible overall.

**Comment by rcmaehl** [comment]
Please try the latest test build.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by PIRATAONE** [comment]
> Please try the latest test build.
> 
> https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

Sorry for the delay. As a few weeks has passed, I installed directly the latest official version. Looks like everything is working now. Will use it as main deflector now and test it widely. Thank you.
