### ISSUE TITLE
Active Mode MSEdgeRedirect - Settings UWP app looking for msedge.exe error

### ISSUE THREAD

**Issue by FadeMind** [rcmaehl/MSEdgeRedirect#15]
**Check List**
- [ ] The App appears in the system tray
- [ ] Running `microsoft-edge:https://google.com` redirects successfully

**Describe the bug**
Active Mode MSEdgeRedirect - Settings UWP app looking for msedge.exe error

**To Reproduce**
1. Run MSEdgeRedirect setup as admin and set Active Mode setup install. 
2. Set Microsoft Edge Chromium as MICROSOFT-EDGE PROTOCOL handler. 
2. Launch Settings UWP app.

Results:
![20211127-1638002526](https://user-images.githubusercontent.com/9846948/143674631-851ebd37-256c-4a1f-b0ae-c4c5e3ad3d09.png)

**File Upload**

/!\ Leave edge open and run `Get-WmiObject Win32_Process -Filter "name = 'msedge.exe'" | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File ./edge.txt` and attach the generated file

**Desktop (please complete the following information):**
 - Windows Version: 10
 - Windows Build: 21H2 (19044.1387) 

**Additional context**\
After removing MSEdgeRedirect and reinstall as service mode - user, seems works fine for now.

**Comment by rcmaehl** [comment]
Which option in the settings app did you select?

**Comment by rcmaehl** [comment]
Might be a 21H2 specific issue, I see the program running within settings but it shouldn't be erroring out. Installing 21H2 now and will make any needed changes.

**Comment by FadeMind** [comment]
I removed `MSEdgeRedirect`, install fresh as admin with Active Mode,  reboot.
Seems it is fine now. Will test and feedback IF issue happen again. 

![20211127-1638029911](https://user-images.githubusercontent.com/9846948/143689050-144d2077-03e1-420b-8397-fba25bd3d8a7.png)

BTW If you set 

175% screen zoom and in custom 125% this happen:

![20211127-1638029855](https://user-images.githubusercontent.com/9846948/143689102-818b4ee7-2689-493e-b1fb-8e5b3845f885.png)
Text is cut. 

Why do this?
Legacy win32 apps have poor scalling and blur look and this hack fix this:

![20211127-1638030411](https://user-images.githubusercontent.com/9846948/143689178-81f287a9-7f60-445d-b0e9-bb9971fb2a6b.png)

![20211127-1638030305](https://user-images.githubusercontent.com/9846948/143689134-aa6620ce-febf-4742-8367-5230e8ed15bc.png)
![20211127-1638030313](https://user-images.githubusercontent.com/9846948/143689133-2f6e2155-fc34-40ee-b11d-f1413302ba47.png)

**Comment by rcmaehl** [comment]
> I removed `MSEdgeRedirect`, install fresh as admin with Active Mode, reboot. Seems it is fine now. Will test and feedback IF issue happen again.

I'll keep the issue open in case anyone else has the issue.

> BTW If you set
> 
> 175% screen scale and in custom 125% this happen:
> 
> Why do this? Legacy win32 apps have poor scalling and blur look and this hack fix this:
> 
> I have Full HD display here.

I've created #16 for this issue, should be fixed in 74cf9e7e0e8748e2573676c3a169d89f48f9bc69

**Comment by rcmaehl** [comment]
This may have been the same issue as #17. Did you remove the downloaded file after installing?

**Comment by 0ibaba** [comment]
@rcmaehl I had this issue too. Fixed it by installing from the folder in program files, but the problem now is that edge isn't opening when I open it normally (I'm using active mode).

**Comment by rcmaehl** [comment]
> @rcmaehl I had something similar to this and #17. Fixed it by installing from the folder in program files, but the problem now is that edge isn't opening when I open it normally (I'm using active mode).

Will be adding additional changes to launch edge if no parameters are passed in 0.4.1.0

**Comment by 0ibaba** [comment]
@rcmaehl Edge opens normally now, but opening files in edge (PDF files, for example) doesn't work. It's not a big deal though

**Comment by 0ibaba** [comment]
![image](https://user-images.githubusercontent.com/69052158/144716867-77f2c31d-c4f4-4d35-b9c5-75a3b1e7b295.png)

Don't know why but edge stopped opening again, tried reinstaling msedgeredirect, but that didn't fix it.

**Comment by rcmaehl** [comment]
> ![image](https://user-images.githubusercontent.com/69052158/144716867-77f2c31d-c4f4-4d35-b9c5-75a3b1e7b295.png)
> 
> Don't know why but edge stopped opening again, tried reinstaling msedgeredirect, but that didn't fix it.

What windows build are you on?
