### ISSUE TITLE
A more robust Edge detection

### ISSUE THREAD

**Issue by pratyakshm** [rcmaehl/MSEdgeRedirect#151]
### Description of the new feature / enhancement

Before checking if Edge is removed using AveYo's script, check if the package itself is installed using a native Windows tool.

### Scenario when this would be used?

N/A.

### Supporting information

I used AveYo's Edge removal script a long time ago, and I re-installed Edge after a few days.

I still have Edge installed on my device, but MSER incorrectly detects Edge as been removed using AveYo's script:
<details><summary>Screenshot (tap to view)</summary>

![image](https://user-images.githubusercontent.com/54220235/177028344-4e1ad99f-bc3d-43ea-bc42-ff9080059a94.png)
</details>

This behavior is misleading. One way to fix it is to check if Edge is registered as an app using winget.

Something along the lines of ```winget list Microsoft.Edge``` will produce an output to check if the browser is installed.

**Comment by rcmaehl** [comment]
Will do
