### ISSUE TITLE
Find alternative link for News and Interests 'Manage Profile Settings'

### ISSUE THREAD

**Issue by dalchina** [rcmaehl/MSEdgeRedirect#152]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

With MSEdge Redirect running, open News and Interests.
Click the profile picture top left
Click Manage Profile Settings

(I have Firefox set as default..)

### ✔️ Expected Behavior

That having MSEdgeRedirect installed would not interfere with this

### ❌ Actual Behavior

Tries to open 
https://9667fbd0ec73be97/
in Firefox

Same in Active or Service mode.

If I uninstall MSEdgeRedirect this opens the appropriate page in Edge.
Thanks.

### Microsoft Windows version

19044.1176

### Other Software

None

**Comment by rcmaehl** [comment]
Odd. Doing that on my end just opens up a blank tab in edge

![image](https://user-images.githubusercontent.com/716581/177429023-31f30228-7d11-46ff-b725-bb018caa97f9.png)

I'll review the command line try to exclude it.

**Comment by dalchina** [comment]
Hi- thanks, & should have said thanks so much for this program.. very handy.

Curious difference.. I have Firefox set as default... if I set Edge as default with MSEdge Redirect running, naturally it tells me to use a different browser as default.  FWIW I'm running an admin MS account.

**Comment by rcmaehl** [comment]
> Hi- thanks, & should have said thanks so much for this program.. very handy.
> 
> Curious difference.. I have Firefox set as default... if I set Edge as default with MSEdge Redirect running, naturally it tells me to use a different browser as default. FWIW I'm running an admin MS account.

This is because, currently, the behavior is to redirect any MSEdge websites to the Default browser. If Edge was the default browser, it would close Edge, open the website in the Default Browser (Edge), detect something tried to open a webpage in Edge, close Edge, open the website in the Default Browser (Edge), and so on.

However, It's definitely on my TODO list for allowing the websites to open in the non-default browser. - #124

**Comment by rcmaehl** [comment]
It's "fixed". As in, it loads the page in edge. I'll see if there's an actual URL that can be used that opens similar microsoft account settings online.

**Comment by dalchina** [comment]
Thanks- appreciate the notification. Is that version available for 
download, or is that just in your development build?

David Lawrie

----- Original Message -----
Subject: Re: [rcmaehl/MSEdgeRedirect] Find alternative link for News and 
Interests 'Manage Profile Settings' (Issue #152)
Date: Sat, 16 Jul 2022 21:25:57 -0700
From: "Robert C. Maehl" ***@***.***>

It's "fixed". As in, it loads the page in edge. I'll see if there's an 
actual URL that can be used that opens similar microsoft account 
settings online.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/rcmaehl/MSEdgeRedirect/issues/152#issuecomment-1186394661 

You are receiving this because you authored the thread.

Message ID: ***@***.***>


-- 
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by dalchina** [comment]
Hi Robert, Tried v 7.0.1; with FF as default, clicking 'Manage Profile 
Settings' in N & Interests now does nothing at all.

Have tried completely uninstalling MSEdgeRedirect and reinstalled it.

Thanks, David Lawrie

----- Original Message -----
Subject: Re: [rcmaehl/MSEdgeRedirect] Find alternative link for News and 
Interests 'Manage Profile Settings' (Issue #152)
Date: Sat, 16 Jul 2022 21:25:57 -0700
From: "Robert C. Maehl" ***@***.***>

It's "fixed". As in, it loads the page in edge. I'll see if there's an 
actual URL that can be used that opens similar microsoft account 
settings online.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/rcmaehl/MSEdgeRedirect/issues/152#issuecomment-1186394661 

You are receiving this because you authored the thread.

Message ID: ***@***.***>


-- 
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by rcmaehl** [comment]
Hi @dalchina, can you try the latest dev build?

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
