### ISSUE TITLE
winget install fali with exit code 160

### ISSUE THREAD

**Issue by DancingLeaf123** [rcmaehl/MSEdgeRedirect#156]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Unsure

### Steps to reproduce

winget install fali with exit code 160

### Microsoft Windows version

21H2 22000.739

**Comment by rcmaehl** [comment]
Duplicate of #155
