### ISSUE TITLE
MSER Settings - Service Mode Options get reset to being empty at each startup

### ISSUE THREAD

**Issue by RavenMacDaddy** [rcmaehl/MSEdgeRedirect#157]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Deployment (Chocolatey, Winget, Etc)

### Install Mode

Service Mode

### Steps to reproduce

![image](https://user-images.githubusercontent.com/67732686/180601245-6ae4fee4-0c5a-4915-a4ab-35cc36f7fe9a.png)

App is installed through [Scoop](https://scoop.sh/).

Every time **MSER Settings** is started, the checkboxes are empty, even if the user has previously ticked one of them or both.

### ✔️ Expected Behavior

If the user has selected at least one of the options, the corresponding option(s) should be ticked the following times **MSER Settings** is started - and obviously reverse if an option is disabled after the fact.

### ❌ Actual Behavior

Even if I've previously ticked both boxes, the checkboxes always show up empty the following times that **MSER Settings** is started.

### Microsoft Windows version

Windows 11 - 22621.160

### Other Software

The main browser is **Mozilla Firefox**.

**Comment by rcmaehl** [comment]
Please try the latest test build if possible:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by RavenMacDaddy** [comment]
It's reversed; now both are ticked - possibly partly related to #158 since the shortcut isn't deleted, even if the run at startup-option is unticked > save.

The other part, hiding the icon in tray, also isn't saved; if I select to not hide the icon > save, this doesn't result in the option being unticked the next time **MSER Settings** is started.

**Comment by rcmaehl** [comment]
Fixed in 0.7.0.2 which will be released as soon as the new program logo arrives from the artist.
