### ISSUE TITLE
MSER Settings - Service Mode Options: Saving 'run at startup' unticked doesn't delete the shortcut from the Startup folder

### ISSUE THREAD

**Issue by RavenMacDaddy** [rcmaehl/MSEdgeRedirect#158]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Deployment (Chocolatey, Winget, Etc)

### Install Mode

Service Mode

### Steps to reproduce

App is installed through [Scoop](https://scoop.sh/).

1. Enable the service to start on Windows user login and save.
2. Start **MSER Settings** again, this time with the setting disabled, and save.
3. Notice how the corresponding shortcut in the Startup folder (run `shell:startup`) doesn't get deleted to reflect the action taken in **MSER Settings** in step 2.

### ✔️ Expected Behavior

If I have the option to run on startup unticked and save, I expect the shortcut in the Startup folder to be deleted to reflect this action.

### ❌ Actual Behavior

The shortcut isn't deleted, which means the service still starts up on Windows user login.

### Microsoft Windows version

Windows 11 - 22621.160

### Other Software

**Mozilla Firefox** is installed as the default browser.

**Comment by rcmaehl** [comment]
Fixed in bb0021e9115a84f96d9492d66b04de705956f0e1
