### ISSUE TITLE
Custom sites

### ISSUE THREAD

**Issue by ItzPeto** [rcmaehl/MSEdgeRedirect#159]
### Description of the new feature / enhancement

Ability to set custom website for each task.

### Scenario when this would be used?

Custom weather, images sites etc. (In my case, ability to set the weather site to Slovak Hydrometeorological Institute) without having to compile our own version of MSER.

**Comment by rch77** [comment]
Can we get some proper documented way to embed latitude/longitude in the custom weather url? Currently it just appends comma separated values which doesn't necessary match what website may expect.
E.g. weather.gov Hourly Graphical Forecast pages expect &textField1=26.666666&textField2=-81.11111111
https://forecast.weather.gov/MapClick.php?w0=t&w3=sfcwind&w3u=1&w4=sky&w5=pop&w6=rh&w8=rain&w10=lal&w11u=1&w12u=1&AheadHour=0&Submit=Submit&FcstType=graphical&textField1=26.666666&textField2=-81.11111111&site=all&unit=1&dd=0&bw=0
I know there is general option for the weather.gov weekly forecast page but it doesn't pass Celsius/Fahrenheit units right from Windows settings and these weather.gov Hourly Graphical Forecast pages have many more customization options.
