### ISSUE TITLE
Aut2Exe Line 4 Error (i think that i solved it)

### ISSUE THREAD

**Issue by SackNetz** [rcmaehl/MSEdgeRedirect#163]
After installing latest version (0.7.0.1 for that time), I tested with "microsoft-edge:https://google.com" in Run and it doesn't work. And then Edge is trying to start up (but since i deleted, it won't work anymore). Even after uninstalling and properly reinstalling with "AutoIt", it won't work either. if try to compile code there, "AutoIt" shows "Line 4" error. I tried to "run as administartor" but I got the same results (even with source code).

**Comment by rcmaehl** [comment]
## In regards to it not working

I see you deleted Edge, was that with AveYo's script or another method? If you used a method other than AveYo's, it likely didn't leave behind required registry keys and whitelisted files for MSEdgeRedirect or AveYo's ChrEdgeFckOff.bat to work.

## In regards to compiling issues

An Aut2Exe error would be if you're compiling yourself from source. Make sure you have the [Full Version of AutoIt](https://www.autoitscript.com/site/autoit/downloads) installed if doing so. If the error persists, try with the [SciTe4AutoIt](https://www.autoitscript.com/site/autoit-script-editor/downloads/).

**Comment by SackNetz** [comment]
No, it wasn't. Before I installed MSEdgeRedirect i tried to reinstall [Edge Deflector](https://github.com/da2x/EdgeDeflector) but since Microsoft backdoored process with "update" (KB5007262). I used it and it worked fine (before Microsoft forced me to upgrade to Windows 11).
