### ISSUE TITLE
is virus>....?

### ISSUE THREAD

**Issue by forreset06** [rcmaehl/MSEdgeRedirect#165]
**Describe the request**
virus detected by google chrome (version 104.0.5112.81 (official build) (64bit))
Setup files could not be downloaded at all.

The version installed on my computer is 0.7.0.0 version.
It still works well. But I want to update

**Screenshots**
![is_virus](https://user-images.githubusercontent.com/61132258/184522431-12e86cbb-d3d8-488e-add5-972b53701926.png)

**Desktop (please complete the following information):**
 - OS: windows 10 (kor)
 - Build: 21H2 19044.1889

**Additional context**
I want to MSEdgeDirect update...please thank you

**Comment by rcmaehl** [comment]
You can "view all downloads then:

![image](https://user-images.githubusercontent.com/716581/184523301-9b546b1f-9bd5-4344-ab50-ff53e5b963bb.png)

Alternatively, you can install directly from Microsoft's Winget:

`winget install msedgeredirect` from CMD

![image](https://user-images.githubusercontent.com/716581/184523311-8c1f9e89-146e-4e72-a213-5b97b380b977.png)
