### ISSUE TITLE
Detect Locale being used for News and apply it to redirects

### ISSUE THREAD

**Issue by happyboy1992** [rcmaehl/MSEdgeRedirect#168]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

It's hard to say, but sometimes I clicked on the News and all I saw was English news. This happened a lot lately, how could I revert back to Edge? Uninstalling Edge redirect will also disable Edge

### ✔️ Expected Behavior

Showing Vietnamese news all the time

### ❌ Actual Behavior

Showing English news some of the time

### Microsoft Windows version

20H2

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
