### ISSUE TITLE
Invalid parameter window upon startup

### ISSUE THREAD

**Issue by Simzy** [rcmaehl/MSEdgeRedirect#169]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Unsure as it happens when pc is turned on

URIFailures log
`2022/08/28 14:37:09 - Skipped Settings URL: --default-search-provider=? --out-pipe-name=MSEdgeDefaulta3fff4a3h4b70h4650h962fh136fb3f632cc
`

PEBIAT log
`2022/08/28 14:36:39 - Unexpected Commandline: 7|C:\Program|Files|(x86)\Microsoft\Edge\Application\msedge.exe|http://127.0.0.1:1042/E7C8DA76-C9B9-4297-8681-DD878330AFE7?cmd=alert|--headless|--disable-gpu|--remote-debugging-port=0`

### ✔️ Expected Behavior

no window to be appearing with the error

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/978728/187076757-35af5694-888c-46af-bccb-29a30839f80f.png)

### Microsoft Windows version

Windows 10 21H2

### Other Software

It may possible that it is having an issue with Start11.

Quick edit: i tried a restart with Start 11 completely disabled but the issue is the same.

**Comment by rcmaehl** [comment]
I'm assuming you're using an Asus system?

This will be fixed in 0.7.0.2/0.7.1.0. Please use the latest test build: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by Simzy** [comment]
Can confirm i am on Asus motherboard, test build stops that error from coming up, just get a message about it being a test build now lol.
