### ISSUE TITLE
Exe location

### ISSUE THREAD

**Issue by badbcentral** [rcmaehl/MSEdgeRedirect#17]
After launching the exe file from downloads for the first time and doing the setup (setting to active) it now needs to have the exe in the downloads folder. If you copy it somewhere else and launch it - the tray icon appears but the redirect doesn't work.

**Comment by rcmaehl** [comment]
> After launching the exe file from downloads for the first time and doing the setup (setting to active) it now needs to have the exe in the downloads folder. If you copy it somewhere else and launch it - the tray icon appears but the redirect doesn't work.

Can you see if there's a `C:\Program Files\MSEdgeRedirect` folder?

**Comment by badbcentral** [comment]
@rcmaehl yes, there was. I deleted, still needs it in the downloads

**Comment by rcmaehl** [comment]
> @rcmaehl yes, there was. I deleted, still needs it in the downloads

Odd. Can you run:
 `reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe" /s` 
in command prompt for me and screenshot the output?

**Comment by badbcentral** [comment]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/67790845/143725452-756c6be5-f1ae-479c-b31f-48ed2cddb011.png">

**Comment by rcmaehl** [comment]
> <img alt="image" width="650" src="https://user-images.githubusercontent.com/67790845/143725452-756c6be5-f1ae-479c-b31f-48ed2cddb011.png">

!@#$

**Comment by badbcentral** [comment]
Huh

**Comment by rcmaehl** [comment]
> Huh

Yep, See what went wrong. Fixing and releasing 0.4.1.0 here in a bit.

**Comment by rcmaehl** [comment]
@badbcentral Please try test build "MSER" from:

https://github.com/rcmaehl/MSEdgeRedirect/suites/4483062888/artifacts/119405199

**Comment by FadeMind** [comment]
@rcmaehl got it

![20211128-1638083412](https://user-images.githubusercontent.com/9846948/143733254-95acdf87-cbde-413f-8002-4290bcedf1a7.png)
![20211128-1638083402](https://user-images.githubusercontent.com/9846948/143733255-ecacdaeb-7fac-460d-93c9-750e2babde73.png)

1. Launch FIRST TIME `MSEdgeRedirect.exe` from sample location:
`C:\Users\foobar\Desktop\MSEdgeRedirect.exe` as admin
2. Now set app in active mode. 
3. Rename `MSEdgeRedirect.exe` or move else where. 
4. microsoft-edge protocol cannot launch - file missed.
5. After restore proper name and location - all works again.

**Comment by badbcentral** [comment]
> @badbcentral Please try test build "MSER" from:
> 
> https://github.com/rcmaehl/MSEdgeRedirect/suites/4483062888/artifacts/119405199

works!

**Comment by rcmaehl** [comment]
Will release 0.4.1.0 when I get home then
