### ISSUE TITLE
Whitelist more command line flags

### ISSUE THREAD

**Issue by popy2k14** [rcmaehl/MSEdgeRedirect#172]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

I am running msedge.exe with the following command:

"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --autoplay-policy=no-user-gesture-required https://www.google.at

There is noredirect happening and msedge will also not open.

### ✔️ Expected Behavior

msedge.exe will open instead of chrome.

### ❌ Actual Behavior

No new browser tab/window will be opened.

### Microsoft Windows version

21H2 (Build 19044.1706)

**Comment by rcmaehl** [comment]
I've only whitelisted a few command line flags for safety purposes. If you can provide me a list of the flags you want available, I can add them if they're not abusable.

**Comment by popy2k14** [comment]
ok, got you.

The ones that i am currently using are:
--autoplay-policy=no-user-gesture-required
--kiosk

Would be nice if xou could whitelist them.

thx

**Comment by rcmaehl** [comment]
> ok, got you.
> 
> The ones that i am currently using are: --autoplay-policy=no-user-gesture-required --kiosk
> 
> Would be nice if xou could whitelist them.
> 
> thx

Both look okay. I'll get those whitelisted.

**Comment by popy2k14** [comment]
thx

**Comment by popy2k14** [comment]
thx a lot for adding those arguments!
