### ISSUE TITLE
Launching Edge directly or from shortcut results in error

### ISSUE THREAD

**Issue by PacFox** [rcmaehl/MSEdgeRedirect#174]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Service Mode

### Steps to reproduce

After installing the latest testing build when you launch Edge directly (C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe) or through a shortcut that points to that it will result in the below error:
![image](https://user-images.githubusercontent.com/60280495/188107213-ca052a85-484c-4a96-8eb9-fc4ae8354f3d.png)

Launching from msedge_no_ifeo.exe or clicking PDF files will start Edge without any error. If using ms-edge:https://google.com/ or clicking from widgets the default browser will launch.

### ✔️ Expected Behavior

Edge launches without error

### ❌ Actual Behavior

AutoIt error box pops up and Edge does not launch

### Microsoft Windows version

Windows 11 22H2

**Comment by rcmaehl** [comment]
Can Reproduce
