### ISSUE TITLE
MSEdgeRedirect doesn't redirect

### ISSUE THREAD

**Issue by sandromos** [rcmaehl/MSEdgeRedirect#179]
Hi Robert,

I installed MSEdgeRedirect in both modes but it doesn't work in none of both. If I click a Link in an application like Thunderbird or WhatsApp, nothing happens. No message appears. I give you some information.

**OS:** Windows 11, Version: 21H2, Build: 22000.856
**Default Browser:** Google Chrome, Version 105.0.5195.102
**MS Edge:** Version Version 105.0.1343.33

Please let me know, how I can support you to find the issue.

Regards
Sandro

**Comment by rcmaehl** [comment]
Can you provide any logs in %localappdata%\MSEdgeRedirect?

**Comment by sandromos** [comment]
All log files are empty

**Comment by rcmaehl** [comment]
> All log files are empty

That's definitely something. Run the cleanup script from: https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1

And try an install again.

**Comment by sandromos** [comment]
Hi, it was my mistake. I didn't know that a restart after installation is necessary. Now I did it and all redirects are working. If MS Edge is not running the tool works too. I thougt the Edge needs to run.

**Comment by rcmaehl** [comment]
> Hi, it was my mistake. I didn't know that a restart after installation is necessary. Now I did it and all redirects are working. If MS Edge is not running the tool works too. I thougt the Edge needs to run.

Generally a reboot isn't needed but I may start recommending it for the few edge cases where it does. Glad to hear it's working
