### ISSUE TITLE
Invalid parameter - "C:\Program.

### ISSUE THREAD

**Issue by BrendanoElTaco** [rcmaehl/MSEdgeRedirect#180]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Reboot PC

### ✔️ Expected Behavior

Normal program startup with no notification

### ❌ Actual Behavior

After booting pc into windows a message from MSEdgeRedirect pops up that says: Invalid parameter - "C:\Program.
Otherwise, the program behaves correctly.
![Capture](https://user-images.githubusercontent.com/33934145/189497787-a0e909f4-e0e6-4084-ae46-2cf73891be80.PNG)

### Microsoft Windows version

21H2 Build 19044, 1889

**Comment by rcmaehl** [comment]
Please use the latest test build as this is fixed in that test build
