### ISSUE TITLE
searching from start menu opens chrome but doesn't return the search result, searching from run dialog works normally

### ISSUE THREAD

**Issue by Mohab12345678** [rcmaehl/MSEdgeRedirect#185]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

https://user-images.githubusercontent.com/98129432/192951432-e4e56438-c988-4052-a887-34479dc68e06.mp4

### ✔️ Expected Behavior

chrome opens with google as search engine and return the search result from searching via the start menu

### ❌ Actual Behavior

chrome opens with google as search engine and doesn't return the search result from searching via the start menu but opens new chrome page without the result

### Microsoft Windows version

21H2 Build 19044.2006

### Other Software

Google Chrome : Version 106.0.5249.62 (Official Build) (64-bit)
Windows 10 start menu

**Comment by Mohab12345678** [comment]
Running MsEdgeRedirect Version 0.7.0.2, and Edge update services disabled , and Edge & chrome update services disabled and task schedules in task scheduler

**Comment by rcmaehl** [comment]
I've had one other user report this issue in the discord but haven't been able to reproduce yet. I am looking into this however

**Comment by Mohab12345678** [comment]
Okay thanks for replying i hope you can fix it

**Comment by Mohab12345678** [comment]
And one thing i forgot to mention that this behaviour happened after bsod from killing wininit.exe , everything else works normally after bsod only this changed , i think you can reproduce it by killing wininit.exe to trigger bsod

**Comment by Madmick2963** [comment]
I'm also experiencing this. I had taken the cumulative Windows update, so I thought maybe Microsoft did something to break MSEdgeRedirect. I rolled back to a Restore Point prior to taking that update. Didn't fix it. So I tried rolling back to the previous version of MSEdgeRedirect (0.7.0.1), but that also didn't fix it.

**Comment by Mohab12345678** [comment]
Weird i now don't know what the issue is from, but from what i remember i did get the exact same thing back in April and a windows update fixed so i check for updates but i am updated already so there is nothing else i can try

**Comment by Memesy02** [comment]
am also experiencing this on brave w duckduckgo, did the latest cumulative windows update like @Madmick2963

**Comment by bMorgan01** [comment]
I am also having this issue in Firefox now. I uninstalled chrome today and MSEdge Redirect warned me to update to redo some settings (don't remember the exact verbiage) after the uninstall. Does not work before or after updating and a complete reinstall.

**Comment by rcmaehl** [comment]
Hi all, 

Can you run the [Cleanup Script] and do a new install. Apparently, I screwed up some upgrade logic that may be causing some issues.

**Comment by Dallas-J** [comment]
Same issues here, unfortunately the cleanup script didn't help. I am using Chrome with google.com - I found this on Tuesday and all I have done in between then and now was a windows update (as others have done).

**Comment by Mohab12345678** [comment]
i tried the cleanup script and uninstalled MsEdgeRedirect and reinstalled with active mode and still the same issue nothing solved i tried the latest version that is 0.7.0.2 and 0.7.0.1

**Comment by rcmaehl** [comment]
Been able to reproduce. Investigating now

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/193302005-9d7a4dee-874b-48b8-b736-745bbf968f28.png)
![image](https://user-images.githubusercontent.com/716581/193302035-de26d689-af46-4066-a8c2-865ad094ea46.png)
![image](https://user-images.githubusercontent.com/716581/193302068-7189f1c8-b521-4beb-895e-53770e64077f.png)

Looks like `?url=` got added at some point. Maybe as some sort of Protection judging by `Campaign=AddEdgeProt`

Issue started after installing KB5017380

**Comment by rcmaehl** [comment]
Improving Command Line decoding now to make it more robust.

**Comment by rcmaehl** [comment]
Test build is available for download: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.7.1.0/mser.zip

**Comment by Phantasm-Dev** [comment]
Same issue for me, tried all of the things that were in this issue and still percists.

I ran the clean up script and then tried the test build and it seems to have broken the whole app.
When i try to search in the start menu it does nothing when i press enter.
Start closes and then it acts as if nothing ever happened.

When using the `microsoft-edge:https://google.com/` command in the run section results in what we want to happen if that helps.

**Comment by rcmaehl** [comment]
> When using the `microsoft-edge:https://google.com/` command in the run section results in what we want to happen if that helps.
 
Just patched the test command because I apparently broke legacy calls. Give it about 5 minutes and try the test link above again.

**Comment by Phantasm-Dev** [comment]
Sounds good, cheers :)

**Comment by Phantasm-Dev** [comment]
Sorry to be a real pain in the a**, but i seem to have the same issue with the new link also.
I did the clean install again and restarted my pc just in case, the old off and on again trick.
The normal edge works but when instlaling the app it breaks again.

Again the run command works so maybe im just doing something wrong?

**Comment by rcmaehl** [comment]
> The normal edge works but when instlaling the app it breaks again.
Are you using Service Mode or Active Mode?
Additionally, are you on Windows 10 or 11?

**Comment by Phantasm-Dev** [comment]
Active Mode and Win 11

**Comment by rcmaehl** [comment]
> Active Mode and Win 11

Let me spin up my Win 11 VM, Give me a few minutes

**Comment by Phantasm-Dev** [comment]
No problem, take your time!

**Comment by rcmaehl** [comment]
Okay, have found some issues on Windows 11 I'll have to patch.

**Comment by Phantasm-Dev** [comment]
Good news to me, Means i never broke it lol.
Will keep an eye out for updates.
Thanks for the quick responses!

**Comment by cwmschmidty** [comment]
Having the same problem. Active Mode. Windows 11. Only opening chrome but not showing my search results. Commenting to follow the hopeful updates. Thanks!

**Comment by muchisx** [comment]
Having this issue too, Windows 11 and Google Chrome with multiple accounts, opens the account selector always even when I already have it open.

https://user-images.githubusercontent.com/34131801/193379031-307af116-2e7b-40f3-bbce-193f1a266039.mp4

**Comment by zhuher** [comment]
Same problem here. Good luck fixing this!

**Comment by fieraoh** [comment]
All hail windows 11 with active mode

**Comment by bMorgan01** [comment]
I'm on Win 10 active mode!

**Comment by Madmick2963** [comment]
> Test build is available for download: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.7.1.0/mser.zip

This worked for me. 

To be clear, I'm still on the Restore point prior to that latest cumulative Windows update, and it doesn't appear I have KB5017380 installed, but as I previously mentioned, rolling back didn't work for me before with the latest official stable release. 

Also, before installing this new test build, I uninstalled MSEdge Redirect with Revo Uninstaller Pro (a program that clears all registry values and associated leftover folders not normally uninstalled). Then I ran the Cleanup script.

**Comment by Phantasm-Dev** [comment]
> > Test build is available for download: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.7.1.0/mser.zip

Yip, latest test Build works perfectly for me.
All was the same from last night except i installed the latest test build.

**Comment by rcmaehl** [comment]
If anyone else is having issues after installing the latest from:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.7.1.0/mser.zip

Please let me know. Otherwise, I'll be releasing 0.7.1.0 at end of day EST.

**Comment by Dallas-J** [comment]
Test build works great, it's awesome how fast you addressed this!!

**Comment by fieraoh** [comment]
The nightly build does work fine for me

**Comment by mellester** [comment]
> 

Can confirm reinstalling with the script fixes it on win11. Thx
