### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by w311ang** [rcmaehl/MSEdgeRedirect#186]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Service Mode

### Steps to reproduce

Logs all are empty.
![屏幕截图 2022-09-29 231535](https://user-images.githubusercontent.com/30381083/193070848-ff10cdfc-604b-407b-9a16-a483447f637a.png)

### ✔️ Expected Behavior

Redirect to Chrome Beta normally.

### ❌ Actual Behavior

Still open Edge.

### Microsoft Windows version

22H2 Build 22621

**Comment by rcmaehl** [comment]
I'm going to merge this with #185
