### ISSUE TITLE
"Help MSEdgeRedirect get off Google's Blacklist" text is broken in installer

### ISSUE THREAD

**Issue by ItsMeAubey** [rcmaehl/MSEdgeRedirect#193]
![image](https://user-images.githubusercontent.com/35206674/193321682-bd8842b1-f7f5-48ef-a42b-a9281c9c3d66.png)

Picture should be self explanatory :)

Here's the line in question

https://github.com/rcmaehl/MSEdgeRedirect/blob/582c5600863977a5395c842fb2ed0077363cd9c7/MSEdgeRedirect_Wrapper.au3#L519

**Comment by rcmaehl** [comment]
Whoops. The text is removed in the next version anyway.
