### ISSUE TITLE
Some Widgets/Searches Broken. Autoit Error 

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#195]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Win+W
Click on a Widget

### ✔️ Expected Behavior

Redirect

### ❌ Actual Behavior

Array out of bounds error

### Microsoft Windows version

22621.521

**Comment by rcmaehl** [comment]
Fixed in https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by mgfirewater** [comment]
![grafik](https://user-images.githubusercontent.com/66381035/193568786-9d3565be-200c-4d65-81c2-bb6a35eaa1d9.png)
maybe this help to fix i use win 11 22622.608

**Comment by mgfirewater** [comment]
i try the fix of #197 and this fix the widgets links to my standardbroser firefox
