### ISSUE TITLE
Searching url via start menu causes an error popup

### ISSUE THREAD

**Issue by Adolar0042** [rcmaehl/MSEdgeRedirect#197]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Write a url into the start menu (for example www.google.com) and press enter

### ✔️ Expected Behavior

The url opens in new browser tab

### ❌ Actual Behavior

An error message pops up and the browser doesn't open
![image](https://user-images.githubusercontent.com/39769465/193448612-bfc051f5-5f83-4922-a11d-09b2b96d284f.png)

### Microsoft Windows version

22H2 Build 22621.608

**Comment by rcmaehl** [comment]
Please try the latest test build: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

This *should* be fixed.

**Comment by mgfirewater** [comment]
yes it has fixed!

**Comment by Adolar0042** [comment]
Yeah, the build fixed it, thanks!
