### ISSUE TITLE
Test on 22494 

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#2]
Application shouldn't be affected compared to those who hooked directly into the handler, but test anyway.

**Comment by rcmaehl** [comment]
Not working per Cornflakes. Pending investigation

**Comment by gnpaone** [comment]
Yah, it's not working in 22494, it's still asking for edge browser and it's opening in edge
![Screenshot (4835)](https://user-images.githubusercontent.com/78990165/141403097-602cde7a-acfe-4095-8379-5a86193a0531.png)

**Comment by rcmaehl** [comment]
> Yah, it's not working in 22494, it's still asking for edge browser and it's opening in edge ![Screenshot (4835)](https://user-images.githubusercontent.com/78990165/141403097-602cde7a-acfe-4095-8379-5a86193a0531.png)

Can you verify Chrome is set as your default currently? 

Additionally, the app opens the results after Microsoft Edge has been called by Windows unlike other solutions. If you have it open in Edge, does it redirect to Chrome?

**Comment by gnpaone** [comment]
> > Yah, it's not working in 22494, it's still asking for edge browser and it's opening in edge
> 
> Can you verify Chrome is set as your default browser currently?
> 
> Additionally, the app opens the results after Microsoft Edge has been called by Windows unlike other solutions. If you have it open in Edge, does it redirect to Chrome?

Yes, chrome is set as my default browser
No, it opens results in edge, it doesn't invoke/open chrome

**Comment by rcmaehl** [comment]
> Now I installed edge back and I set default for Microsoft edge links to open in Edge instead of Edge dev now it's redirecting to Chrome

Created #3. Will fix ASAP
