### ISSUE TITLE
AutoIt Error: Line 1590

### ISSUE THREAD

**Issue by CZJohny** [rcmaehl/MSEdgeRedirect#201]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [x] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install version 7.1

### Install Mode

Active Mode

### Steps to reproduce

Open any link from tray News show error 

AutoIt Error 
Line 1590 (File "C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe"):

Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded.

Screen:
[https://ibb.co/64WT0cf](url)

### ✔️ Expected Behavior

Open Chrome with content. 

### ❌ Actual Behavior

Open error window

### Microsoft Windows version

21H2 19044.2075

### Other Software

Unable to test nightly 8.0.0 Symantec protection won't allow me to open file due to security level.

**Comment by ErrorRaffyline0** [comment]
Latest builds have addressed these issues, rcmaehl linked this build 2 days ago in #197:
https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by ElitePheonix2009** [comment]
> Latest builds have addressed these issues, rcmaehl linked this build 2 days ago in #197: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

He has said that he is unable to test nightly 8.0.0 because Symantec protection won't allow him to open file due to security level.

**Comment by CZJohny** [comment]
> Latest builds have addressed these issues, rcmaehl linked this build 2 days ago in #197: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

As I wrote into bugreport, Symantec Endpoint Protection won't allow opening this file. Not even to exclude. 7.1. is OK to download and install, 8.0 not.

**Comment by hir0aki** [comment]
Same error here. So while we wait for 0.8.0.0 update, is there a way to disable EdgeRedirect? I tried unchecking Edge Stable from Active Mode Options and press Save but when I open the settings again is still Checked.

**Comment by khei** [comment]
So green on this) Had same 1590-error,...but now  **_no errors_**: 
Using ver. 8.0.0. although I did get a **very** stong UAC//Defender warning when saving file after DL. 
Manged to install when by fist un-installing, and then installing in 'Service mode' ... 

The file used is ver.8 Nightly: 'mser.zip' - SHA256=13635b13cfbe37d234c105eac0efa7cec11da31630952d3da9cdff229f0510a7

Version: Windows 11 Home
Version: 21H2
Build: 22000.1042
Experience pack for Windows-function: 1000.22000.1042.0

**Comment by Axer128** [comment]
> Same error here. So while we wait for 0.8.0.0 update, is there a way to disable EdgeRedirect? I tried unchecking Edge Stable from Active Mode Options and press Save but when I open the settings again is still Checked.

Can simply uninstall it via settings app or programs and features control panel

**Comment by osm0sis** [comment]
Downgrade to 0.7.0.2 also works for now. (y)

**Comment by CZJohny** [comment]
> Downgrade to 0.7.0.2 also works for now. 👍

Thanks, downgrade helped :)

**Comment by krashd8** [comment]
This is the exact error I was getting, completely the same setup as CZJohny, but downgrading to 0.7.0.2 only partially fixed the problem.

Now when I click on something inside the "News and interests" drawer on the taskbar it no longer gives me the popup error (Line 1590), and it successfully opens a new tab in Chrome for the URL, but every thing I click on results in the same tab contents...

`Redirect Notice
 The page you were on is trying to send you to https://www.worldbank.org/en/home.

 If you do not want to visit that page, you can [return to the previous page](https://www.google.com/url?q=https://www.worldbank.org/en/home#).`

Whether I click on a news article or the weather link, or anything else, they always just open a tab in Chrome that displays the above text with the two links in it. 

Any ideas?

**Comment by t0rzz** [comment]
Same problem with latest version.
