### ISSUE TITLE
Enormous number of disruptive update notifs

### ISSUE THREAD

**Issue by Triarite** [rcmaehl/MSEdgeRedirect#202]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [x] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Occurs randomly

### ✔️ Expected Behavior

It would give me a pop-up asking me to update. This pop-up would not remain at the front of the screen or occur multiple times

### ❌ Actual Behavior

Occasionally, seemingly at random, MSER will give me not only an always-at-front update notif that disrupts me (when I'm gaming especially), but it sometimes will also appear countless times, like in the attached image.

![image](https://user-images.githubusercontent.com/79460443/194171781-c175e88f-b7cc-4a28-86c3-6b81be8c5074.png)

### Microsoft Windows version

21H2 OS Build 19044.2006

**Comment by Triarite** [comment]
I would like either a fix, or preferably, a way to disable update notif's entirely

**Comment by xerz-one** [comment]
Would support adding an option to disable notifications (and another one for autoupdate) even if this bug gets fixed, particularly since I have installed MSER to people who don't know about its existence nor understand English and the popups merely become a repetitive annoyance.

**Comment by rcmaehl** [comment]
> Would support adding an option to disable notifications (and another one for autoupdate) even if this bug gets fixed, particularly since I have installed MSER to people who don't know about its existence nor understand English and the popups merely become a repetitive annoyance.

Disabling updates is already supported.

1. Open regedit
2. Navigate to `HKLM\SOFTWARE\Policies`
3. Create a key for `Robert Maehl Software`
4. Create a subkey for `MSEdgeRedirect`
5. Create a DWORD for `NoUpdates`
6. Set DWORD to `1`

![image](https://user-images.githubusercontent.com/716581/194728285-baa1fbb7-9376-4ae0-8503-04359039021a.png)

Alternatively: Save this file as a .reg and double click it to import into the registry
[NoUpdates.saveas.reg.txt](https://github.com/rcmaehl/MSEdgeRedirect/files/9740286/NoUpdates.saveas.reg.txt)

I'll add an an extra for no notifications at all.

**Comment by rcmaehl** [comment]
This should be improved slightly per 5f9f4b8

Still working on getting the solution working to remove the messages entirely
