### ISSUE TITLE
Latest update broke website "search" from start menu

### ISSUE THREAD

**Issue by CJNiiva** [rcmaehl/MSEdgeRedirect#203]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

type google.com inside windows search

### ✔️ Expected Behavior

open google.com on chrome

### ❌ Actual Behavior

error message 
![image](https://user-images.githubusercontent.com/19373615/194297059-6019906b-5e7c-4723-841d-2f8858622bea.png)

### Microsoft Windows version

22h2 build 22622.598

**Comment by rcmaehl** [comment]
> also of note, I had installed msedgeredirect with winget, but had to uninstall it and reinstall it manually as winget did not have the latest version.

Should be fixed in the current test build: 
https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

If not, please comment on #195
