### ISSUE TITLE
Windows Security Detected Trojan:Script/Phonzy.A!ml in MSEdgeRedirect_x86.exe from Testing Build

### ISSUE THREAD

**Issue by AdamHardix** [rcmaehl/MSEdgeRedirect#204]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Just have the install file on system and wait for Windows Security to detect Trojan.

![ApplicationFrameHost_d0gvdGlTPC](https://user-images.githubusercontent.com/115196713/194441546-13dbfb09-3ce8-4f0e-adb8-3b65b5dfcc5b.png)

### ✔️ Expected Behavior

Not to have a Trojan on my system from downloading this software.

### ❌ Actual Behavior

Have a Trojan on my system from downloading this software.

### Microsoft Windows version

21H2 Build 19044.2006

**Comment by rcmaehl** [comment]
Duplicate of #37
Windows 11 doesn't have a 32-bit version, so you should be using MSEdgeRedirect.exe, not MSEdgeRedirect_x86.exe
