### ISSUE TITLE
Need command-line silent install option

### ISSUE THREAD

**Issue by SamHills** [rcmaehl/MSEdgeRedirect#21]
I need the ability to install the program silently from a batch file, with switches to specify installation options (very important: install for all users and start automatically with Windows).

**Comment by rcmaehl** [comment]
@SamHills I'm sure I can add this for you. Give me a couple days as I've been slammed at work.

**Comment by rcmaehl** [comment]
@SamHills Would you be fine with a setup.ini file instead of passing a bunch of flags?

**Comment by SamHills** [comment]
Yes.  Anything that I can put in a batch file.

**Comment by rcmaehl** [comment]
How to make a setup.ini file to be used can be found here:
https://github.com/rcmaehl/MSEdgeRedirect/wiki/Setup.ini-File-Configuration

Hoping to get 0.5.0.0 released afternoon "tomorrow" (12/12)

**Comment by SamHills** [comment]
Thanks!  Please provide instructions on how to use setup.ini, including where to put it, the command line needed to invoke it and a sample file showing the syntax required.
Also please add DuckDuckGo to the list of search engines supported.

**Comment by rcmaehl** [comment]
> Thanks! Please provide instructions on how to use setup.ini, including where to put it, the command line needed to invoke it and a sample file showing the syntax required. Also please add DuckDuckGo to the list of search engines supported.

DuckDuckGo is supported. Let me fix that. Forgot I put that as an abbreviation. Will add a wiki page for deployment instructions.

**Comment by rcmaehl** [comment]
[Deployment](https://github.com/rcmaehl/MSEdgeRedirect/wiki/Deploying-MSEdgeRedirect) and [Setup.ini](https://github.com/rcmaehl/MSEdgeRedirect/wiki/Setup.ini-File-Configuration) wiki
