### ISSUE TITLE
Error while opening news/weather from widget menu

### ISSUE THREAD

**Issue by ProgramerPanda** [rcmaehl/MSEdgeRedirect#210]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/9120649/196542730-c552a85c-ad73-4e02-83d0-87d1f1c72a38.png">

**Comment by ElitePheonix2009** [comment]
Latest builds have addressed these issues, rcmaehl linked this build in #197:
https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip
