### ISSUE TITLE
Edge Failing to Open PDFs - Error

### ISSUE THREAD

**Issue by MG-LSJ** [rcmaehl/MSEdgeRedirect#219]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [x] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

When opening PDFs, this error occurs.
This only occurred when updated to the latest release 0.7.0.2. Tried fresh installing but it still exists.

MS edge is set as the default PDF viewer.

![image](https://user-images.githubusercontent.com/73988826/198643856-25228ac9-8dc7-4c33-851b-d2d3b46b97cf.png)

MSER settings
<img width="345" alt="image" src="https://user-images.githubusercontent.com/73988826/198645172-4b3e7a59-f93e-4e66-9f66-236ade64da29.png">

### ✔️ Expected Behavior

PDF to open in Edge

### ❌ Actual Behavior

This error shows.

### Microsoft Windows version

22H2 22621.755

**Comment by rcmaehl** [comment]
A build with this fixed should available shortly:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip
