### ISSUE TITLE
This project marked as dangerous (red) , in Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by yeoldehacker** [rcmaehl/MSEdgeRedirect#220]
i opened this project , from google , got that red page of warning
here is the screenshot
![image](https://user-images.githubusercontent.com/75392515/199165214-e3e022a0-aa31-4c99-bca5-d535760bd8c6.png)

**Comment by SiddharthSharma16923** [comment]
![image](https://user-images.githubusercontent.com/75392515/199165432-798adc20-9e8e-4041-99a6-0950c2671791.png)

**Comment by SiddharthSharma16923** [comment]
![image](https://user-images.githubusercontent.com/75392515/199165562-9816d37a-6de2-4115-a0a5-95831f81e91f.png)

**Comment by SiddharthSharma16923** [comment]
and this https://www.virustotal.com/gui/file/9f903df9025c8b5c22e5c9c80730d3d32db920cf08eb147e6158eccf6ffde60c

**Comment by SiddharthSharma16923** [comment]
i am sorry i posted this without knowing that is is a known issue
i marked it as safe  👍 on both virus total and google report!

**Comment by rcmaehl** [comment]
> i am sorry i posted this without knowing that is is a known issue i marked it as safe 👍 on both virus total and google report!

Yep! I'm aware. Thank you for helping submit a false positive!

**Comment by yeoldehacker** [comment]
:( tho this doesnt seem to work for me at all , i wanted windows search results to open in chrome

**Comment by yeoldehacker** [comment]
![image](https://user-images.githubusercontent.com/75392515/200119918-8e9c2ba7-e685-4848-9861-369df944ed09.png)

winver screenshot

**Comment by ElitePheonix2009** [comment]
> :( tho this doesnt seem to work for me at all , i wanted windows search results to open in chrome

You can use either this test build or the latest test build, this issue was fixed:
https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.7.1.0/mser.zip

**Comment by yeoldehacker** [comment]
![image](https://user-images.githubusercontent.com/75392515/200159581-b5718375-58c8-484f-8778-de69e80e4401.png)

i have force killed edge using a little trick  , maybe that is interfering with it , i tried both edges(as displayed in ss)
![image](https://user-images.githubusercontent.com/75392515/200159765-d6ae4b43-466e-40de-9e15-abf6fe5a44b9.png)

i get this error when i try to open the iconless (second) edge  from search
![image](https://user-images.githubusercontent.com/75392515/200159662-ad62e119-5553-430d-b225-8e03418612ad.png)

also tried the latest release of this tool , still no luck 
i give up

**Comment by yeoldehacker** [comment]
not that i care anymore , but
more on latest release : installed it in active mode this time , didnt workout , it crashed as i hit enter in the search , left windows bugged , some ghost window ( didnt found anything in task manager )  , was taking away focus from chrome as i was trying to type here , had to logout to fix

**Comment by yeoldehacker** [comment]
i am not a coder or anything , but what if i make( i never will ) a exe to take all arguments , and send them to chrome
name it msedge.exe , and replace the original edge.exe
and voila (or not?)
this will also include replacing edgeupdater
is it sane , coder sama(lol)?

**Comment by rcmaehl** [comment]
> i am not a coder or anything , but what if i make( i never will ) a exe to take all arguments , and send them to chrome name it msedge.exe , and replace the original edge.exe and voila (or not?) this will also include replacing edgeupdater is it sane , coder sama(lol)?

Unfortunately, unless you have Microsoft's Security Certificate this does not work.

**Comment by rcmaehl** [comment]
> ![image](https://user-images.githubusercontent.com/75392515/200159581-b5718375-58c8-484f-8778-de69e80e4401.png)
> 
> i have force killed edge using a little trick , maybe that is interfering with it , i tried both edges(as displayed in ss) ![image](https://user-images.githubusercontent.com/75392515/200159765-d6ae4b43-466e-40de-9e15-abf6fe5a44b9.png)
> 
> i get this error when i try to open the iconless (second) edge from search ![image](https://user-images.githubusercontent.com/75392515/200159662-ad62e119-5553-430d-b225-8e03418612ad.png)
> 
> also tried the latest release of this tool , still no luck i give up

MSEdgeRedirect will not work if msedge.exe has been renamed/removed.
