### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by littlesquirt1** [rcmaehl/MSEdgeRedirect#222]
I just installed and it wont work.
![image](https://user-images.githubusercontent.com/56567956/202807310-a20ca3d4-50a9-4e70-ba87-abb11e845d28.png)

I pressed `WIN` + `R` and typed `microsoft-edge:https://google.com` but there is still the same error.

**Comment by rcmaehl** [comment]
Are you able to provide a screenshot of msinfo32?

**Comment by littlesquirt1** [comment]
![image](https://user-images.githubusercontent.com/56567956/202922426-a9491b9f-dfcd-4d4e-ab27-54e21b7e219e.png)

**Comment by littlesquirt1** [comment]
NoMoreEdge gives the same error.

**Comment by rcmaehl** [comment]
Odd. I'm not seeing anything out of the normal for your computer.

If you open Settings -> About, can you confirm that it doesn't say "in S mode" under "Windows Specifications"?

**Comment by rcmaehl** [comment]
Let me know if version 0.7.3.0 has the same issue. Considering you're having the same issue with NoMoreEdge, I honestly don't know what to say.

**Comment by littlesquirt1** [comment]
Still no luck

**Comment by rcmaehl** [comment]
I would advise using https://github.com/AveYo/fox/blob/main/OpenWebSearch.cmd as a workaround. I haven't had any one report this issue yet out of nearly 100.000 downloads now.

Closing as won't fix. Sorry :(
