### ISSUE TITLE
Some Web Apps open links in Edge (e.g. Twitter)

### ISSUE THREAD

**Issue by ZainAjam** [rcmaehl/MSEdgeRedirect#224]
I use Edge exclusively to create web apps on Windows, because I enjoy how Edge uses the notification panel of Windows. It is better integrated. But for my day to day browsing outside of the web apps I've created, I use chrome. The challenge is that if I have gmail (as an example) as a web app, and I click on a link in an email in Gmail Edge Web app, the link opens up in Edge, when I want it to open up in Chrome. Is there anyway to force all links clicked in Edge to open up in my default browser Chrome?

**Comment by Masamune3210** [comment]
Probably not, considering you are already in the browser, the browser itself handles how to deal with links that are opened in a page.

**Comment by rcmaehl** [comment]
Unfortunately, some apps specifically call for a new tab instead of the default browser. E.g. Links in Netflix will open the default browser, but links in twitter will open in Edge. Since the web apps are Edge itself, I can't intercept the call.
