### ISSUE TITLE
When using Edge for web app notifications, MSEdgeRedirect blocks actions when clicking on the notification

### ISSUE THREAD

**Issue by ZainAjam** [rcmaehl/MSEdgeRedirect#225]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

1. Go to youtube.com in Edge and install it as a web app
2. When a youtube notification comes through (while MSEdgeRedirect is installed), click on the notification
3. Nothing will happen. The action seems to be blocked by MSEdgeRedirect 

### ✔️ Expected Behavior

Allow Edge to receive action calls from the edge web app notifications

### Microsoft Windows version

22H2 22621.898

**Comment by rcmaehl** [comment]
Was finally able to reproduce this. I'll figure out how to get this excluded.

Some metadata for myself below

![image](https://user-images.githubusercontent.com/716581/205480066-b282bc8c-4080-49c0-b2f4-f8afe5fb8972.png)

**Comment by rcmaehl** [comment]
This should be fixed in the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

If it's not feel free to reopen the issue :)
