### ISSUE TITLE
Uninstalled MSEdgeRedirect, now shows 2x in System Tray settings, not in System Tray

### ISSUE THREAD

**Issue by CharmaineKavanagh** [rcmaehl/MSEdgeRedirect#228]
I am a home user and installed MSEDGEDIRECT as I use Google not Edge for searches. However, I see it 2x in my System Tray settings. I thought to uninstall and start over. I uninstalled through Programs, but I still have it showing in System Tray settings. I see there is a Uninstall script and I ran it in PowerShell, but it didn't work and says not found, failure, or invalid on most lines. I want to avoid another reset as it is very time consuming.
![Screenshot 2022-12-02 141057](https://user-images.githubusercontent.com/119703379/205380125-cc5e9be0-67bc-44f7-8e21-734e46506b0e.png)

**Comment by rcmaehl** [comment]
This is something Windows keeps track of itself. You can clear it using the following instructions:

https://www.winhelponline.com/blog/clear-customize-notifications-tray-items-windows-7-vista-xp/

**Comment by CharmaineKavanagh** [comment]
Thanks. I used regedit method and deleted the 2 values indicated, MsEdgeRedirect is gone. Now there is an Audio icon labelled Task Manager appearing in the System Tray settings. There is another Audio icon but it is correct as its labelled HP Audio Switch. Weird instances since Win11 update.

Charmaine Kavanagh
________________________________
