### ISSUE TITLE
Won't work w/ Hurl (browser chooser) - endless loop

### ISSUE THREAD

**Issue by lucaspestana** [rcmaehl/MSEdgeRedirect#229]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [x] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Unsure

### Steps to reproduce

I recently started using [Hurl](https://github.com/U-C-S/Hurl) by @U-C-S, a [browser choosing utility](https://reddit.com/r/windows/comments/z8uw9d/comment/iyp5jya/) that will always pop-up a prompt, asking the user to choose which browser they want to use to open a hyperlink (usually a regular HTTPS or HTTP one).

(In case this is relevant, these are my currently installed browsers: regular Edge, Edge Dev, Vivaldi Snapshot, Firefox Developer Edition, IE11†, regular Google Chrome‡. ### † For whatever reason, IE [and IE Mode on Edges] has stopped working recently, anyway, whatever. ‡ I barely use regular Edge and Google Chrome, but I sometimes use the second one for some webapps [PWAs].)

I configured Hurl to always to prompt me choose between my three faves: Vivaldi / Edge Dev* / Firefox Dev (* [with a special argument for a rounded squared omnibox](https://techcommunity.microsoft.com/t5/discussions/rounded-address-bar-omnibox-in-latest-versions-of-edge/m-p/3670194#M56199))

.

THE ACTUAL ISSUE:

1. With all apps installed and configured, I try to open a news article from the News & Interests widget.
2. MSEdgeRedirect (installed as admin) detects the microsoft-edge: hyperlink and sends it to the default "browser", which is Hurl.
3. Hurl pops up and prompts me to choose from my three browsers.
(continues…)

### ✔️ Expected Behavior

(…continued)
4. What I expected to happen is that Hurl would pop up, I would choose "Edge Dev" (which's most often my preferred one of the bunch anyway), and Edge Dev would launch and load the page.
5. NOTE: Indeed, right after installing MSEdgeRedirect (Hurl was already pre-installed), it worked fine (with that ugly fully rounded omnibox, by the way). However, from the second time around on, it didn't!…
(continues again…)

### ❌ Actual Behavior

(…again continued)
6. If I choose "Edge Dev" (and insist on choosing it, again and again)… an endless, l∞ping cycle ensues, where Hurl tries to pass the URL to Edge Dev (msedge.exe), but MSEdgeRedirect detects this and decides it must not be opened with disgusting Microsoft Edge, but rather with the user's default browser (which in my OS is now Hurl).
7. I can be sure that all of the above is happening because I can see the MSEdgeRedirect.exe process loading and unloading again and again in a processes monitor app -- and msedge.exe itself never even loads.
8. In the end, the link to the news article will never open as long as I insist on selecting "Edge Dev" and unless I choose another, non-Edge browser (Vivaldi, Firefox, etc.).
9. I tried setting up the Active Mode(s) of MSEdgeRedirect -- but oddly, it seems the settings wouldn't stick. I dunno. I selected the checkboxes (tried: unchecking all, unchecking only Edge Dev, checking Edge Dev alone) and clicked Save; next time I opened MSEdgeRedirect Settings, the checkboxes would all be checked, regardless of my previous setup of choice. 
10. Running microsoft-edge:https://google.com and trying to choose "Edge Dev" from Hurl dead-ends in the same l∞p scenario.
11. SOLUTION: I rarely click on Windows' own in-system links, so MSEdgeRedirect was more of a curiosity for me rather than something I actively need. (I even went as far as force-removing Internet search from Windows Search on taskbar, my Search only shows me my own apps and files and local stuff; but I digress. Besides, I actually mostly like Microsoft Edge, it's an okay everyday browser for me.) ### So, I simply uninstalled MSEdgeRedirect as normal. Everything is back to normal, Hurl works in most cases (handling regular HTTPS and HTTP links) -- and news articles from News & Interests will still open without being intercepted by Hurl.

### Microsoft Windows version

Windows 10 22H2

### Other Software

[Microsoft Edge Dev](https://www.microsoftedgeinsider.com/)

**Comment by rcmaehl** [comment]
I'll definitely look into this!

**Comment by rcmaehl** [comment]
Can you upload `%localappdata%\MSEdgeRedirect\logs\AppGeneral.log`? After some debugging, I have an idea but I need to confirm the issue.

**Comment by lucaspestana** [comment]
> Can you upload `%localappdata%\MSEdgeRedirect\logs\AppGeneral.log`? After some debugging, I have an idea but I need to confirm the issue.

Yes, I can do that! I'll be doing it tomorrow or over the next few days.

**Comment by lucaspestana** [comment]
> Can you upload `%localappdata%\MSEdgeRedirect\logs\AppGeneral.log`? After some debugging, I have an idea but I need to confirm the issue.

Here it is: https://1drv.ms/u/s!Avd_TL84UM5zqb4fgQKIO3xO0qT5Gw?e=zdM6gu (there's five .LOG files inside a single ZIP).

**Comment by lucaspestana** [comment]
> Can you upload `%localappdata%\MSEdgeRedirect\logs\AppGeneral.log`? After some debugging, I have an idea but I need to confirm the issue.

I think I sent

**Comment by lucaspestana** [comment]
> Can you upload `%localappdata%\MSEdgeRedirect\logs\AppGeneral.log`? After some debugging, I have an idea but I need to confirm the issue.

I think I sent too many files; here's only AppGeneral.log (and my apologies): https://1drv.ms/u/s!Avd_TL84UM5zqb4h7LLquClf9Cw9Iw?e=ns07G0

**Comment by rcmaehl** [comment]
> > Can you upload `%localappdata%\MSEdgeRedirect\logs\AppGeneral.log`? After some debugging, I have an idea but I need to confirm the issue.
> 
> I think I sent you too many files; here's only AppGeneral.log (and my apologies): https://1drv.ms/u/s!Avd_TL84UM5zqb4h7LLquClf9Cw9Iw?e=ns07G0
> 
> Let me know in case you'd like me to reinstall MSEdgeRedirect in case another further log is needed.

I'm still working on this :)

**Comment by rcmaehl** [comment]
Let me reopen this so I don't forget again

**Comment by rcmaehl** [comment]
This should be fixed for active mode in the latest dev build.

**Comment by U-C-S** [comment]
Hey, I'm the author of Hurl, came here since I got referenced, didn't notice this one till now as the issue got closed. Is there anything I can do so You wouldn't need to hard code `Hurl.exe` into the code ??

**Comment by rcmaehl** [comment]
> Hey, I'm the author of Hurl, came here since I got referenced, didn't notice this one till now as the issue got closed. Is there anything I can do so You wouldn't need to hard code `Hurl.exe` into the code ??

Not really. I'm breaking your functionality, not the other way around. I'll probably add more parent process aware handling soon.
