### ISSUE TITLE
Won't install under Windows 10 22H2

### ISSUE THREAD

**Issue by 1di9** [rcmaehl/MSEdgeRedirect#231]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Launching installation, choosing Active Mode, selecting active mode options and choosing "install"

### ✔️ Expected Behavior

Correct installation procedure ending

### ❌ Actual Behavior

after clicking on "install", installation prcedure close and nothing elese happens. Edge is not redirected to my favorite browser

### Microsoft Windows version

Windows 10 22H2

**Comment by rcmaehl** [comment]
That seems extremely odd. Not even any autoit error boxes?

**Comment by 1di9** [comment]
Why did you close as completed? I replyed by email

**Comment by Couchy** [comment]
The same thing happened to me when trying to upgrade. After every failed install attempt, this line was written in AppData\Local\MSEdgeRedirect\logs\AppFailures.log

2022/12/28 11:09:35 - [CRITICAL] Unable to copy application to 'C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe'

This is despite running with admin privilege. Then I manually deleted the existing exe in Program Files, and the install worked.

**Comment by rcmaehl** [comment]
I've added error handling for this and will create a permanent fix in version 0.8.0.0

**Comment by rcmaehl** [comment]
#65

**Comment by 1di9** [comment]
I've tryied to install update 7.3.0 but after clicking on Finish in final windows with "Update successfully" Edge is no more installed and links in msn news don't open

**Comment by rcmaehl** [comment]
> I've tryied to install update 7.3.0 but after clicking on Finish in final windows with "Update successfully" Edge is no more installed and links in msn news don't open

Please open apps & features, select Microsoft Edge, and choose change. This will run a repair on edge.
