### ISSUE TITLE
MsEdgeRedirect no longer opens Chrome.

### ISSUE THREAD

**Issue by haraop** [rcmaehl/MSEdgeRedirect#232]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

1. Install update
2. Search for something on the Windows Bar or click on any news on the widget.

Stable (0.7.2.0) nor testing (0.7.2.1) versions work.
Service mode doesn't work either, even when I can see it active on the Task manager. Active mode doesn't show any task on task manager. 

Running microsoft-edge:https://google.com/ DOES NOT redirect successfully. I'm sorry if this is in the wrong section, but it seems to be mandatory for me to choose in order to report this.

### ✔️ Expected Behavior

Redirect to Chrome

### ❌ Actual Behavior

Edge opens

### Microsoft Windows version

22H2 Build 22621.819

### Other Software

Nothing

**Comment by haraop** [comment]
AppFailures.log shows 
"2022/12/11 17:36:32 - [CRITICAL] Unable to copy application to 'C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe'!"

Knowing this, I manually erased the folder, tried to install again, and it did work now! It can be closed now, but just to let you know if someone else has this problem again.

**Comment by rcmaehl** [comment]
> AppFailures.log shows "2022/12/11 17:36:32 - [CRITICAL] Unable to copy application to 'C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe'!"
> 
> Knowing this, I manually erased the folder, tried to install again, and it did work now! It can be closed now, but just to let you know if someone else has this problem again.

This will no longer be an issue in 0.7.3.0 onwards
