### ISSUE TITLE
Some News Categories are not handled (e.g. TechAndScience)

### ISSUE THREAD

**Issue by huurdy** [rcmaehl/MSEdgeRedirect#233]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Clicking on an item in the popup Weather / News and Interest button in windows 10, then clicking on an item, will often result in a different page being opened in Chrome
![edge redirect incorrect](https://user-images.githubusercontent.com/121280738/209288543-4eb7e3f3-6742-4c75-9577-29ad72979364.png)

### ✔️ Expected Behavior

In this example, application should redirect to Popular Science website and article, instead the search result in the background was the result. 

### ❌ Actual Behavior

Redirect did not happen as expected. This is just one example of a strange redirect
![strange redirect](https://user-images.githubusercontent.com/121280738/209289666-b86775fe-2207-4b43-a0ac-331329a0feda.png)

### Microsoft Windows version

22H2 Build 19045.2364

### Other Software

Chrome Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by rcmaehl** [comment]
The one for Popular Science will be fixed.

The one for redirect notice unfortunately can't be fixed as it's a google anti-bot measure. You can set MSN News to DuckDuckGo and it shouldn't have that issues however.

**Comment by huurdy** [comment]
Thanks for Investigating and replying.

**Comment by huurdy** [comment]
Thanks for Investigating and replying.

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
