### ISSUE TITLE
Doesn't start at all, not even microsoft-edge:https://example.com

### ISSUE THREAD

**Issue by linuzzx** [rcmaehl/MSEdgeRedirect#235]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [ ] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

tried to search something, doesn't do anything

URIFailures.log and AppSecurity.log:
2023/01/01 13:56:44 - Blocked Unsafe URL: --no-startup-window --win-session-start /prefetch:5
2023/01/02 12:36:00 - Blocked Unsafe URL: --no-startup-window --win-session-start /prefetch:5
2023/01/03 10:50:01 - Blocked Unsafe URL: --no-startup-window --win-session-start /prefetch:5
2023/01/04 18:24:06 - Blocked Unsafe URL: --no-startup-window --win-session-start /prefetch:5
2023/01/04 21:01:57 - Blocked Unsafe URL: --no-startup-window --win-session-start /prefetch:5

the rest is empty

### ✔️ Expected Behavior

do it

### ❌ Actual Behavior

doesn't

### Microsoft Windows version

22H2 Build 22621.963

**Comment by rcmaehl** [comment]
> ### ✔️ Expected Behavior
> do it
> 
> ### ❌ Actual Behavior
> doesn't

Understandable. Let me upgrade to that build on my Windows 11 machine and see if MS changed some stuff.

**Comment by rcmaehl** [comment]
Closing to merge with #236
