### ISSUE TITLE
Reinstall may be needed for Windows 11 Build 22621

### ISSUE THREAD

**Issue by FelixHohgraebe** [rcmaehl/MSEdgeRedirect#236]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

I mostly use this programm to redirect my  windows search to my default browser(firefox) and search engine(duckduck).
After upgrading windows when searching something it would just open an new empty browser window.
I reinstalled MSEdgeRedirect. Now it  works but seems to be slower than before.
Thanks and good day!

### Microsoft Windows version

Windows 11, version 22H2

**Comment by rcmaehl** [comment]
Can you provide your build number from the WinVer command?

**Comment by FelixHohgraebe** [comment]
Version	10.0.22621 Build 22621
Hope it's the right number

**Comment by rcmaehl** [comment]
> Version 10.0.22621 Build 22621 Hope it's the right number

Yep. Assuming MS Changed something. You aren't the only one reporting issues (#235)

**Comment by FelixHohgraebe** [comment]
Hello
I just discovered that my default app for .html change to another browser (chrome)
I am pretty sure it was firefox. Maybe the update reseted this setting.

**Comment by smithj76** [comment]
I barely understand github, never mind coding so i never write issues. first off, HUGE FAN. when this fails, i'm never mad you. I know precisely who to blame. 

second i'm on:

Edition	Windows 11 Enterprise Insider Preview
Version	22H2
Installed on	‎1/‎5/‎23
OS build	25272.1000
Experience	Windows Feature Experience Pack 1000.25272.1000.0

However, i just noticed msedgeredirect was uninstalled just now, despite the build last updating 6 days ago. the only update that isn't mrt.exe or 'definition' that seem to update daily was the following:

2023-01 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows Version Next for x64 (KB5022411)
Successfully installed on ‎1/‎10/‎23

I do not know what version of the app I had installed, but i did install via 'scoop' quite recently

Hope this was helpful, thanks again!
