### ISSUE TITLE
MSER unable to update and gives a critical error

### ISSUE THREAD

**Issue by gnpaone** [rcmaehl/MSEdgeRedirect#240]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Download the setup, and click next and update. (Admin mode) - version 0.8.0.0-dev (I always use nightly 😅)

### ✔️ Expected Behavior

Update mser

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/78990165/213361085-3621cbd2-fe1f-4bfa-a1f7-33cebdca2ba8.png)

### Microsoft Windows version

Dev Build 25278

**Comment by gnpaone** [comment]
Also please update your bug template and remove compulsory to preflight checklist checkboxes😳
![image](https://user-images.githubusercontent.com/78990165/213361660-2357f3ed-b518-4306-a88d-18dff706a8f9.png)
Submit button will be enabled only if first two checkboxes ticked according to current template, but what if for example second statement isn't true, still I have to check the box to submit the issue 😅

**Comment by rcmaehl** [comment]
> Also please update your bug template and remove compulsory to preflight checklist checkboxes😳 ![image](https://user-images.githubusercontent.com/78990165/213361660-2357f3ed-b518-4306-a88d-18dff706a8f9.png) Submit button will be enabled only if first two checkboxes ticked according to current template, but what if for example second statement isn't true, still I have to check the box to submit the issue 😅

WHOOPS

**Comment by gnpaone** [comment]
Any updates regarding that error? 😶

**Comment by rcmaehl** [comment]
> Any updates regarding that error? 😶

Working on an actual fix.

In the meantime, you can manually copy msedgeredirect.exe to the folder and it will work fine.

**Comment by rcmaehl** [comment]
I believe I found this issue for this in which "RunAs" isn't always working. Looking into this

**Comment by gnpaone** [comment]
Also after that critical error it broke the previous installed version too so now it opens in msedge even if exe file copied manually 🫣

**Comment by rcmaehl** [comment]
> Also after that critical error it broke the previous installed version too so now it opens in msedge even if exe file copied manually 🫣

Yeah, cleanup of the old version occurs before install of the new version. I may change that.
