### ISSUE TITLE
Intercept default HTTP/HTTPs handler to replace bing results there as well.

### ISSUE THREAD

**Issue by bigplayer-ai** [rcmaehl/MSEdgeRedirect#242]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Searching online in taskbar redirects me to bing search instead of google search.
Go to taskbar
2) startup settings
3) right click any program
4) search online
5) search is in bing and not google as I chose it.

### ✔️ Expected Behavior

search the program in google instead of bing.

### ❌ Actual Behavior

search the program in bing instead of google.

### Microsoft Windows version

22H2 BUILD 22621.1194

**Comment by rcmaehl** [comment]
Are you referring to this screen?

![image](https://user-images.githubusercontent.com/716581/215495376-9adecdc2-686d-4e3c-83fa-7629f1bf617f.png)

**Comment by bigplayer-ai** [comment]
Yes 100%

**Comment by rcmaehl** [comment]
I'm going to stay out of this for now. Chrometana-Pro does it well and other extensions are available. I'll be documenting those and adding a plug for them at the end of the install
