### ISSUE TITLE
Can't update Edge

### ISSUE THREAD

**Issue by purevertigo** [rcmaehl/MSEdgeRedirect#244]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Tried to update Edge. Can't.

### ✔️ Expected Behavior

Edge updates.

### ❌ Actual Behavior

An error occurred while checking for updates: We couldn't create that component (error code 1: [0x80004005](https://go.microsoft.com/fwlink/?linkid=2068169&0x80004005) -- system level).

### Microsoft Windows version

22H2 Build 22621.1194

### Other Software

Edge Version 109.0.1518.78 (Official build) (64-bit)

**Comment by ElitePheonix2009** [comment]
Duplicate of #239

**Comment by rcmaehl** [comment]
> Duplicate of #239
Yep
