### ISSUE TITLE
[Feature Request] Add str.replaceFirst() to strings coming from start menu searches

### ISSUE THREAD

**Issue by sinistarZ** [rcmaehl/MSEdgeRedirect#245]
### Description of the new feature / enhancement

A great feature is searching from the start menu. Press win key to bring up start menu from anywhere, enter your prompt and press enter. 

I prevent the start menu from opening any files or settings by adding "s " (lower case "s" and a space) to my prompt. 

Example, press win key then enter: 
s doughnut recipes

Will call "See web results" within the start menu, and pass that text to the browser and insert it into the default search engine and search it. 

While searches still work and your browser and search engine of choice is brought up, it would be nice to do something like str.replaceFirst to strings coming from the start menu.

Example:
`return str.replaceFirst("s ", ""); // set from MSER settings`

### Scenario when this would be used?

During everyday use, press the win key to search from anywhere and bring up your browser and search of choice. From there scripts or browser extensions could be used if additional behavior, like multi-window merging is wanted.

**Comment by rcmaehl** [comment]
While prepending `web;` (e.g. web:doughnut recipes) to your query will do what you're looking for, I can add something like this for the 0.9.0.0 release.

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
