### ISSUE TITLE
Redirect to any (portable) browser

### ISSUE THREAD

**Issue by rino5555** [rcmaehl/MSEdgeRedirect#247]
### Description of the new feature / enhancement

I need a possibility to redirect not to default browser, but to any browser installed or not installed by simply choosing the brwser exe file.

### Scenario when this would be used?

The default browser is set by group policy and its ms edge, but i habe forefox installed an wnt to use this for alle browser requests.
I can't change default browser, because it is set by group policy.

**Comment by rcmaehl** [comment]
This is coming soon™.

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
