### ISSUE TITLE
Add feature to use Google with Edge while using Windows search

### ISSUE THREAD

**Issue by NukeThief** [rcmaehl/MSEdgeRedirect#248]
### Description of the new feature / enhancement

Normally, when trying to use MSER with Edge it gives an error, and this is not good for people who want to have MSEdge with Google on windows search, because other alternatives like Search Deflector got discontinued. So i suggest adding a feature to allow people to switch from Microsoft search services but keep using MSEdge.

### Scenario when this would be used?

When a person prefers Google but wants to use edge

**Comment by NukeThief** [comment]
:SteamHappy:

**Comment by NukeThief** [comment]
yippee

**Comment by Riot20058** [comment]
> ### Description of the new feature / enhancement
> Normally, when trying to use MSER with Edge it gives an error, and this is not good for people who want to have MSEdge with Google on windows search, because other alternatives like Search Deflector got discontinued. So i suggest adding a feature to allow people to switch from Microsoft search services but keep using MSEdge.
> 
> ### Scenario when this would be used?
> When a person prefers Google but wants to use edge
> 
> ### Supporting information
> _No response_

No edge is even whose they chrome because trick more data they chrome so plese use web broswer works and trick more they needs like brave or firefox.

**Comment by NukeThief** [comment]
Iwas trying to read that and i got a stroke

**Comment by Masamune3210** [comment]
You aren't the only one lmao
