### ISSUE TITLE
Edge desktop and start menu links are invalid after uninstalling MSER 0.7.3.0

### ISSUE THREAD

**Issue by Suncoast-Cyclist** [rcmaehl/MSEdgeRedirect#249]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

1. Install MSER 0.7.3.0
2. Uninstall MSER
3. Select an Edge link from the start menu or desktop

### ✔️ Expected Behavior

Edge should open

### ❌ Actual Behavior

A Windows error dialog opens reporting that the item'msedge.exe' referenced by the shortcut has been changed or moved and offers to remove the shortcut. 

FWIW, the Edge shortcuts seem to continue to work correctly after uninstalling MSER 0.7.2.0

### Microsoft Windows version

Windows 10 Pro 22H2 19045.2604

**Comment by Sopor** [comment]
I'm a new user to MSEdgeRedirect and after uninstalling 0.7.3.0 i also get a default Windows icon on my desktop telling me it can't find the exe file.

If i install MSEdgeRedirect again it seems that MSEdgeRedirect is not working and when i use search nothing happens. 😥

It seems that MSEdgeRedirect need to repair what it has broken.

I tried to reboot, but it didn't fixed the issue.

**Comment by Sopor** [comment]
After copying the following files:
`delegatedWebFeatures.sccd`, `msedge.exe`, `msedge_proxy.exe` and `pwahelper.exe`
from
`C:\Program Files (x86)\Microsoft\Edge\Application\111.0.1661.41\`
to
`C:\Program Files (x86)\Microsoft\Edge\Application\`
it is working again.

**Comment by rcmaehl** [comment]
This will be fixed in the next release 👍
