### ISSUE TITLE
Add brave serach as a options like Google 

### ISSUE THREAD

**Issue by Riot20058** [rcmaehl/MSEdgeRedirect#250]
### Description of the new feature / enhancement

When go options set search engine thier is no brave search which not good because use by brave different. And should settings chaged most search engines are thier.

### Scenario when this would be used?

If useing brave as your web browser do not use settings already thier.

### Supporting information

Thier million of people use Brave most do not chaged search engines to Google and guys should settings make brave what redrict to it.

**Comment by Riot20058** [comment]
Here screenshots mean yes for 10 months ago but click newest update still not thier. @
![Screenshot_20230319-011139](https://user-images.githubusercontent.com/128275823/226155088-9c874905-c988-48af-9e2c-d7fdef1fc836.jpg)

**Comment by rcmaehl** [comment]
Should be in the next release 👍

**Comment by Riot20058** [comment]
> Should be in the next release 👍

Yeah msredrict for brave thier do use Google saying brave option for start. Thier how update ms redrict  Do you auto update or is it manual.

**Comment by rcmaehl** [comment]
> > Should be in the next release 👍
> 
> Yeah msredrict for brave thier do use Google saying brave option for start. Thier how update ms redrict Do you auto update or is it manual.

The software checks for updates and will prompt you to update when a new version is out

**Comment by Riot20058** [comment]
> > > Should be in the next release 👍
> > 
> > 
> > Yeah msredrict for brave thier do use Google saying brave option for start. Thier how update ms redrict Do you auto update or is it manual.
> 
> The software checks for updates and will prompt you to update when a new version is out

Thier do think chaged different search might useing brave because much more  privacy focused and use own batabase found thier search data only Google can not be founded.

**Comment by Riot20058** [comment]
@rcmaehl 
also uri add make brave work just called brave and test works good. but not custom needed one batter sarech engine
https://search.brave.com/search?q=%s
https://search.brave.com/?ia=images&iax=images&q=

**Comment by Riot20058** [comment]
> > > Should be in the next release 👍
> > 
> > 
> > Yeah msredrict for brave thier do use Google saying brave option for start. Thier how update ms redrict Do you auto update or is it manual.
> 
> The software checks for updates and will prompt you to update when a new version is out

here draft pr for this brave search and has URI added.
https://github.com/rcmaehl/MSEdgeRedirect/pull/255

**Comment by Riot20058** [comment]
> > > Should be in the next release 👍
> > 
> > 
> > Yeah msredrict for brave thier do use Google saying brave option for start. Thier how update ms redrict Do you auto update or is it manual.
> 
> The software checks for updates and will prompt you to update when a new version is out

did test and say working now
![Screenshot (6)](https://user-images.githubusercontent.com/128275823/227074996-8ca8dad7-719b-455b-b31b-c04bfcbad50e.png)
