### ISSUE TITLE
Running MSEdgeRedirect.exe after installing from chocolatey breaks everything

### ISSUE THREAD

**Issue by callumjohnspiller** [rcmaehl/MSEdgeRedirect#253]
### Preflight Checklist

- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Unsure

### Steps to reproduce

- Windows 10
- Install Through Chocolatey
- Runs the MSEdgeRedirect.exe to try and add features such as searching in Google that were not included with the chocolatey install
- Finishes this .exe then tries to search with the bar and nothing happens
- Uninstall MSEdgeRedirect using script in README
- MS Edge now no longer opens

### ✔️ Expected Behavior

For the changes made in the MSEdgeRedirect.exe program to take effect

### ❌ Actual Behavior

The search bar no longer worked and The existing MSEdge installation was corrupted

### Microsoft Windows version

"22H2 (OS Build 19045.2728)"

**Comment by rcmaehl** [comment]
Run `Get-AppXPackage -AllUsers -Name Microsoft.MicrosoftEdge | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}` to fix Edge. I'll look into the Chocolately build here in a bit.

**Comment by callumjohnspiller** [comment]
Hi there, unfortunatey this didn't work to fix edge and I had to remove it and re-install to get it working again.
