### ISSUE TITLE
Add brave news as someting replace MSN news

### ISSUE THREAD

**Issue by Riot20058** [rcmaehl/MSEdgeRedirect#254]
### Description of the new feature / enhancement

Think going add brave search also add brave news to site redrict because lead diffent site they google.

### Scenario when this would be used?

If someone trying use brave as thier main search enegine and also news come for brave.

### Supporting information

Helpful because msn news only duckduck go and google. add something like brave really good batter they evil google.

**Comment by Riot20058** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/128275823/227012282-a6a90970-f63d-41eb-b1e8-beb16124dba0.png)
see not may choice replace msn news think brave news whould be good.

**Comment by rcmaehl** [comment]
I am not seeing a "I'm Feeling Lucky" style search result for Brave Search which is required for news articles as the original source is not included in the URL, only the title. Do you know what the format is for that for Brave?

**Comment by Riot20058** [comment]
> I am not seeing a "I'm Feeling Lucky" style search result for Brave Search which is required for news articles as the original source is not included in the URL, only the title. Do you know what the format is for that for Brave?

Maybe best keep Google news. After testing brave news some news and changed site used. Also did testing yesh Brave search easy to add next ver. Think dev ver test for Brave search support added without needed custom uri.

**Comment by Riot20058** [comment]
@rcmaehl think help because have no clue added brave search to MSEdgeRedrict so help draft pr with added right.
