### ISSUE TITLE
Widgets won't open in browser after update to Release 0.7.3.0

### ISSUE THREAD

**Issue by hjbridger** [rcmaehl/MSEdgeRedirect#259]
After updating to current release, widgets in Windows 11 will not open at all. Used to redirect to Chrome, but they won't even open in any browser now.

I'm running:
Edition	Windows 11 Home
Version	22H2
Installed on	‎12-‎May-‎22
OS build	22624.1470
Experience	Windows Feature Experience Pack 1000.22640.1000.0

![Screenshot 2023-03-25 095750](https://user-images.githubusercontent.com/128918001/227731153-bf22fdb4-8e47-4975-9898-210f9c1e4e2a.png)

**Comment by rcmaehl** [comment]
If possible, can you try the dev build and let me know if it persists?

**Comment by hjbridger** [comment]
I'm sorry, but I don't know where to find dev build.

**Comment by rcmaehl** [comment]
> I'm sorry, but I don't know where to find dev build.

The dev build is located at: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by hjbridger** [comment]
Thanks, I was able to install it.  Had to turn off Safe Browsing in Chrome and Windows Defender blocked the install, but I was able to get it installed.  I clicked on one of the news widgets and it doesn't take me directly to the page, it shows me redirect link instead.  See screenshot.
![image](https://user-images.githubusercontent.com/128918001/227947643-e995c44c-7269-4c71-8de7-07c1bf70d652.png)

**Comment by rcmaehl** [comment]
Yeah, I'm looking at another way of distributing dev builds here soon.

**Comment by rcmaehl** [comment]
If you could. Please upload your log files from `%localappdata%\MSEdgeRedirect\logs`

**Comment by hjbridger** [comment]
[AppGeneral.log](https://github.com/rcmaehl/MSEdgeRedirect/files/11079430/AppGeneral.log)
[AppFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/11079431/AppFailures.log)
[URIFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/11079432/URIFailures.log)
[PEBIAT.log](https://github.com/rcmaehl/MSEdgeRedirect/files/11079433/PEBIAT.log)
[AppSecurity.log](https://github.com/rcmaehl/MSEdgeRedirect/files/11079434/AppSecurity.log)

**Comment by hjbridger** [comment]
The redirect link I sent, isn't even the link it was supposed to go to.
When clicking on a widget, some go directly to the article, then some
redirect to random sites such as Websters, Wiki or nowhere.
