### ISSUE TITLE
Investigate ChatGPT Button on Win11 22621.1483+

### ISSUE THREAD

**Issue by mcl21014** [rcmaehl/MSEdgeRedirect#260]
I noticed this when I tweaked my privacy settings via W10Privacy and Winaero Tweaker to re-enable cloud search, Cortana, web search etc. (I would not have noticed if it I didn't re-enable it to see the new search) and immediately noticed that upon clicking the new Bing ChatGPT button, with the latest MSEdgeRedirect running in the background, the link once again opens in MS Edge even though the default browser is not Edge and the program is running. Not sure if they snuck in more hard-coded Edge links in the update with updated search. New build is Windows 11 22621.1483 in the Release Preview.  That means this new "feature" of hardcoded Edge links will shortly be in the stable Windows 11.

**Comment by rcmaehl** [comment]
I'll look into this

**Comment by rcmaehl** [comment]
This is fixed in 0.8.0.0
