### ISSUE TITLE
Winget installs are broken

### ISSUE THREAD

**Issue by aloner-pro** [rcmaehl/MSEdgeRedirect#262]
I searched *tokyo* from windows search with `Win+S` but it went to edge whereas my default is Brave. I also tried the method given by `Win+R` , it too lead to Edge.

Using Windows 10.

**Comment by rcmaehl** [comment]
Can you verify you did not have both installed at the same time?

**Comment by aloner-pro** [comment]
At first I only had MsEdgeRedirect only on my system. Downloaded it through `winglet`. After it didn't work I installed NoMoreEdge by the installer.

**Comment by rcmaehl** [comment]
> At first I only had MsEdgeRedirect only on my system. Downloaded it through `winglet`. After it didn't work I installed NoMoreEdge by the installer.

Do you mean winget? If so, can you run winget as administrator and retry the install. I have the installer set to inherit Winget's permissions and as such it would only install in service mode from package managers.

**Comment by aloner-pro** [comment]
Well I uninstalled both `MSEdgeRedirect` and `NoMoreEdge` then reinstalled `MSEdgeRedirect` from `winget` with admin priviledges and now it is working.

**Comment by rcmaehl** [comment]
> Well I uninstalled both `MSEdgeRedirect` and `NoMoreEdge` then reinstalled `MSEdgeRedirect` from `winget` with admin priviledges and now it is working.

I'll get non-admin winget installs fixed for 0.8.0.0

**Comment by rcmaehl** [comment]
@androidacy-user @aloner-pro 
Are you all on Win11 of Win10. Wasn't able to reproduce.

**Comment by rcmaehl** [comment]
> > @androidacy-user @aloner-pro
> > Are you all on Win11 or Win10. Wasn't able to reproduce.
> 
> 11

Alright, my Win11 laptop is charging, but I'll test on there shortly

**Comment by aloner-pro** [comment]
As told by me the admin install worked for me on my windows 10 laptop. I am using it currently.

**Comment by rcmaehl** [comment]
Pretty sure this is an issue with `$aConfig[$vMode]`. I have no idea what previous me was doing with this 😂

**Comment by rcmaehl** [comment]
Can you all check %localappdata%\MSEdgeRedirect\PEBIAT.log for any log entries?

**Comment by aloner-pro** [comment]
> Can you all check `%localappdata%\MSEdgeRedirect\PEBIAT.log` for any log entries?

It's empty.

**Comment by Remzi1993** [comment]
> Can you all check `%localappdata%\MSEdgeRedirect\PEBIAT.log` for any log entries?

I will also check. @rcmaehl I'm also on Windows 11, version 22H2 - build 22621.1848 (latest stable build)

**Comment by rcmaehl** [comment]
Hi all,

Has anyone tested this with 0.7.4.0?
