### ISSUE TITLE
Redirect to Chrome Fails

### ISSUE THREAD

**Issue by TW1954** [rcmaehl/MSEdgeRedirect#263]
Just got a new Acer Swift 3 14 running Windows 11 Build 2200-1696.  I get this error message when pasting "microsoft-edge:https://google.com" using the Windows + R keys.
![Screenshot 2023-03-31 164943](https://user-images.githubusercontent.com/48024639/229170292-f01f3448-96a3-4c53-90ef-e0eb41345233.png)

**Comment by rcmaehl** [comment]
> Just got a new Acer Swift 3 14 running Windows 11 Build 2200-1696. I get this error message when pasting "microsoft-edge:https://google.com" using the Windows + R keys. ![Screenshot 2023-03-31 164943](https://user-images.githubusercontent.com/48024639/229170292-f01f3448-96a3-4c53-90ef-e0eb41345233.png)

You still have Edge installed correct?

**Comment by TW1954** [comment]
Robert,

My bad, had forgotten that in previous attempts I had removed Edge.  Have
reinstalled Edge and your program is working as advertised.  Thanks for the
quick response, a coffee is on the way.

Trevor
