### ISSUE TITLE
Opening Edge as Default App for a File

### ISSUE THREAD

**Issue by AllanHigdon** [rcmaehl/MSEdgeRedirect#269]
**Describe the request**
If Edge is the Default App for .MHT files, nothing happens when selecting one of these files.
I assume that MSEdgeRedirect only works with URLs.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Build 19045

**Additional context**
Add any other context about the request here.

**Comment by gazzawazza** [comment]
i second @AllanHigdon request for a .MHT file / Edge usage excluder for MSER (if it's viable).

It's niche but it would be good to permit Edge to open MHT files, as firefox definitely doesn't work (my default browser) and Opera reportedly doesn't support them.

Chrome does seemingly open MHT files but they have to be saved.

My usage example is outlook 2021. I had an email that offered to open in a browser. This in fact didn't take me to an online version but tried to open a .MHT file (it seems to dynamically create one - created an MHT file in users/[myusername]/appdata/Local/Microsoft/Windows/INetCache/Content.Outlook/).

For whatever reason, if Chrome is the default app for .MHT, it does not render this dynamic MHT file correctly, when 'open in browser' is used.

If i save the same email as .MHT, then Chrome opens and renders file fine.

If Edge is default app, then MSER pushes to the default browser (firefox here) but firefox can't do anything with .mht (so basically nothing happens). 

tested with:

MSER 0.7.3
firefox 115.0.2
chrome 115
edge 114
win 10 22H2 19045



regards,

Gary

**Comment by rcmaehl** [comment]
Sounds doable

**Comment by gazzawazza** [comment]
> Sounds doable

that's super kind of you

Honestly, my use case (the email view in browser) is uncommon. I rarely do it and as said thought it normally just takes one to an online version.

However, when i was googled about MHT, it sounds like it gets usage from an archiving perspective.

I think it depends for you on how much effort's involved or maybe whether you feel a need to add the functionality for completeness sake, as MHT is so IE / Edge-centric

**Comment by AllanHigdon** [comment]
> However, when i was googling about MHT, it sounds like it gets usage from an archiving perspective.
> 
> I think it depends for you on how much effort's involved or maybe whether you feel a need to add the functionality for completeness sake, as MHT (and possibly MHTML) are so IE / Edge-centric

That's my point of view as well. I only use MHT as a way to save Web pages, like I've been doing ever since I used IE.

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
