### ISSUE TITLE
URLs Rewritten in Managed Browser Environment?

### ISSUE THREAD

**Issue by cgequi** [rcmaehl/MSEdgeRedirect#270]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Install MSEdgeRedirector.  Set default browser to Firefox or Chrome.  Use the Windows taskbar search box and enter a website name (i.e. amazon.com... don't even need the https://).  

### ✔️ Expected Behavior

The website should open in the default browser.  E.g., if I entered "amazon.com" in the Windows taskbar search and my default browser is Firefox, a new Firefox window should open at https://www.amazon.com.

### ❌ Actual Behavior

The default browser will open, but it will open with a URL as follows.

If the URL is not redirected, the browser will open a rewritten URL in the following format, assuming:
- {website-name} is the name entered in the Windows taskbar search box (possibly reformatted as a proper URL, i.e., amazon.com -> https://www.amazon.com)
- {email-address} is the email address I'm assuming Windows is picking up as associated with my Windows login to an employer-managed Windows device with managed browser installations 
- Other items in curly braces { } are as described by the text within them
(By "redirected" I mean that 

> https://{website-name}/&timestamp={unix-epoc-timestamp}&source=WindowsSearchBox&oid={43-character_oid-string}&upn={email-address}

With Firefox, if you try to go to a website that gets redirected, the browser prompts with the following before opening:  

> Confirm.  You are about to log into the site "{FQDN-from-email-address-in-URL}" with the username "{remainder-of-URL-except-FQDN-from-email-address}" but the website does not require authentication.  This may be an attempt to trick you.  Is "{FQDN-from-email-address-in-URL}" the site you want to visit?  [ Yes | No ]

If "Yes" is selected, it will open the FQDN from the email address in the URL, not the URL itself.

Note that my browsers are managed by my employer, so this might not be a problem with MSEdgeRedirector itself.

But I'd love to know how to get this to stop.  It has only started recently - and without an update to MSEdgeRedirector - so perhaps a GPO push or other management tooling has changed how Windows passes information from the taskbar search box to Edge and then on to MSEdgeRedirector...?

**_Note that if I uninstall MSEdgeRedir (and re-install Edge as the current bug requires me to do that), Edge will open {website-name} as expected._**

Feel free to close this if it's not a bug with MSEdgeRedirector.  But I'd love a pointer on where to look to figure out what's going on...

### Microsoft Windows version

22H2 OS Build 22621.1702

### Other Software

MSEdgeRedirector 0.7.3.0 in "Active" mode
Firefox 113.0.2 (64-bit)
Chrome 114.0.5735.110 (64-bit)

**Comment by cgequi** [comment]
Thank you for jumping right on this!

Strangely, AppGeneral.log doesn't have an entry since 5/26.  However, AppFailures.log, AppSecurity.log, and URIFailures.log all have a few... just just a few.  For the entries that are in AppGeneral.log from 5/26 and prior, they seem to all be of the format:

> yyyy/mm/dd hh:mm:ss - Redirected Edge Call:
> --single-argument : 
> launchContext1: Microsoft.Windows.Search_cw5n1h2txyewy
> url: {urlencoded-url}

I do not see a UPN listed in any of those logs.

Is there something I might have done to prevent the logs being written?  Is something written to AppGeneral.log on every redirect, or just under certain circumstances?  

Let me know how I can help.  TY!

**Comment by rcmaehl** [comment]
>they seem to all be of the format:
> 
> > yyyy/mm/dd hh:mm:ss - Redirected Edge Call:
> > --single-argument :
> > launchContext1: Microsoft.Windows.Search_cw5n1h2txyewy
> > url: {urlencoded-url}

> Is there something I might have done to prevent the logs being written?

From being written to ANY log: Generally not, but some edge case might have the code ending up someone I didn't expect

> Is something written to AppGeneral.log on every redirect, or just under certain circumstances?

Something should be written to any of the logs on every redirect.

Does the username firefox is displaying URL encoded at all?

**Comment by Remzi1993** [comment]
@rcmaehl I just updated redirect to the latest version and if I search something in the searchbar nothing happens.
![Screenshot 2023-06-14 231907](https://github.com/rcmaehl/MSEdgeRedirect/assets/980950/22ceed99-bd32-40e1-9bb7-932ee98a2f0b)

**Comment by cgequi** [comment]
Downloaded the latest version of MSER (0.7.4.0) and the original issue appears to be resolved.  I also do not have the issue that Remzi1993 has above.  (Actually, that does happen occasionally, but that's whether MSER is installed or not.  I think it's a problem with Explorer or Windows or Windows Search or whatever.  Usually a restart fixes Remzi's problem for me.)  I think you can close this one out.  Thank you @rcmaehl for getting this fixed!

**Comment by rcmaehl** [comment]
> Downloaded the latest version of MSER (0.7.4.0) and the original issue appears to be resolved. I also do not have the issue that Remzi1993 has above. (Actually, that does happen occasionally, but that's whether MSER is installed or not. I think it's a problem with Explorer or Windows or Windows Search or whatever. Usually a restart fixes Remzi's problem for me.) I think you can close this one out. Thank you @rcmaehl for getting this fixed!

Let me know if it reoccurs!

Some of the MSEdge calls were still using the legacy call parameters but not formatted as such. This should be fixed, although I'm sure some edge cases will still occur.
