### ISSUE TITLE
Flutter can't start and connect Edge

### ISSUE THREAD

**Issue by enesuzun2002** [rcmaehl/MSEdgeRedirect#271]
### Preflight Checklist

- [x] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Deployment (Chocolatey, Winget, Etc)

### Install Mode

Unsure

### Steps to reproduce

I am trying to run a flutter debug session with edge and it can't start it.

`Failed to launch browser after 3 tries. Command used to launch it: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --user-data-dir=C:\Users\ENESMU~1\AppData\Local\Temp\flutter_tools.f282b3f8\flutter_tools_chrome_device.b46fd5aa --remote-debugging-port=52847 --disable-background-timer-throttling --disable-extensions --disable-popup-blocking --bwsi --no-first-run --no-default-browser-check --disable-default-apps --disable-translate http://localhost:52816
Failed to launch browser. Make sure you are using an up-to-date Chrome or Edge. Otherwise, consider using -d web-server instead and filing an issue at https://github.com/flutter/flutter/issues.`

### ✔️ Expected Behavior

Edge should run without issue

### ❌ Actual Behavior

Edge doesn't start

### Microsoft Windows version

22H2 build 22621.1848

### Other Software

Flutter 3.10.5
VS Codium and Flutter extension

**Comment by rcmaehl** [comment]
Will fix 👍

**Comment by rcmaehl** [comment]
Should be fixed in test builds btw 👍
