### ISSUE TITLE
0.7.4.0 not working

### ISSUE THREAD

**Issue by halt76** [rcmaehl/MSEdgeRedirect#273]
### Preflight Checklist

- [ ] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Service Mode

### Steps to reproduce

Press F1 in Explorer
or
microsoft-edge:https://google.com/

Everything is working fine in development version 0.7.3.0

### ✔️ Expected Behavior

open in firefox

### ❌ Actual Behavior

open in Edge

### Microsoft Windows version

Win10 22H2 19045.3086

**Comment by rcmaehl** [comment]
Which dev links are you using? 0.7.4.0 IS the latest dev build?

**Comment by rcmaehl** [comment]
I'm not in front of my home computer but can you test if start menu searches still work?

I'm guessing that works (and should work pretty damn well now), but not other redirects.

If so, I just need to readd some older code.

**Comment by halt76** [comment]
I'm not sure about the start menu search, but web search results from the taskbar seem to redirect successfully,
The microsoft-edge protocol redirection is also successful.

The explorer help seems to be missing the query.

**Comment by rcmaehl** [comment]
Yep. Working on fixing that.

**Comment by halt76** [comment]
Confirmed fixed
