### ISSUE TITLE
Broke Everything

### ISSUE THREAD

**Issue by pmruzicka** [rcmaehl/MSEdgeRedirect#275]
### Preflight Checklist

- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Installed Active Mode and it seemed fine. Went to change setting to Service Mode and nothing worked. Tried to change back to active mode and the start with windows was grayed out. AT this point, nothing works. I tried to uninstall it also. None of the widgets open at all. Clicking on them just closes the widget window. I am absolutely clueless on hos to return my system to normal.

### ✔️ Expected Behavior

I was at least expecting the uninstall to return the system to the way it was originally (opening widgets in Edge).

### ❌ Actual Behavior

Already explained: nothing

### Microsoft Windows version

22H2 Build 22621.1848

**Comment by rcmaehl** [comment]
Please open apps and features, search microsoft edge, and choose modify. This will run a repair on Edge. The uninstall bug is fixed in 0.7.4.0

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/5d805926-23a6-4efc-9a72-4a97b7b3f2d7)

**Comment by pmruzicka** [comment]
I ran Edge repair and it did nothing for the problem. Ran SFC - no effect, nothing wrong. Ran DISM - no effect. Was thinking of running System Restore but . . . I ended up copying the msedge.exe file to where the system was looking for it. Now all seems to be fine. The only place I could find MSEdgeRedirect was in C:\Program Files. The folder was empty.
