### ISSUE TITLE
After installing 0.7.4.0, links from Outlook for Windows always open in a new browser window.

### ISSUE THREAD

**Issue by darren12345** [rcmaehl/MSEdgeRedirect#278]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Upgrade from 0.7.3.0 to 0.7.4.0
Click a URL in an email in Outlook (Windows desktop app - "Microsoft 365 Apps for Business")

### ✔️ Expected Behavior

Link opens in a new tab in the last active default browser window (Firefox in my case)

### ❌ Actual Behavior

Link opens in a new window of the default browser.
Downgrading to 0.7.3.0 fixes this.

### Microsoft Windows version

22H2 (OS Build 22621.1848)

### Other Software

Firefox 114.0.2

**Comment by Couchy** [comment]
Same here, though mine doesn't even open the link, just a new Firefox window with an empty tab.

**Comment by darren12345** [comment]
Off topic: I have been living in blissful ignorance that MS at some point changed Outlook to force all URLs to open in Edge, and I only found out while investigating this issue, and was actually assuming for a bit that my default browser setting wasn’t working. Dick. Move.

**Comment by rcmaehl** [comment]
> Off topic: I have been living in blissful ignorance that MS at some point changed Outlook to force all URLs to open in Edge, and I only found out while investigating this issue, and was actually assuming for a bit that my default browser setting wasn’t working. Dick. Move.

Applies to Teams as well, and likely all Microsoft developed apps soon. Honestly, MS needs another AntiTrust suit IMO, they seem to be forgetting the lessons they learned the hard way.

**Comment by mjmatthiesen** [comment]
It's a "feature": https://community.spiceworks.com/topic/2488133-new-feature-outlook-forces-links-to-open-in-edge-solved
You have to disable it in your outlook settings.

**Comment by rcmaehl** [comment]
> It's a "feature": https://community.spiceworks.com/topic/2488133-new-feature-outlook-forces-links-to-open-in-edge-solved You have to disable it in your outlook settings.

They said downgrading to 0.7.3.0 fixes the issue. I haven't had a chance to install the office apps but I'm thinking it's a change on my end.  @darren12345 can you confirm again real quick?

**Comment by darren12345** [comment]
OK, if I change the setting in Outlook to actually respect my choices, if I upgrade to 0.7.4.0 it initially seems like this issue is fixed and links from Outlook open in the existing FF window, not a new one.

**Comment by rcmaehl** [comment]
So

Trying to troubleshoot this.

Outlook won't let me set browser to "Microsoft Edge" in advanced. 😂

**Comment by Couchy** [comment]
> So
> 
> Trying to troubleshoot this.
> 
> Outlook won't let me set browser to "Microsoft Edge" in advanced. 😂

Is there a log I can send you?

**Comment by rcmaehl** [comment]
> Is there a log I can send you? I get this in AppGeneral.log when clicking a link in Outlook:
> 
> 2023/08/10 15:45:47 - Caught 'Microsoft-Edge' Call: --single-argument : url: %2F%2F%2F?URL

As in

`Caught 'Microsoft-Edge' Call: --single-argument : url: %2F%2F%2F?https://google.com/` or literally `Caught 'Microsoft-Edge' Call: --single-argument : url: %2F%2F%2F?URL` ?

Yes, AppGeneral.log if a browser is opening. URIFailures.log if no browser is opening

**Comment by Couchy** [comment]
Yes, I pasted it exactly as-is. As mentioned, Firefox does open, just to a blank tab.

**Comment by rcmaehl** [comment]
> Literally "URL" - I pasted it exactly as-is. And as mentioned, Firefox does open, just to a blank tab.

Yeah. You can email the logs to rcmaehl@gmail.com if you want to keep the confidential or DM me them on the discord server from the readme

**Comment by Couchy** [comment]
What you see is what I got. Probably need to log what the original command was before any parsing is done.

**Comment by rcmaehl** [comment]
> What you see is what I got. Probably need to log what the original command was before any parsing is done.

Yep. I've found something that seems to have fixed my issue back from July from r/Sysadmin

https://pastebin.com/AbaPjJHa

Will be taking another wack at it here in a bit

**Comment by rcmaehl** [comment]
Should be fixed in test builds 👍
