### ISSUE TITLE
"Default" PDF handler option unable to handle PDFs with spaces

### ISSUE THREAD

**Issue by MG-LSJ** [rcmaehl/MSEdgeRedirect#284]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Open a pdf which has spaces in name. When MS edge is set as default pdf reader. Only happens in the latest update.

### ✔️ Expected Behavior

Pdf opens normally.

### ❌ Actual Behavior

File name gets split and opened as individual words.
<img width="131" alt="image" src="https://github.com/rcmaehl/MSEdgeRedirect/assets/73988826/e2ebd3b5-c326-4ecc-bcdf-50e1c6792119">
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/73988826/d5d88e9d-f81a-4ec0-b5ac-ac3e65794461)

### Microsoft Windows version

22H2 22631.1972

**Comment by rcmaehl** [comment]
Whoops. Looks like this is an issue with having PDFs set to "Default". I've made a fix for this but you can work around it for now by setting it to Custom and selecting the PDF handler manually.
