### ISSUE TITLE
Not working on Outlook

### ISSUE THREAD

**Issue by sellingchico** [rcmaehl/MSEdgeRedirect#286]
Verified that it's working from the Run function, and searching in the taskbar. However outlook links just open a new blank chrome window. 
SS attached of settings and result
![Screenshot_290](https://github.com/rcmaehl/MSEdgeRedirect/assets/125104703/6cce94c1-6a77-4ad3-b736-fd612a77a6a7)

![Screenshot_289](https://github.com/rcmaehl/MSEdgeRedirect/assets/125104703/fe85ca12-989f-4e56-9cd9-b36c85d8a366)

**Comment by rcmaehl** [comment]
Duplicate of #278. Literally working on this currently
