### ISSUE TITLE
Implement Install Logging

### ISSUE THREAD

**Issue by Alexyoe** [rcmaehl/MSEdgeRedirect#288]
### Preflight Checklist

- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Run microsoft-edge:https://google.com

### ✔️ Expected Behavior

Open google.com in chrome

### ❌ Actual Behavior

Opens google.com in edge

### Microsoft Windows version

22H2 Build 19045

**Comment by rcmaehl** [comment]
Can you check if C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe exists?

**Comment by Alexyoe** [comment]
Yep it is there.

**Comment by rcmaehl** [comment]
1. Open appwiz.cpl
2. Select MSEdgeRedirect
3. Select "Change"
4. Walk through the installer again
5. Retry `microsoft-edge:https://google.com/`

If the issue persists, please send the logs from `%localappdata%\MSEdgeRedirect\Logs`

**Comment by rcmaehl** [comment]
> Just tried this but I'm still getting the same result. I checked the logs but they are all blank.

Odd. I'll make some changes and give ya a dev build to try here in a couple hours. Currently slammed at my main job.

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
