### ISSUE TITLE
Service Mode idle usage

### ISSUE THREAD

**Issue by paradonym** [rcmaehl/MSEdgeRedirect#29]
**Describe the request**
A clear and concise description of what the request is.

I often see MSEdgeRedirect within the top 5 CPU load programs when I haven't opened Edge or clicked any Windows internal links.
I want to ask if there's a reason for this, because the program has to actively check which internet requests are made or so.

**Screenshots**
If applicable, add screenshots to help explain your request.
[PICTURE](https://photos.google.com/lr/album/AI1jw-bwD7fVuuwfxOYICm5uiz7YLEv_SrKpMJPUZQ2bZo8RpDaVh8hULW2X8peCB0qziXqjtspq/photo/AI1jw-YYWK6FVCQXB1TsGeucwgXRStRfUBydDaU3shGk_2En7SRP9LXHmOKnP2De7Oy6SBWOm6pTyttK1VEPGnvqp-wdLmSM5g)

**Desktop (please complete the following information):**
 - OS / Build: Windows 11 Version 21H2 Build 22000.348 [on this hardware](https://www.sysprofile.de/id105306) (Hardware in brief: R7 5800X, RX580 32 GB RAM)
 - MSEdgeRedirect version: 0.4.10

**Additional context**
Add any other context about the request here.

It's not a bug, I just want to understand why it's CPU-load on idle.
It's not staying in the top 5 CPU load programs, but switches quickly to it like every second for a split-second.

**Comment by rcmaehl** [comment]
Looks like I don't have access to your screenshot.

![image](https://user-images.githubusercontent.com/716581/145688303-553e2523-1f6b-42f5-94ba-f87c8d3d53e6.png)

Regardless, sounds like you're using Service Mode. Due to service mode needing to monitor new processes it's more resource intensive than active mode but should top out at 2% at max. I'll look into it however.

**Comment by paradonym** [comment]
How do I switch between modes?
I literally just installed it and let it run, now that Microsoft fights against https://github.com/da2x/EdgeDeflector…

**Comment by rcmaehl** [comment]
> How do I switch between modes? I literally just installed it and let it run, now that Microsoft fights against https://github.com/da2x/EdgeDeflector …

Open programs & features, then "uninstall"
Then run the installer as admin and select "active mode"

I'll consider adding a way to change modes in a future version.

**Comment by rcmaehl** [comment]
> I'll consider adding a way to change modes in a future version.

Added in 6ba62adbf9b50297d95fec48f3c551803103503c

**Comment by rcmaehl** [comment]
Performance was improved in 36c2eed9e22edb47c61f981ff7985f9a803a8a6c. Investigating options to improve performance more.

**Comment by rcmaehl** [comment]
Investigated Adlibregister vs Timer. Timer cpu performance was slightly less and reliability is the same excluding when the tray icon is being interacted with.

![image](https://user-images.githubusercontent.com/716581/146307627-5cc725d7-50af-42b0-878e-d0022dcfb6ee.png)

**Comment by rcmaehl** [comment]
Closing to have #36 take over
