### ISSUE TITLE
Improve File Handling

### ISSUE THREAD

**Issue by MG-LSJ** [rcmaehl/MSEdgeRedirect#291]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Open an svg file when edge is set as defualt

### ✔️ Expected Behavior

SVG file to open

### ❌ Actual Behavior

nothing happens

### Microsoft Windows version

22H2

**Comment by rcmaehl** [comment]
Can confirm. I'll see if I can improve overall file handling here in a bit.

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
