### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Makezu90** [rcmaehl/MSEdgeRedirect#292]
### Preflight Checklist

- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Unsure

### Steps to reproduce

installed normally how it should, when i go to widgets and press some news example, nothing happens. Browser what i want use default is put default.. so yeah nothing happens.

### ✔️ Expected Behavior

open news.. weather on default browser.

### ❌ Actual Behavior

nothing.

### Microsoft Windows version

22H2 22621.2070

**Comment by rcmaehl** [comment]
Please open cmd and run: `reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe" /s`

Please paste the output here

**Comment by Makezu90** [comment]
> ### Preflight Checklist
> * [ ]  Running microsoft-edge:https://google.com redirects successfully
> * [ ]  Microsoft Edge is selected in any "How do you want to open this?" box
> 
> ### Install Type
> New Install
> 
> ### Install Mode
> Unsure
> 
> ### Steps to reproduce
> installed normally how it should, when i go to widgets and press some news example, nothing happens. Browser what i want use default is put default.. so yeah nothing happens.
> 
> ### ✔️ Expected Behavior
> open news.. weather on default browser.
> 
> ### ❌ Actual Behavior
> nothing.
> 
> ### Microsoft Windows version
> 22H2 22621.2070
> 
> ### Other Software
> _No response_

oh, i forgot i uninstalled edge and its need to be installed.
