### ISSUE TITLE
Latest version - Clicking links in Outlook 365 opens up homepage but not the destination of the link clicked.

### ISSUE THREAD

**Issue by Sensivision** [rcmaehl/MSEdgeRedirect#297]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Got popup when I clicked on links to update MSRedirect.
Updated to latest version via Github executable file.
Active mode selected / Does same in service mode.
Stable build selected and default settings used.
Click update option.
Open outlook 365 and click any email link
Opens up new google chrome window to homepage only.

### ✔️ Expected Behavior

Click outlook 365 link and it opens the link in chrome to the desired destination

### ❌ Actual Behavior

Opens a new window in Chrome to my homepage and only my homepage.

### Microsoft Windows version

20H2 22621.1992

**Comment by Sensivision** [comment]
Fixed the issue, you need to run @Aveyo's Edge Removal, after which the links will start properly redirecting.

**Comment by rcmaehl** [comment]
Should be fixed in test builds 👍
