### ISSUE TITLE
Start11 + NTLite causes search-ms URI failure

### ISSUE THREAD

**Issue by MoonSzol** [rcmaehl/MSEdgeRedirect#299]
microsoft-edge:https://google.com in win + R works but when i try and do a search in start menu it shows error, "we cant open this 'search-ms' link, Your device needs a new app to open this link"

using Librewolf browser and I have uninstalled edge browser

**Comment by rcmaehl** [comment]
> I have uninstalled edge browser

Did you uninstall it using AveYo's script or another method? AveYo's script keeps a needed component to trick Microsoft's URI handler into allowing MSEdgeRedirect to work

**Comment by MoonSzol** [comment]
I don't think so, I used CTT tool not sure where he pulled the edge remover. 
Is there a way to fix?

**Comment by rcmaehl** [comment]
> I don't think so, I used CTT tool not sure where he forked the edge remover. Is there a way to fix?
> 
> Edit: tried to reinstall to do it the right way... doesn't work. Gonna have to do a fresh install

ChrisTitus should be using AveYo last I checked. Can you let me know which options you selected in his tool so I can attempt to reproduce?

**Comment by MoonSzol** [comment]
Just ran a test and found out, it has nothing to do with CTT.

It has to do with how my NTLite-iso settings are interacting with start11(a custom start menu app)

**Comment by rcmaehl** [comment]
Is it okay if I close out this issue then?

If you can provide additional details, I can look into it eventually but it won't be high priority

**Comment by MoonSzol** [comment]
Yep, it has absolutely nothing to do with MSERedirect. 

The cause of the problem is that start11 doesn't use "see web result" when pressing 'enter' they instead open up a special command to file explorer
