### ISSUE TITLE
Add Support for Edge Beta, Dev, and Canary

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#3]
- [x] Edge Beta Support
    - [x] Executable Name: msedge.exe
    - [x] Filepath: C:\Program Files (x86)\Microsoft\Edge Beta\Application\msedge.exe
- [x] Edge Dev Support
    - [x] Executable Name: msedge.exe
    - [x] Filepath: C:\Program Files (x86)\Microsoft\Edge Dev\Application\msedge.exe
 - [x] Edge Canary Support
    - [x] Executable Name: msedge.exe
    - [x] Filepath: %localappdata%\Microsoft\Edge SXS\Application\msedge.exe

**Comment by rcmaehl** [comment]
@gnpaone All builds of edge should now be supported. Latest automatically compiled build is available here:

https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1451619392

It works on my machine but if you can test it out, it'd be appreciated :)

**Comment by gnpaone** [comment]
> @gnpaone All builds of edge should now be supported. Latest automatically compiled build is available here:
> 
> https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1451619392
> 
> It works on my machine but if you can test it out, it'd be appreciated :)

Yes, it's working perfectly with dev, but one more issue I found, if I already opened edge (any version - stable, dev etc) and if I search something in windows then search results opens in both edge as well as chrome, this doesn't happen (only opens in chrome) if edge is closed

**Comment by rcmaehl** [comment]
> > @gnpaone All builds of edge should now be supported. Latest automatically compiled build is available here:
> > https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1451619392
> > It works on my machine but if you can test it out, it'd be appreciated :)
> 
> Yes, it's working perfectly with dev, but one more issue I found, if I already opened edge manually (any version - stable, dev etc) and if I search something in windows then search results opens in both edge as well as chrome, this doesn't happen (only opens in chrome) if edge is closed

I'll create a new issue for this as it'll help keep things tidy.
