### ISSUE TITLE
Version display in context menu

### ISSUE THREAD

**Issue by paradonym** [rcmaehl/MSEdgeRedirect#30]
**Describe the request**
A clear and concise description of what the request is.

- A version number display in the right click menu of the tray icon.

**Desktop (please complete the following information):**
See issue  #29 

**Additional context**
Add any other context about the request here.

It would be nice to see the current version number in the right click menu of MSEdgeRedirect.

**Comment by rcmaehl** [comment]
Added. Will be show in 0.5.0.0 onwards and in current [dev builds](https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/mser/main/mser.zip).
