### ISSUE TITLE
Built in Bing Chat button doesn't redirect 

### ISSUE THREAD

**Issue by irie612** [rcmaehl/MSEdgeRedirect#303]
The built in bing chat button in Windows 11 Version 10.0.22621 Build 22621 doesn't redirect. 
It's URL is `microsoft-edge:///?url=http://bing.com/chat?form=WSBCTB`.
Checking with windows run, `microsoft-edge:https://bing.com/` works, but `microsoft-edge:https://bing.com/chat` doesn't.

**Comment by rcmaehl** [comment]
> The built in bing chat button in Windows 11 Version 10.0.22621 Build 22621 doesn't redirect. It's URL is `microsoft-edge:///?url=http://bing.com/chat?form=WSBCTB`. Checking with windows run, `microsoft-edge:https://bing.com/` works, but `microsoft-edge:https://bing.com/chat` doesn't.

This is likely fixed in the dev builds. The wrong `://` was being grabbed and messing up the URL. I'll double check regardless to be safe.
