### ISSUE TITLE
You must use a different default browser to use

### ISSUE THREAD

**Issue by gamesturbator** [rcmaehl/MSEdgeRedirect#305]
### Preflight Checklist

- [X] Microsoft Edge is selected in any "How do you want to open this?" box
- [X] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

New Install

### Install Mode

Unsure

### ℹ Behavior

It won't even begin an install. Back to Edgeblocker I guess.

### Microsoft Windows version

Windows 11 22H2 22621

**Comment by rcmaehl** [comment]
Are you attempting to run MSEdgeRedirect portably? If not, can you make sure Firefox/Chrome/Brave/Et al is set as the default for both HTTP and HTTPs via

Windows Settings -> Apps -> Default Apps -> Choose Default Apps by Protocol

**Comment by gamesturbator** [comment]
Thanks for the suggestion but it is infuriating to set any browser other
than Edge as my default. I spent the whole day trying to do it. and it was
useless. Windows 11 has made too many changes in the last month. I went
back to using Windows 11-Lite by a reliable modder. Hope it will install
this time. I'll let you know.

**Comment by rcmaehl** [comment]
Using MSEdgeRedirect with Edge as the default browser will be added in the next release and will, at the very least, allow the install regardless.

**Comment by gamesturbator** [comment]
My understanding of the software it this. Windows keeps wanting to use Edge
to run things instead of our favorite browser. MSEdgeRedirect is a
workaround. Someone mentioned it could be a PowerShell policy preventing it
from running. Could that be the issue? Thanks.
