### ISSUE TITLE
Auto permissions in installer

### ISSUE THREAD

**Issue by gnpaone** [rcmaehl/MSEdgeRedirect#31]
The installer greys out active mode installation when not ran in administrator mode. I have a suggestion, instead of greying out active mode u can just ask for administrator permissions immediately when active mode chosen and clicked next (this is the way other installers work, for example some installers ask for "install for all users" and "install for me only" options where if u choose all users option and click next it automatically ask for administrator permissions when the installer is started in non-administrator mode instead of greying out the all users option in this mode).

**Non-administrator mode:**
![Screenshot (4980)](https://user-images.githubusercontent.com/78990165/145740749-fa623d41-efd7-4ff7-bce6-0e931ada5166.png)

**Administrator mode:**
![Screenshot (4979)](https://user-images.githubusercontent.com/78990165/145740785-ffba554d-30e1-4c31-8c0d-f1d31ee8d722.png)

**Comment by rcmaehl** [comment]
Added. If you have any additional feedback let me know.

**Comment by gnpaone** [comment]
> Added. If you have any additional feedback let me know.

Yes, it's better now, thanks
