### ISSUE TITLE
Open Links from inside user-installed Edge Web Apps in default browser

### ISSUE THREAD

**Issue by Skyyblaze** [rcmaehl/MSEdgeRedirect#310]
### Description of the new feature / enhancement

In case a user uses a default browser that isn't Edge but uses user-installed web apps installed by Edge, links inside these apps should be opened in the default browser and not a new Edge window.

### Scenario when this would be used?

To give a simple example:

Default Browser: Firefox
App: Google Chat installed as a Edge Web App

Any link clicked inside Google Chat should be opened inside Firefox and not create a new Edge window.

**Comment by rcmaehl** [comment]
Unfortunately I don't think this is possible last I checked but I'll investigate again

**Comment by rcmaehl** [comment]
Merging with #320
