### ISSUE TITLE
Installed via winget, did not seem to work - Start menu search and the run command in the Readme

### ISSUE THREAD

**Issue by SandeeepKiran** [rcmaehl/MSEdgeRedirect#312]
### Preflight Checklist

- [ ] Microsoft Edge is selected in any "How do you want to open this?" box
- [ ] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

New Install

### Install Mode

Unsure

### ℹ Behavior

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/36911157/cab55506-de4e-4075-8293-44db32725697)

All logs appear empty

### Microsoft Windows version

Version 20H2 (OS Build 22621.2283

### Other Software

None

**Comment by rcmaehl** [comment]
Have you already tried rebooting?

**Comment by SandeeepKiran** [comment]
Yep, tried rebooting. Still not working.
Anything I can do to provide some logs?

**Comment by rcmaehl** [comment]
> Yep, tried rebooting. Still not working. Anything I can do to provide some logs?

Nah, Winget should have errored out if the install failed. Check `%localappdata%\MSEdgeRedirect` or `C:\Program FIles\MSEdgeRedirect\` for MSEdgeRedirect.exe

If you have neither, let me know

**Comment by SandeeepKiran** [comment]
Updated to the latest version.
Issue resolved.
Unsure why it did not work before.
