### ISSUE TITLE
Recursion Prevention sometimes fails

### ISSUE THREAD

**Issue by pylesvideos** [rcmaehl/MSEdgeRedirect#318]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Install Active mode
Keep "Disable Windows Copilot" and "Disable Bing Chat" off
Open Copilot

### ✔️ Expected Behavior

Open Copilot

### ❌ Actual Behavior

Error shows saying "Invalid parameter -"--MSEdgeRedirect."
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/87779575/9a378952-6b63-4366-8fbd-5b79d77b31fe)

### Microsoft Windows version

Windows 11 Pro 22H2, 22621.2361

**Comment by rcmaehl** [comment]
Script somehow failed its recursion prevention check. Will get this patched

**Comment by rcmaehl** [comment]
Note to self,

Move https://github.com/rcmaehl/MSEdgeRedirect/blob/main/MSEdgeRedirect.au3#L168-L171 into https://github.com/rcmaehl/MSEdgeRedirect/blob/main/MSEdgeRedirect.au3#L93-98

**Comment by rcmaehl** [comment]
Should be fixed. Please try this test build if you're still having the issue:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by pylesvideos** [comment]
Ok!
