### ISSUE TITLE
Chrome starts with `--win-session-start` after reboot

### ISSUE THREAD

**Issue by bilogic** [rcmaehl/MSEdgeRedirect#321]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Unsure, all I know is after each reboot, I get that Chrome window opening with address bar filled with `--win-session-start` 

### ✔️ Expected Behavior

Chrome should not open with `--win-session-start` 

### ❌ Actual Behavior

Chrome opens `--win-session-start` 

### Microsoft Windows version

22H2 19045.3448

**Comment by Tyne-Bridges** [comment]
This is happening for me too but (oddly) doesn't seem to have been flagged as a common issue...

**Comment by bilogic** [comment]
https://github.com/rcmaehl/MSEdgeRedirect/issues/325 

Reported another issue which is worse than this

**Comment by haraop** [comment]
Happening here too.

**Comment by rcmaehl** [comment]
Please try the latest test build when possible:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by bilogic** [comment]
@rcmaehl 

Yes, this new build doesn't create the problem anymore. However, I had to do the following to solve my problem:

1. Delete the `--win-session-start` from the registry
2. Reinstall mser from the zip (btw it says `0.7.5.0` in the installer, not `0.8.0.0`)

**Comment by bilogic** [comment]
@rcmaehl this issue is back. I did not update or anything.

**Comment by chjohans** [comment]
I have the chrome "--win-session-start" issue too!

**Comment by mon5termatt** [comment]
still seeing this issue.
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/43628254/a2ba5b9e-9d97-422c-9b85-b051516cfd5f)
Current Version.

**Comment by oddtwelve** [comment]
me too

**Comment by simwai** [comment]
I have this issue too, with the latest version.

**Comment by KarlLee830** [comment]
same

**Comment by Tiwas** [comment]
Any resolution? This just started happning today (or was it yesterday?) without updating or anything. The only thing I've done is clearing the browser. Would love to get rid of this tab, preferably without having to deal with edge :)

**Comment by rcmaehl** [comment]
I will be pushing out an update this weekend. I would have had the update out by now but I was in a car accident and have been dealing with all of that hassle between insurance, medical, car rental, and everything else.

**Comment by bilogic** [comment]
Will this be released soon? Thank you.

**Comment by vonDubenshire** [comment]
> I will be pushing out an update this weekend. I would have had the update out by now but I was in a car accident and have been dealing with all of that hassle between insurance, medical, car rental, and everything else.

hope you're ok!  Still waiting to see an update but definitely understand issues like that! It is a pain.

**Comment by rcmaehl** [comment]
> > I will be pushing out an update this weekend. I would have had the update out by now but I was in a car accident and have been dealing with all of that hassle between insurance, medical, car rental, and everything else.
> 
> hope you're ok! Still waiting to see an update but definitely understand issues like that! It is a pain.

Was planning to but found a few more bugs. Trying to fix the issue in #345 first.

**Comment by vonDubenshire** [comment]
> > > I will be pushing out an update this weekend. I would have had the update out by now but I was in a car accident and have been dealing with all of that hassle between insurance, medical, car rental, and everything else.
> > 
> > 
> > hope you're ok! Still waiting to see an update but definitely understand issues like that! It is a pain.
> 
> Was planning to but found a few more bugs. Trying to fix the issue in #345 first.

strange bug, haven't run into that being an issue on my side before 

hope you get it fixed!

**Comment by bilogic** [comment]
Hi,

Will this be resolved soon? Thank you.

**Comment by bilogic** [comment]
@rcmaehl how can we test the fix? thanks

**Comment by simwai** [comment]
@bilogic Get the latest version I guess?

**Comment by bilogic** [comment]
and when is that dated?

**Comment by simwai** [comment]
Idk

**Comment by uffemcev** [comment]
I still have this problem on the latest version.

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/96709114/ad92a5ed-6a07-4a63-a924-9a8c0b2f561b)

**Comment by bilogic** [comment]
@rcmaehl appreciate if you can fill us in on this. Thank you.

**Comment by uffemcev** [comment]
@rcmaehl any thoughts?

**Comment by rcmaehl** [comment]
> @rcmaehl any thoughts?

Should be resolved in 0.7.5.1 or 0.7.5.2. Is it --win-session-start or another message?

**Comment by uffemcev** [comment]
> Is it --win-session-start or another message?

`--win-session-start`

**Comment by bilogic** [comment]
`0.7.5.1` and `0.7.5.2` fixed the `--win-session-start` for me.
