### ISSUE TITLE
Autolt error popup

### ISSUE THREAD

**Issue by UsainSrht** [rcmaehl/MSEdgeRedirect#322]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

i dont know exactly, yesterday the app started spamming me(new popu like every 5 seconds) with popups that say "there is an update" so i installed the latest release on github. After i run the setup it kept saying there is an update so i restarted my pc. Problem wasn't solved and i decided to make a clean install, uninstalled the msedgeredirect, installed the latest version and now it sometimes opens a Autolt error popup. its kinda annoying.

### ✔️ Expected Behavior

no error popups?

### ❌ Actual Behavior

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/59025999/69e1afd2-b5a5-4179-a637-ee9e46104a26)

### Microsoft Windows version

22H2 23555.1000

### Other Software

settings 
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/59025999/fa96057c-a8ba-40eb-bafa-ae7fb06e44ba)

**Comment by rcmaehl** [comment]
Please try the latest test build. This should be fixed :)
