### ISSUE TITLE
Newest update reopens Edge every time the browser is closed

### ISSUE THREAD

**Issue by quartzbear** [rcmaehl/MSEdgeRedirect#324]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

I updated MSEdgeRedirect to the latest version. I opened Edge and attempted to close it pressing the X,

### ✔️ Expected Behavior

That Edge would stay closed.

### ❌ Actual Behavior

Now every time I close Edge it reopens unprompted, and I need to kill the processes in Task Manager.
I discovered that if I open the menu and click on "close Microsoft Edge" it doesn't keep on restarting.

[AppFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/12822577/AppFailures.log)
[AppGeneral.log](https://github.com/rcmaehl/MSEdgeRedirect/files/12822578/AppGeneral.log)
[AppSecurity.log](https://github.com/rcmaehl/MSEdgeRedirect/files/12822580/AppSecurity.log)
[Install.log](https://github.com/rcmaehl/MSEdgeRedirect/files/12822581/Install.log)
[PEBIAT.log](https://github.com/rcmaehl/MSEdgeRedirect/files/12822582/PEBIAT.log)

### Microsoft Windows version

22H2 Build 22621.2283

**Comment by bilogic** [comment]
duplicate in #315
