### ISSUE TITLE
Edge keeps reopening when closed until `...`, `Close Microsoft Edge`

### ISSUE THREAD

**Issue by bilogic** [rcmaehl/MSEdgeRedirect#325]
### Preflight Checklist

- [x] Running `microsoft-edge:https://google.com` redirects successfully
- [x] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

1. After I open my Edge and try to close it, it will close but reopens immediately
2. This repeats until I go to `...`, `Close Microsoft Edge`

### ✔️ Expected Behavior

Edge should not reopen immediately

### ❌ Actual Behavior

Edge should keeps reopening

### Microsoft Windows version

22H2 19045.3448

**Comment by haraop** [comment]
Happening here as well.

**Comment by bilogic** [comment]
and #315
