### ISSUE TITLE
PDF files not found error and 7 addionatl tabs when using MS Edge as default

### ISSUE THREAD

**Issue by ctorbaoglu** [rcmaehl/MSEdgeRedirect#326]
### Preflight Checklist

- [ ] Microsoft Edge is selected in any "How do you want to open this?" box
- [ ] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

New Install

### Install Mode

Active Mode

### ℹ Behavior

No matter PDF viewer option not checked when opening PDFs, Edge says File not found and opens another 6 more (different) tabs. And addinatal tabs has no meaning names. Event check Deafult or custom and choose MSEdge from the opened window.
This occurres every version after 7.3.0 (which is the only version works well).  I updated to the latest release 0.7.5.0 tried fresh installing but it still exists.

### Microsoft Windows version

23H2 build 22635.2419

### Other Software

![Screenshot 2023-10-11 202752](https://github.com/rcmaehl/MSEdgeRedirect/assets/47308120/5d72964f-d094-47cd-8ba5-969a97606fc2)

**Comment by hyperio546** [comment]
Same. And CoPilot doesn't work with service mode even though this gets fixed. I cannot use it unfortunately.

**Comment by Sutliff707** [comment]
I have found this happens to me when the file path directory or the file has spaces in the name. As a current work around, try removing spaces in file path directories and file names.
