### ISSUE TITLE
Random error dialogs have started popping up

### ISSUE THREAD

**Issue by akienm** [rcmaehl/MSEdgeRedirect#327]
### Preflight Checklist

- [x] Running `microsoft-edge:https://google.com` redirects successfully
- [x] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Managed Update (Chocolatey, Winget, Etc)

### Install Mode

Unsure

### Steps to reproduce

Heard about your app some months ago, been working great. Until last week. Started seeing a slew of error windows up when I've been away from the computer for a while. Sometimes it's just a couple, sometimes upwards of a dozen. The error box says:

Line 2986 (File "C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe"): 
Error: Array variable has incorrect number of subscripts or the subscript dimension range exceeded.

I tried uninstall/reinstall to no avail. 

### ✔️ Expected Behavior

Not to have random error boxes :) 

### ❌ Actual Behavior

Lots of actual error boxes. Got two while i was away at lunch

### Microsoft Windows version

22H2 19045.3570

**Comment by akienm** [comment]
Update: Right clicking on an INI file and selecting open with edge resulted in that same box coming up.

**Comment by akienm** [comment]
Well, I solved it, tho seems weird to me. I first installed this via winget, and as I said, it was working fine... But recently I told winget to update all, and that's when the wacky started. So today, I tried just running  "C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe", and this time I was presented with an install wizard. That seems to have solved the issue.

**Comment by akienm** [comment]
I spoke too soon. They're back. but they're not showing up from Open With anymore

**Comment by akienm** [comment]
I spoke too soon. They're back, but not from "Open With" anymore. But the coming up randomly, yep.

**Comment by rcmaehl** [comment]
This should be fixed in the latest test build.

I had made some assumptions about array sizing.. 
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/f84d0c10-2e1f-4eff-a5b2-3b7b8560ea38)

which is now fixed
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/083f8415-cf4d-454f-b792-1a38204d0512)

**Comment by akienm** [comment]
I have replaced the file. 

Now when I right click on a text file and say open with edge, there's some VERY brief activity in the tray (couldn't capture an image) and then nothing. 

So now we're not getting errors on open with... 
But also nothing is opening in either browser. 
And still waiting to see about random errors (seems unlikely, will know in a few hours).

More as I know it.

**Comment by akienm** [comment]
No more random errors over a protracted time. So that issue resolved.

Still Open As Edge to, say an INI file, and there's a tray flicker, but nothing else happens. The INI is not opened in either browser.
