### ISSUE TITLE
Error popups

### ISSUE THREAD

**Issue by miguel-mib** [rcmaehl/MSEdgeRedirect#328]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Deployment (Chocolatey, Winget, Etc)

### Install Mode

Active Mode

### Steps to reproduce

While I use the computer, a error popup randomly appears with the title "Autolt Error"

### ✔️ Expected Behavior

no error popups appear

### ❌ Actual Behavior

pop ups appearing randomly with the title "Autolt Error"

---------------------------
AutoIt Error
---------------------------
Line 2986  (File "C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe"):

Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded.
---------------------------
OK   
---------------------------

### Microsoft Windows version

22H2 22621.2428

**Comment by NanoCompute** [comment]
I'm having the same issue. Seven are popped up on my screen and it keeps on growing gradually.

**Comment by TonyGstring** [comment]
Same here.

**Comment by NanoCompute** [comment]
I found out every time I get a notification on my iPhone this error pops up. I have the phone link for iOS on my pc. It’s supposed to have a notification pop up like any other notification on windows 11 when I get a notification on my iPhone, but instead this error pops up. I hope that helps.

**Comment by blackmoth1911** [comment]
Same happens every log in and when I right click the desktop

"msedgeredirect autoit error line 2986"
