### ISSUE TITLE
not getting the redirect functionality

### ISSUE THREAD

**Issue by mcfalld** [rcmaehl/MSEdgeRedirect#33]
**Check List**
- [x] The App appears in the system tray
- [x] Running `microsoft-edge:https://google.com`  gives the following:

![image](https://user-images.githubusercontent.com/32588824/146289362-dc539c06-5a15-4415-80ee-2cc92f1b0fa2.png)

**Describe the bug**\

**To Reproduce**
1. search for anything that initiates a web search in the startmenu/search bar
2. see the same prompt from the screenshot

**⚠️ File Upload ⚠️**

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files

6. gwmi: The term 'gwmi' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Desktop (please complete the following information):**
 - Windows Edition: Windows 10 Pro for Workstations
 - Version: 21H2
 - Windows Build: 19044.1415

**Additional context**\

**Comment by mcfalld** [comment]
[edge.txt](https://github.com/rcmaehl/MSEdgeRedirect/files/7723847/edge.txt)
i was running the command in the wrong version of powershell

**Comment by rcmaehl** [comment]
Please try the latest build 
https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/mser/main/mser.zip

Microsoft made some really recent changes and the fix will be released in 0.5.0.0 (probably this evening)

**Comment by rcmaehl** [comment]
Link is apparently broken. One moment

**Comment by rcmaehl** [comment]
https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1585025130

Will be the `MSER` box.

**Comment by mcfalld** [comment]
thanks a lot! will the check for updates work once its released?

**Comment by mcfalld** [comment]
![image](https://user-images.githubusercontent.com/32588824/146293657-1fdd7b23-cb97-460e-94dd-0da05ff69021.png)

just downloaded the MSER.zip, unzipped installed and still looks the same, unless im doing something wrong

**Comment by rcmaehl** [comment]
Select the Featured. It should still redirect the search.

**Comment by mcfalld** [comment]
ah, it does open in my browser but searches with Bing. is that to be expected?

**Comment by rcmaehl** [comment]
> ah, it does open in my browser but searches with Bing. is that to be expected?

Did you select the option during setup?

If not, you can open Programs and Features and choose "change" to adjust the settings.

![image](https://user-images.githubusercontent.com/716581/146294230-eb8aa0c7-025d-43a6-a29b-b8b7361b6273.png)
