### ISSUE TITLE
Edge reinstalled but it still auto detects edge removed via AveYo

### ISSUE THREAD

**Issue by gamer20088** [rcmaehl/MSEdgeRedirect#334]
### Preflight Checklist

- [X] Microsoft Edge is selected in any "How do you want to open this?" box
- [X] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

New Deployment (Chocolatey, Winget, Etc)

### Install Mode

Unsure

### ℹ Behavior

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/46035878/acd8c0b7-c976-473a-a3fc-75458d1457cf)

### Microsoft Windows version

22H2

**Comment by rcmaehl** [comment]
Please check:

C:\Scripts
C:\ProgramData
C:\Users\Public

for _ie_to_edge_stub.exe_

If it exists, remove the file, then relaunch MSER

**Comment by rcmaehl** [comment]
If you've already installed MSER, also delete

_HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ie_to_edge_stub.exe_

from the registry

(or just remove and reinstall MSER)

**Comment by gamer20088** [comment]
> Please check:
> 
> C:\Scripts C:\ProgramData C:\Users\Public
> 
> for _ie_to_edge_stub.exe_
> 
> If it exists, remove the file, then relaunch MSER

Should I also delete it from program files?

**Comment by rcmaehl** [comment]
> Should I also delete it from program files?

No, it can be left there as that location is not checked.

**Comment by gamer20088** [comment]
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/46035878/b70af35b-4f2e-46c7-998c-4db58f19e914)
Seems that is fixed but now when I go on edge and then X out it boots up edge again. This only happens when MSER is downloaded.

**Comment by rcmaehl** [comment]
> ![image](https://user-images.githubusercontent.com/46035878/281609949-b70af35b-4f2e-46c7-998c-4db58f19e914.png) Seems that is fixed but now when I go on edge and then X out it boots up edge again. This only happens when MSER is downloaded.

Known issue with 0.7.5.0. Working on a release this weekend to address this. Try the ". . ." menu -> Close Edge

**Comment by gamer20088** [comment]
> > ![image](https://user-images.githubusercontent.com/46035878/281609949-b70af35b-4f2e-46c7-998c-4db58f19e914.png) Seems that is fixed but now when I go on edge and then X out it boots up edge again. This only happens when MSER is downloaded.
> 
> Known issue with 0.7.5.0. Working on a release this weekend to address this. Try the ". . ." menu -> Close Edge

Thank you. Is the best way to update by deleting and then installing the new exe or using a deployment?

**Comment by rcmaehl** [comment]
> Thank you. Is the best way to update by deleting and then installing the new exe or using a deployment?

When MSER is ran, it will automatically check for updates about 10% of the time. Just running the newest version from the downloads page should be a good enough update.

If you're using Chocolately or WinGet for deployment they should update fine as long as they have appropriate permissions.

**Comment by gamer20088** [comment]
Thank you
