### ISSUE TITLE
Opening PDFs in v0.5 with firefox with active mode

### ISSUE THREAD

**Issue by 0ibaba** [rcmaehl/MSEdgeRedirect#34]
- [✓] The App appears in the system tray
- [✓] Running `microsoft-edge:https://google.com` redirects successfully

Opening pdf files after setting it to redirect to firefox, it just opens a new window of the browser and doesn't open the pdf file.
However setting chrome to open them seems to be working just fine.

1. Install with active mode and set firefox to open pdf files
2. Open a pdf file

[logs.zip](https://github.com/rcmaehl/MSEdgeRedirect/files/7727277/logs.zip)

 - Windows Version: 11
 - Windows Build: 22000.376

Also, the first time around I accidentally selected edge to open PDFs which sent it on a never ending loop, adding a blacklist for msedge might be a good idea.

**Comment by rcmaehl** [comment]
Just tested. Should be good in latest dev builds: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by 0ibaba** [comment]
> Just tested. Should be good in latest dev builds: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

This build is working properly :)
