### ISSUE TITLE
Phone Link notifications causing Window spam

### ISSUE THREAD

**Issue by Auriosi** [rcmaehl/MSEdgeRedirect#340]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Link a phone to the Phone Link app, then receive a notification

### ✔️ Expected Behavior

Nothing to happen

### ❌ Actual Behavior

I get spammed with popups

### Microsoft Windows version

23H2 Build 22631.2715

### Other Software

Phone Link 1.23092.151.0

**Comment by rcmaehl** [comment]
Setting this up now to investigate

**Comment by Auriosi** [comment]
As a clarification, the spam comes from the number of notifications I get (1 error per notif), but still quite annoying.

**Comment by rcmaehl** [comment]
> As a clarification, the spam comes from the number of notifications I get (1 error per notif), but still quite annoying.

AutoIt Errors?

**Comment by Auriosi** [comment]
Yes
