### ISSUE TITLE
Random tab opens while AFK

### ISSUE THREAD

**Issue by UsainSrht** [rcmaehl/MSEdgeRedirect#341]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

I don't know it just happens while I'm afk

### ✔️ Expected Behavior

no random tabs opening

### ❌ Actual Behavior

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/59025999/1385f69e-3fc4-4ac3-9ab7-ec2ed8d794ba)

### Microsoft Windows version

22H2 23585.1001

### Other Software

Google Chrome Version 119.0.6045.159 (Official Build) (64-bit)

**Comment by rcmaehl** [comment]
Will be fixed shortly

**Comment by UsainSrht** [comment]
It started to occur more and more frequently. How can i fix it temporarily, its so annoying.

**Comment by rcmaehl** [comment]
> It started to occur more and more frequently. How can i fix it temporarily, its so annoying.

You can install the latest test build from https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip which will resolve it.
