### ISSUE TITLE
MSER sometimes call my default browser with strange parameter.

### ISSUE THREAD

**Issue by xkww3n** [rcmaehl/MSEdgeRedirect#347]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

No action needed. Just open computer for a while, then my default browser will be called with the following parameter:
```
"C:\Program Files\Mozilla Firefox\firefox.exe" -osint -url "https://--no-startup-window%20--edge-reporting-task/"
```
And MSER log:
```
2023/12/04 13:02:01 - Caught Other Edge Call:
--no-startup-window --edge-reporting-task
```

### ✔️ Expected Behavior

Nothing should happen until I do something with Edge.

### ❌ Actual Behavior

My default browser opens randomly with a blank page.

### Microsoft Windows version

23H2 Build 26002.1000

**Comment by chjohans** [comment]
I have the same issue, and it has been like this for weeks.
