### ISSUE TITLE
Edge cannot open after uninstall MSRedirect!

### ISSUE THREAD

**Issue by Meonthb** [rcmaehl/MSEdgeRedirect#349]
### Preflight Checklist

- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

After uninstall the MSRedirect (used cleanup tool) and set back Edge as default browser, Edge cannot open with the error popped up:
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/60881723/3b33531e-15f2-4be7-a3ec-a33839270ca3)

Edge will only works when reinstall MSRedirect. Is there anyway to uninstall MSRedirect while keeping Edge works?

### Microsoft Windows version

23H2 build 22631.2792

**Comment by rcmaehl** [comment]
Do you get the same error if you open Microsoft Edge from the Start Menu?

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/d03d1b55-4b94-4b73-a4ac-20de08ee9395)

**Comment by Meonthb** [comment]
Thank you! It works when open Edge from Start Menu!

**Comment by rcmaehl** [comment]
You may need to unpin the shortcut from the taskbar and "repin" it if the issue persists
