### ISSUE TITLE
Document Settings Registry Keys

### ISSUE THREAD

**Issue by SamHills** [rcmaehl/MSEdgeRedirect#35]
1.  According to the page [https://github.com/rcmaehl/MSEdgeRedirect/wiki/Settings-Locations-Priority](url), MSEdgeRedirect attempts to read settings from the registry before reading Settings.ini.  Please document the registry values and types.

2.  Once MSEdgeRedirect has been installed in Active mode, can any settings be changed programmatically (i.e. from a .bat file)?  Please document how this should be done.

**Comment by rcmaehl** [comment]
> 1. According to the page [https://github.com/rcmaehl/MSEdgeRedirect/wiki/Settings-Locations-Priority](url), MSEdgeRedirect attempts to read settings from the registry before reading Settings.ini.  Please document the registry values and types.

Planning to :) 

> 2. Once MSEdgeRedirect has been installed in Active mode, can any settings be changed programmatically (i.e. from a .bat file)?  Please document how this should be done.

If not managed. Open programs and features and choose "Change". This will be improved in 0.6 (~1-2 weeks)

**Comment by SamHills** [comment]
I already tried opening Apps and clicking "Change".  There were 2 problems:
1.  It gave me the GUI installer window with the default values selected, not the settings from my Settings.ini file.
2.  I need the ability to update multiple computers via a .bat file.  A GUI solution cannot be used for this.  I searched the registry and found the settings in `HKLM\SOFTWARE\Robert Maehl Software\MSEdgeRedirect`.  If I edit these values with `REG ADD` commands, when would they take effect?  Would a reboot be necessary?

**Comment by rcmaehl** [comment]
> I already tried opening Apps and clicking "Change". There were 2 problems:
> 
> 1. It gave me the GUI installer window with the default values selected, not the settings from my Settings.ini file.
> 2. I need the ability to update multiple computers via a .bat file.  A GUI solution cannot be used for this.  I searched the registry and found the settings in `HKLM\SOFTWARE\Robert Maehl Software\MSEdgeRedirect`.  If I edit these values with `REG ADD` commands, when would they take effect?  Would a reboot be necessary?

A reboot won't be necessary. Values aren't currently cached and are read as needed. This will change in the future for performance reasons. As such, any registry changes should take effect as soon as you change them without even needing to restart the app.

**Comment by rcmaehl** [comment]
Documented [Registry Keys, Types, and Accepted](https://github.com/rcmaehl/MSEdgeRedirect/wiki/Settings-Overview) Values in the Wiki
