### ISSUE TITLE
AutoIt Crash/Error

### ISSUE THREAD

**Issue by marty0678** [rcmaehl/MSEdgeRedirect#352]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Not really sure steps, it happens about three times a day, and it seems to be random, but I keep getting this pop-up as of about a week ago (there was a windows cumulative update around that time I believe so maybe related).
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/49799843/b0dd3e1e-c6fa-47ce-82b2-6931e40a6d53)

Everything appears to still work though and MsRedirect is still working as expected though so it's not actually causing any issues but wanted to report it / provide any logs, steps, etc.

### ✔️ Expected Behavior

Not to see this pop up.

### ❌ Actual Behavior

See this pop up.

### Microsoft Windows version

23H2 Build 22631.2861

**Comment by Scanman1** [comment]
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/97991076/2c22e065-584a-4ba2-b50b-5880a12b5a76)

I just had the same popup error appear for the first time when my PC was in hybrid sleep and I just moved the mouse to wake it.

MSEdgeRedirect v 0.7.5.0
Insider Preview Windows 11 Professional 23H2 (25997.rs_prerelease.231110-1241)
Other system modifications installed:
Open Shell,  Stardock WindowFX v6.13, Groupy 2 v2.12, Fences v5.04, CursorFX v4.03, IconPackager v10.03, Start 11 v2.03, Windowblinds v11.02

**Comment by rcmaehl** [comment]
Dropping 0.7.5.1. Just typing up the release notes
