### ISSUE TITLE
Sentence Error in 0.7.5.1 Release Notes

### ISSUE THREAD

**Issue by Obscure2020** [rcmaehl/MSEdgeRedirect#358]
Someone forgot to finish a sentence before moving on to the next sentence.

> The current method sets your PC region as "in EU" and should be a permanent patch. I have verified that this method lets you uninstall Edge, but I have noThe second method to be added later requires taking ownership and modifying a System32 file...

You have verified that the current method lets you uninstall Edge, but you have no-- ***what?***

**Comment by rcmaehl** [comment]
Corrected. Thank you!
