### ISSUE TITLE
Installer duplicates itself

### ISSUE THREAD

**Issue by NJullienSweet** [rcmaehl/MSEdgeRedirect#359]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Open the exe installer from version 0.7.5.1, accept the license, hit save on the second window.

### ✔️ Expected Behavior

The 2nd setup window should close or eventually open a third window

### ❌ Actual Behavior

A new window (the same one) opens up in front of the previous one. When I click Cancel on one of the windows, all of them close at once.
![msedge](https://github.com/rcmaehl/MSEdgeRedirect/assets/139108357/8973f5f1-7075-4961-9850-529f040f29d4)

### Microsoft Windows version

23H2 build 22631.2861

**Comment by rcmaehl** [comment]
Thought I had fixed all of these. Will release a fix here in a sec.

**Comment by rcmaehl** [comment]
I did fix this... apparently I forgot to refresh the release page for it to grab the latest commit...
