### ISSUE TITLE
Europe Mode Inquiry

### ISSUE THREAD

**Issue by AidanGee7** [rcmaehl/MSEdgeRedirect#363]
### Preflight Checklist

- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Europe Mode

### Steps to reproduce

Apologies if I've completely misunderstood how the "Europe" mode works, but when I select this mode, then restart my computer when prompted, it doesn't appear to have done anything. Even when opening the installer again and then selecting "Europe" mode a second time it just asks me to reboot again, but with no changes. I've also tried enabling the two options mentioned via ViveTool.

I have an X next to "Is ID in ISRPS.json" after I restart if that means anything and also it appears my region ID reverts back to GB after the restart.

![Screenshot 2023-12-22 211900](https://github.com/rcmaehl/MSEdgeRedirect/assets/28673281/4fc4cf8b-5874-456d-87f0-f89303ba5162)

If I'm doing something obviously wrong/don't understand this new mode then feel free to call me an idiot lol. Thank you!

### ✔️ Expected Behavior

Europe mode should redirect Edge requests to Chrome in this mode (I think?)

### ❌ Actual Behavior

Web results etc from Windows search open up in Edge.

### Microsoft Windows version

23H2 26016.1012

P.S. I absolutely love this tool! The other modes have been working perfectly. Really appreciate the hard work :)

**Comment by rcmaehl** [comment]
MSEdgeRedirect's Europe mode doesn't make any other changes other than setting the Region. Mainly because Microsoft hasn't implemented all their promises yet but should by March 6, 2024. The mode should allow the users to make those changes though. (Maybe I should add a "json promised feature vs what's implemented" tracker)

I'll see if I can throw some documentation together later tonight for users wanting to mess around with Windows Settings; and I'll definitely add the ability for MSER to make these changes in a later release. :)

**Comment by e-t-l** [comment]
> MSEdgeRedirect's Europe mode doesn't make any other changes other than setting the Region

So would this be even better performance-wise than Active Mode?

And forgive me if this question has been answered elsewhere, I couldn't find anything about it. Could you please give a run-down of what the pros and cons are to Europe Mode? What exactly does changing the region accomplish, and what features of Active Mode does it therefore lack? Are there any possible unintended side effects of changing the region (e.g. with app licenses, date/time defaults, keyboard layout, useragent/location, etc? assume the device is currently set to USA)

**Comment by rcmaehl** [comment]
> > MSEdgeRedirect's Europe mode doesn't make any other changes other than setting the Region
> 
> So would this be even better performance-wise than Active Mode?
> 
> And forgive me if this question has been answered elsewhere, I couldn't find anything about it. Could you please give a run-down of what the pros and cons are to Europe Mode? What exactly does changing the region accomplish, and what features of Active Mode does it therefore lack? Are there any possible unintended side effects of changing the region (e.g. with app licenses, xbox content, date/time/language defaults, useragent/location, etc?)

Excuse the late reply. I've been on vacation. Europe Mode technically will have greater performance as it doesn't have to hack around Microsoft's Edge restrictions. It is less feature rich however, but I'm sure there's Browser Extensions that can assist (but I haven't looked into)

**Comment by jfdl1991** [comment]
First thanks so much for your program!
Europe mode is not working for me. Is it some recent update? I'm on win 11 25H2
