### ISSUE TITLE
Microsoft Store inoperable

### ISSUE THREAD

**Issue by Masamune3210** [rcmaehl/MSEdgeRedirect#364]
### Preflight Checklist

- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Unsure

### Steps to reproduce

1. Enable Europe Mode
2. Realize that the Microsoft Store and anything involving it, including winget no longer works
3. Manually revert the settings in the registry

### ✔️ Expected Behavior

For there to be a warning stating that Store might break

### ❌ Actual Behavior

No such warning present, lots of exasperated sighs and copy/paste sessions 

### Microsoft Windows version

22H2

**Comment by rcmaehl** [comment]
I saw a few issues from setting another region that resolved after a restart/reboot once the registry was set which is why I added the warning. Can you verify if you had rebooted after the registry change?

**Comment by Masamune3210** [comment]
Yes, rebooted twice, nothing changed and on top of the store not working, edge still wasn't uninstallable. that might have been because I didn't try vivetool yet, but I know the store and winget issues were still present

**Comment by rcmaehl** [comment]
Investigating 👍

**Comment by davwheat** [comment]
This happened for me yesterday, then after a couple of reboots and leaving the store open, it told me it had to restart the Store app to update my region, after which it worked again.

**Comment by sovy666** [comment]
> This happened for me yesterday, then after a couple of reboots and leaving the store open, it told me it had to restart the Store app to update my region, after which it worked again.

Following the previous comment, I changed the geographic area from Windows Settings and now the Store works again.

**Comment by chip33** [comment]
How can I completely revert the settings for Europe mode back to how they were before the change? 
I was expecting to see a Revert button or something similar after the reboot but despite changing my 'Country or region' settings in Windows back to normal and rebooting, MSEdgeRedirect still shows Default region ID as DE.

**Comment by rcmaehl** [comment]
> How can I completely revert the settings for Europe mode back to how they were before the change? I was expecting to see a Revert button or something similar after the reboot but despite changing my 'Country or region' settings in Windows back to normal and rebooting, MSEdgeRedirect still shows Default region ID as DE.

In `%localappdata%\MSEdgeRedirect\logs\Install.log` the oldest entry should have your original values

In RegEdit set:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Control Panel\DeviceRegion\DeviceRegion`
`HKEY_USERS\.DEFAULT\Control Panel\International\Geo\Name`
`HKEY_USERS\.DEFAULT\Control Panel\International\Geo\Nation`
`HKEY_CURRENT_USER\Control Panel\International\Geo\Name`
`HKEY_CURRENT_USER\Control Panel\International\Geo\Nation`

To their previous values.

I'll throw up a script to revert it in [the assets folder](https://github.com/rcmaehl/MSEdgeRedirect/tree/main/Assets) within the next couple days
