### ISSUE TITLE
Explorer keep restarting forever after reboot 

### ISSUE THREAD

**Issue by Bartolini1522** [rcmaehl/MSEdgeRedirect#366]
Hi, I've installed the program, enabled the Europe mode, setted it to Italy, and than after the reboot explorer keeps crashing and restarting again forever and I'm struck in an infinite loop that prevents  me from using my pc.
https://github.com/rcmaehl/MSEdgeRedirect/assets/103816175/05057184-8b5b-4aa0-a850-284771d1eb71

**Comment by rcmaehl** [comment]
Merging with #367
