### ISSUE TITLE
Last update breaks Explorer and Settings in Windows 10 (+ Europe Mode does not work as intended)

### ISSUE THREAD

**Issue by tintincastro** [rcmaehl/MSEdgeRedirect#367]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Europe Mode

### Steps to reproduce

I downloaded the 0.7.5.2 update when prompted and tried Europe Mode (Set it to France / 84).

I rebooted and since then, although explorer is running (I have desktop and taskbar access, explorer is usable in save as dialogs, etc..), it won't open **any file explorer windows** (methods tried : Clicking This PC or via shortcut Win+E or using start in cmd…).

Furthermore, I cannot access **Windows Settings Home** anymore (the windows loading shows up with the gear icon, but automatically closes). I can access some subpages of settings (eg. via Sound Settings, or Using right click > properties on This PC, or right-clicking on Desktop to customize background), but whenever I try to go to Home settings, the window closes.

And Microsoft Edge is not uninstallable (I tried using the old control panel) : only repair option is available.

Here are the steps I went through in order to fix this, that didn't work:

 * Rebooted multiple times
 * Uninstalled MSEdgeRedirect and reinstall in Active Mode
 * Try to fix system using sfc and DISM
 
(I welcome any suggestion to try and fix this without a full windows reinstall).

### Microsoft Windows version

22H2 build 19045.3803

**Comment by rcmaehl** [comment]
Are you able to open regedit at all?

If so:

1) Go To https://docs.dnb.com/partner/en-US/iso_country_codes and seach your country. You'll need the `ISO 2 char`
2) Go To https://learn.microsoft.com/en-us/windows/win32/intl/table-of-geographical-locations and seach your country. You'll need the `Geographical location identifier (decimal)`

In RegEdit set:

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Control Panel\DeviceRegion\DeviceRegion`
`HKEY_USERS\.DEFAULT\Control Panel\International\Geo\Name`
`HKEY_USERS\.DEFAULT\Control Panel\International\Geo\Nation`
`HKEY_CURRENT_USER\Control Panel\International\Geo\Name`
`HKEY_CURRENT_USER\Control Panel\International\Geo\Nation`

To their previous values. `ISO 2 char` will replace `FR` and `Geographical location identifier (decimal)` will replace `84`

Working on a reversion script now for those having issues.

## For anyone else having issues, please let me know what EU Country you set so I can rule out specific countries having issues.

**Comment by tintincastro** [comment]
Thanks for your input, it actually corrected the bug on my system (file explorer windows and settings home page are back).

I did not exactly revert everything since I remember when initially setting Europe Mode in MSER, some values where already configured (84), as was confirmed in the Install.log file: `Read Pre-European Install Values of: 84|84|84 & |`

I only removed the `Name` keys ('FR') leaving empty values, and this alone seemed to immediately correct the bug (no reboot needed).

Don't know if it might help, but for information, my installation of windows 10 was from years back, as an in-place upgrade from a 7 version. It was never linked with a windows live account, and pretty much since the beginning, I removed telemetry and access to microsoft store.

**Comment by rcmaehl** [comment]
> Thanks for your input, it actually corrected the bug on my system (file explorer windows and settings home page are back).
> 
> I did not exactly revert everything since I remember when initially setting Europe Mode in MSER, some values where already configured (84), as was confirmed in the Install.log file: `Read Pre-European Install Values of: 84|84|84 & |`
> 
> I only removed the `Name` keys ('FR') leaving empty values, and this alone seemed to immediately correct the bug (no reboot needed).
> 
> Don't know if it might help, but for information, my installation of windows 10 was from years back, as an in-place upgrade from a 7 version. It was never linked with a windows live account, and pretty much since the beginning, I removed telemetry and access to microsoft store.

I'll see if either of those can be left blank while keeping Europe mode. If so, I'll implement it as a patch

**Comment by indyawala** [comment]
> Thanks for your input, it actually corrected the bug on my system (file explorer windows and settings home page are back).
> 
> I did not exactly revert everything since I remember when initially setting Europe Mode in MSER, some values where already configured (84), as was confirmed in the Install.log file: `Read Pre-European Install Values of: 84|84|84 & |`
> 
> I only removed the `Name` keys ('FR') leaving empty values, and this alone seemed to immediately correct the bug (no reboot needed).
> 
> Don't know if it might help, but for information, my installation of windows 10 was from years back, as an in-place upgrade from a 7 version. It was never linked with a windows live account, and pretty much since the beginning, I removed telemetry and access to microsoft store.:i












Hi, tried installing via german DE and it crashed boot up screen, made changes in registry, still same. 
welcome screen is just flickering and not respite from that.

German version (DE) seems to be serious bug. please check
Thanks

**Comment by indyawala** [comment]
https://github.com/rcmaehl/MSEdgeRedirect/assets/154864191/ded76329-ffe0-4507-923e-0f3a8ab05574

**Comment by indyawala** [comment]
German DE and it crashed boot up screen, not allowing to do anything. Tried task manager, made changes in registry via safe mode, via other admin login, nothing helps.
welcome screen is just flickering and not respite from that.

German version (DE) seems to be serious bug.  Only resort is system restore.

**Comment by LessThread** [comment]
Hi,I encountered the same problem. I tried using a third-party file explorer, but it didn't work. I also followed the steps mentioned above to modify the registry, but it had no effect. I also performed a Windows update, but I still can't use the File Explorer.

**Comment by VISTALL** [comment]
Same issue with PL - after install, file exporer not works, settings crashed

**Comment by LessThread** [comment]
> Same issue with PL - after install, file exporer not works, settings crashed
> 
> Removing nodes from
> 
> HKEY_CURRENT_USER\Control Panel\International\Geo
> 
> fixed issues.
> 
> From Settings I had set 'Poland' and saw same keys+values, but now - all interface works as expected

It works,thank you!😀

**Comment by bogmar** [comment]
Switching to Bulgaria broke the Start menu. Reverting to USA fixed it.
My region is actually Bulgaria but during the Windows installation I choose US as a region. After installation I changed it to Bulgaria but I've noticed the machine id stays as US.

**Comment by CastorDYvaine** [comment]
Hi, I chose the Germany option, I got an explorer crash loop and settings not starting.
Removing the values at `HKEY_CURRENT_USER\Control Panel\International\Geo` worked for me.
Thanks to @VISTALL for the advice.

**Comment by rcmaehl** [comment]
This should be fixed!
