### ISSUE TITLE
Improve RunHTTPCheck()

### ISSUE THREAD

**Issue by dongle-the-gadget** [rcmaehl/MSEdgeRedirect#38]
Other Edge channels are also affected by the `microsoft-edge:` protocol as well. Seems that the program just lazy checks if `msedge.exe` is the browser, which causes the program to immediately throw a "select another browser" error on startup.

**Comment by rcmaehl** [comment]
Active Mode already allows other Edge channels, so I'm assuming this is for Service Mode. I'll look into adding it.

**Comment by dongle-the-gadget** [comment]
> Active Mode already allows other Edge channels, so I'm assuming this is for Service Mode. I'll look into adding it.

I mean when I run the executable, it just closes itself with "change your browser".

**Comment by rcmaehl** [comment]
> > Active Mode already allows other Edge channels, so I'm assuming this is for Service Mode. I'll look into adding it.
> 
> I mean when I run the executable, it just closes itself with "change your browser".

What channel of Microsoft Edge are you using as you default browser?

**Comment by dongle-the-gadget** [comment]
> > > Active Mode already allows other Edge channels, so I'm assuming this is for Service Mode. I'll look into adding it.
> > 
> > 
> > I mean when I run the executable, it just closes itself with "change your browser".
> 
> What channel of Microsoft Edge are you using as you default browser?

Canary.

**Comment by rcmaehl** [comment]
Shouldn't give this warning anymore as long as the default browser (http/https handler) is different than what's set for the default microsoft-edge: handler.
