### ISSUE TITLE
Update Installer to update dev builds, Add Success Screen.

### ISSUE THREAD

**Issue by gnpaone** [rcmaehl/MSEdgeRedirect#39]
Unable to update the beta version directly, the only way to update is "uninstall" the old version and install new version. The new installer doesn't open at all without uninstalling previous version. Is there any way to update directly or atleast update using installer over previous version without uninstalling (it should replace the files instead of adding the files that causes storage buildup)

**Comment by gnpaone** [comment]
One more thing is there is no installation successful message after installing that makes me think as if installer failed

**Comment by rcmaehl** [comment]
You're referring to upgrading from a test build correct? If so I'll look into fixing this, either through CI or coding changs to indicate test builds.

@micwoj92 Is there a way to compile a new build on a release being created instead of using an existing CI build?

**Comment by micwoj92** [comment]
I don't really get what you mean by that question.

**Comment by rcmaehl** [comment]
> I don't really get what you mean by that question.

I just checked actions and apparently it already runs CI on release so that answered my question.

I just need to figure out how to have release compile differently and what changes I can make.

**Comment by micwoj92** [comment]
You could split this into 2 separate workflows, one for release and one for commits.

**Comment by rcmaehl** [comment]
TODO: Add Socials, Donate to Finished page
TODO: Add "Run MSEdgeRedirect" checkbox

**Comment by gnpaone** [comment]
> One more thing is there is no installation successful message after installing that makes me think as if installation failed. Also mser icon doesn't show up immediately after installing, I have to reboot for the icon to show up

Also, the mser icon never shows up in the tray icons "after installation" no matter what I do. Please check that too

**Comment by rcmaehl** [comment]
> > One more thing is there is no installation successful message after installing that makes me think as if installation failed. Also mser icon doesn't show up immediately after installing, I have to reboot for the icon to show up
> 
> Also, the mser icon never shows up in the tray icons "after installation" no matter what I do. Please check that too

Yep, left the issue open because I still have to investigate that

**Comment by gnpaone** [comment]
F

> > One more thing is there is no installation successful message after installing that makes me think as if installation failed. Also mser icon doesn't show up immediately after installing, I have to reboot for the icon to show up
> 
> Also, the mser icon never shows up in the tray icons "after installation" no matter what I do. Please check that too

It also doesn't appear in startup apps/startup folder (shell:startup) too, currently using https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1599718339 build
![Screenshot (5004)](https://user-images.githubusercontent.com/78990165/146697722-0564e18e-7b90-4b60-bde5-d564514da2b8.png)

**Comment by rcmaehl** [comment]
> F
> 
> > > One more thing is there is no installation successful message after installing that makes me think as if installation failed. Also mser icon doesn't show up immediately after installing, I have to reboot for the icon to show up
> > 
> > 
> > Also, the mser icon never shows up in the tray icons "after installation" no matter what I do. Please check that too
> 
> It also doesn't appear in startup apps/startup folder (shell:startup) too, currently using https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1599718339 build ![Screenshot (5004)](https://user-images.githubusercontent.com/78990165/146697722-0564e18e-7b90-4b60-bde5-d564514da2b8.png)

Is that `shell:startup` or `shell:common startup`.

**Comment by gnpaone** [comment]
> > F
> > > > One more thing is there is no installation successful message after installing that makes me think as if installation failed. Also mser icon doesn't show up immediately after installing, I have to reboot for the icon to show up
> > > 
> > > 
> > > Also, the mser icon never shows up in the tray icons "after installation" no matter what I do. Please check that too
> > 
> > 
> > It also doesn't appear in startup apps/startup folder (shell:startup) too, currently using https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1599718339 build ![Screenshot (5004)](https://user-images.githubusercontent.com/78990165/146697722-0564e18e-7b90-4b60-bde5-d564514da2b8.png)
> 
> Is that `shell:startup` or `shell:common startup`.

`shell:startup`

**Comment by rcmaehl** [comment]
I've been unable to reproduce the lack of tray icon after install for service mode. 

Also installer should be able to update dev builds, although currently only for active mode installs.

**Comment by gnpaone** [comment]
> I've been unable to reproduce the lack of tray icon after install for service mode.
Yah, the tray icon doesn't show in active mode too. I think I do remember after what action it got disappeared and now it's not coming back, it's when I completed installing one of the previous build (the builds where the installer doesn't open/update if already installed, as I mentioned earlier in this issue - it's probably the latest build version (beta) released before I typed this issue), I thought the installer crashed and relaunched the installer but installer didn't open as well as tray icon disappeared, I think probably this is the action I did and it disappeared, I am not sure

**Comment by rcmaehl** [comment]
> Yah, the tray icon doesn't show in active mode too. I think I do remember after what action it got disappeared and now it's not coming back, it's when I completed installing one of the previous build (the builds where the installer doesn't open/update if already installed, as I mentioned earlier in this issue - it's probably the latest build version (beta) released before I typed this issue), I thought the installer crashed and relaunched the installer but installer didn't open as well as tray icon disappeared, I think probably this is the action I did and it disappeared, I am not sure

Active mode doesn't have a tray icon as it doesn't need to be running in the background 24/7.

**Comment by gnpaone** [comment]
> > Yah, the tray icon doesn't show in active mode too. I think I do remember after what action it got disappeared and now it's not coming back, it's when I completed installing one of the previous build (the builds where the installer doesn't open/update if already installed, as I mentioned earlier in this issue - it's probably the latest build version (beta) released before I typed this issue), I thought the installer crashed and relaunched the installer but installer didn't open as well as tray icon disappeared, I think probably this is the action I did and it disappeared, I am not sure
> 
> Active mode doesn't have a tray icon as it doesn't need to be running in the background 24/7.

But it's good to have tray icon as it contains check for updates, hide icon, exit, etc options which will be helpful as if I want to exit the app, I can do that. It doesn't appear in task manager for stopping the app via it as well as in startup apps too

**Comment by gnpaone** [comment]
[Question] how to update the app for beta version? (As u said earlier that active mode now supports update in beta channel)

**Comment by rcmaehl** [comment]
> [Question] how to update the app for beta version? (As u said earlier that active mode now supports update in beta channel)

Should just be able to run the installer again but it's not 100% complete.

**Comment by rcmaehl** [comment]
Both service mode and active mode dev builds should be upgradeable. The "installer" will operate like a normal installer now.
