### ISSUE TITLE
Opening PDF with spaces in filename fails

### ISSUE THREAD

**Issue by bilogic** [rcmaehl/MSEdgeRedirect#390]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

https://superuser.com/questions/1828834/windows-11-edge-cannot-open-pdfs-that-have-spaces-in-filename/1829007#1829007

### ✔️ Expected Behavior

PDF with spaces in filename should open successfully in 1 Edge tab, not multiple tables

### ❌ Actual Behavior

PDF with spaces in filename causes multiple tabs to open up, each trying to load one of the word of the filename, and all of them failing.

### Microsoft Windows version

22H2 (OS Build 19045.3930)

**Comment by bilogic** [comment]
Wow, where can I get the nightly release? Thanks!

**Comment by bilogic** [comment]
@rcmaehl thanks!

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/946010/919c12e6-40a5-4784-8cb6-f1533c803fc7)

What I ended up doing was to `Download Testing`, perhaps clearer to rename it as nightlies?

**Comment by Aashishkebab** [comment]
When will this fix be in stable? This bug has been around for quite a while.

**Comment by HassaanBhae** [comment]
This isssue doesnt seem to be solved yet? i am on mser version 0.7.5.3 and still happenning.
