### ISSUE TITLE
AutoIt Error

### ISSUE THREAD

**Issue by Kyzoku** [rcmaehl/MSEdgeRedirect#391]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Close Microsoft Edge

### ✔️ Expected Behavior

Microsoft Edge closes without error.

### ❌ Actual Behavior

Microsoft Edge closes with the error:

Line 2986 (File "C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe");
Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded.

### Microsoft Windows version

23H2 (22631.3085)

### Other Software

MSEdgeRedirect
Version 0.7.5.3

Microsoft Edge
Version 121.0.2277.128 (Official build) (64-bit)

**Comment by rcmaehl** [comment]
That's odd. I'm not seeing anything in the compiled script related but I compiled from source for that version. I'll try to decompile and take a look at the decompiled version.

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/c242cc68-530b-4233-bb60-830cd2f24ee4)


Was this a one time error does it occur every time?

**Comment by Kyzoku** [comment]
It happens every time.

**Comment by Kyzoku** [comment]
After a complete format and reinstall of windows I no longer get this problem.  I'm wondering if when I had updated it from a previous version I had been using the update didn't fully take hold.

However, now when I close Edge my default browser (Vivaldi) opens a new window.

**Comment by rcmaehl** [comment]
> After a complete format and reinstall of windows I no longer get this problem. I'm wondering if when I had updated it from a previous version I had been using the update didn't fully take hold.
> 
> However, now when I close Edge my default browser (Vivaldi) opens a new window.

Thank you for the update. I'm looking into the empty browsing window issue as someone else reported it occuring as well
