### ISSUE TITLE
Microsoft Edge is exempt from EU antitrust

### ISSUE THREAD

**Issue by fxzxmicah** [rcmaehl/MSEdgeRedirect#393]
Does this mean Microsoft Edge will remain uninstallable?
It was recently reported that uninstalling Microsoft Edge will cause Windows 10 updates to fail.

**Comment by rcmaehl** [comment]
I'll look into this

**Comment by fxzxmicah** [comment]
https://blogs.microsoft.com/eupolicy/2024/03/07/microsoft-dma-compliance-windows-linkedin/
This latest article clarifies that, Edge is uninstallable.

**Comment by rcmaehl** [comment]
I haven't seen any changes so far that would imply this but I'll keep an eye out
