### ISSUE TITLE
could this breakpoint be anything to do with MSER?

### ISSUE THREAD

**Issue by gazzawazza** [rcmaehl/MSEdgeRedirect#398]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

EDIT: just a standard install, then updated quite some time ago to MSER 0.7.5.3

### Install Mode

N/A or Unsure

### Steps to reproduce

got a breakpoint on win 10 pro 22h2 startup page i.e. login page

0x80000003

msedgewebview2.exe

doesn't normally happen

i have assumed webview2 is a component of or utilises edge in some way.

i recently updated Edge to 122.0.2365.80 (probably about 4 days ago)

EDIT: i've got an app which happens to note installation dates (effectively also updates) of apps and apparently MS edge webview2 runtime was 'installed' on 04 March 2024. Don't know if this is relevant.

Given MSER directly 'interacts' with edge, i wondered if this might be relevant to MSER.

### ✔️ Expected Behaviour

no error / breakpoint

### ❌ Actual Behaviour

got this breakpoint error

### Microsoft Windows version

win10 pro 22h2 19045.3930

**Comment by rcmaehl** [comment]
MSEdgeRedirect shouldn't be affected MSEdgeWebView2, but if you can provide evidence that it is please provide it.
