### ISSUE TITLE
my issue is with Macro$oft not you. THANK YOU!

### ISSUE THREAD

**Issue by budafuko** [rcmaehl/MSEdgeRedirect#40]
when edge deflector went down and microsoft stopped you from being able to switch protocol on edge links i lost hope

not only was bill gates bringing his 1996 antivirus model to real life but he was butt fucking us while he was doing it trying to force us to switch to edge and if you called for support they would tell you to reset edge and switch to edge with no real help being offered for the problem

it is clear that it is a tactic they are using to try to force peoples hand in switching to edge (who wants to use 2 browsers or copy/paste a link every time billy thinks he knows what program you should use better than you know)

should be against monopoly laws

thank you very much for this software! it is much needed 

respect

**Comment by Masamune3210** [comment]
Gates has almost less than nothing to do with anything Microsoft does anymore.....

**Comment by rcmaehl** [comment]
No problem :)
