### ISSUE TITLE
The icon is not hidden from system tray.

### ISSUE THREAD

**Issue by josh1221wa** [rcmaehl/MSEdgeRedirect#41]
The app works and all but it doesen't hide itself in the system tray. During install I had set it to hide but it still pops up on the system tray. If I manually hide it from the tray it goes but it comes back on system restart. I'm using Windows 11.

**Comment by rcmaehl** [comment]
Can you open the following directory:

![image](https://user-images.githubusercontent.com/716581/146687085-8e7d090f-71fb-476c-9741-fbc31e99dc12.png)

And send me a screenshot of it's properties?

![image](https://user-images.githubusercontent.com/716581/146687145-89979820-9116-4abb-9f7b-fdfc419af846.png)

**Comment by rcmaehl** [comment]
Please try the latest dev build:
https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by 0ibaba** [comment]
> Please try the latest dev build: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

![image](https://user-images.githubusercontent.com/69052158/146770817-ad33eee4-5c14-48a1-b087-073e114f5792.png)

This is the properties of the shortcut that's automatically created

**Comment by rcmaehl** [comment]
> > Please try the latest dev build: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
> 
> ![image](https://user-images.githubusercontent.com/69052158/146770817-ad33eee4-5c14-48a1-b087-073e114f5792.png)
> 
> This is the properties of the shortcut that's automatically created

Odd

**Comment by rcmaehl** [comment]
> > Please try the latest dev build: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
> 
> ![image](https://user-images.githubusercontent.com/69052158/146770817-ad33eee4-5c14-48a1-b087-073e114f5792.png)
> 
> This is the properties of the shortcut that's automatically created

Corrected in 7743753
