### ISSUE TITLE
Not working on 32 bit...

### ISSUE THREAD

**Issue by N2FC** [rcmaehl/MSEdgeRedirect#42]
Using 0.5.0.1:

I have 2 WIN 10 machines: 32 bit & 64 bit... both on 21H2..

Works fine on the 64 bit...
Not working on 32 bit...

Any ideas??

**Comment by rcmaehl** [comment]
Have you tried both Service and Active modes on the 32-bit machine?

**Comment by N2FC** [comment]
Tried both ways...
1) Active mode still opens in MSEdge...
2) Service mode seems to "eat" the requests and doesn't open ANY browser!

**Comment by rcmaehl** [comment]
Ah. I believe I know the issue.

**Comment by rcmaehl** [comment]
Please try the "MSER" from https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1600136708 and let me know if it's working for you now.

**Comment by N2FC** [comment]
Much better!
