### ISSUE TITLE
I wanted to make the switch to edge having redownloaded msedgeredirect. 

### ISSUE THREAD

**Issue by Prof-Max** [rcmaehl/MSEdgeRedirect#421]
### Preflight Checklist

- [X] Microsoft Edge is selected in any "How do you want to open this?" box
- [X] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

New Install

### Install Mode

Active Mode

### ℹ Behavior

I deleted MSEdgeRedirect because I wanted to go back to edge as default browser. This stopped edge working (I could open the application but the tabs wouldn't load).
When I redownloaded MSEdgeRedirect Edge worked again.
I was told this uninstall issue was fixed in a dev build, but unsure how to download this...
Using Edge alongside MSEdgeRedirect works well tbh - except for ONE thing, which is really annyoing. It doesn't let you use Edge as your default PDF viewer - if there could be an update that allows you to use Edge as your PDF viewer, it means you can use edge with bing redirection to google from windows search, but still use edge...
Please help me - I want to be able to open PDFs in edge, but can't uninstall edgeredirect!!

### Microsoft Windows version

23H2 Build 22631.3447

**Comment by rcmaehl** [comment]
Did you intend to close this as completed or do you still need assistance?

**Comment by Prof-Max** [comment]
I managed to download the developer version, which seems to have basically inactivated MSEdgeRedirect – I would ideally like Windows search to redirect to google on Edge, but it instead just goes to bing on Edge (seems like MSEdgeRedirect just not active at all).

However, this is preferable to the situation before where I was on stable version, where if I deleted it Edge didn’t work, and if I had it active then I couldn’t open PDFs on edge.

Is there a way to just redirect bing from google search only?

Cheers
