### ISSUE TITLE
MSEdgeRedirect will not install

### ISSUE THREAD

**Issue by jjuenger304** [rcmaehl/MSEdgeRedirect#424]
Robert,
I recently acquired a new computer and I'm trying to install MSEdgeRedirect v7.5.3 and following the programs install process, when I click on the "Install" button, a pop up appears indicating "Unable to copy application to C:\Program Files\MSEdgeRedirect.exe.

I'm running Windows 11 Pro v10.0.22631 Build 22631.

The program worked on my old computer running Windows 10 Pro.

Any workarounds for this?

If you want, you can converse with me directly by email at jjuenger@sbcglobal.net

I'm willing to bet that Microsoft has installed an update that is blocking the install. Don't know if this helps, but the updates are:
KBKB5037771 on June 1st, KB5037591 also June 1st and KB5037853 on June 6th.

Thanks.

**Comment by rcmaehl** [comment]
Excuse the late reply, I've had a lot on my plate lately.

Please

1. Run the setup
2. Once the error box appears, copy the MSEdgeRedirect.exe file to C:\Program Files\MSEdgeRedirect\
3. End the existing MSEdgeRedirect Process using the Processes Tab in Task Manager
4. Run C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe /settings and configure the settings you want

If you still have issues with this workaround, please let me know.

**Comment by jjuenger304** [comment]
Robert,

 

I’ll bet your plate if full, especially with Microsoft changing things every week with their Windows updates.

 

Thanks for getting back to me. The fix you provided worked like a charm. Items usually directed to Bing are now going to my default browser.

 

Again, thank you.
