### ISSUE TITLE
Ability to catch/redirect webviews

### ISSUE THREAD

**Issue by Bluscream** [rcmaehl/MSEdgeRedirect#432]
### Description of the new feature / enhancement

Would be nice if MSER would find a way to wedge another webview in so applications relying on them (e.g. HASS.Agent, some game launchers) can continue functioning without the need of Edge.

Ideally redirecting to something privacy friendly like ungoogled-chromium or firefox/librewolf

### Scenario when this would be used?

examples given above

**Comment by rcmaehl** [comment]
I'm sure something could be done with msedgewebview2 to port calls to Electron or Chrome but this isn't something I'm going to attempt for a LONG time, if ever.
