### ISSUE TITLE
Drop support for windows 8.1

### ISSUE THREAD

**Issue by micwoj92** [rcmaehl/MSEdgeRedirect#433]
**Describe the request**
 Windows 8.1 is not supported by Microsoft Edge since end of 2022.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: `GNU/Linux 6.6.37-1-lts`
 - Build: `Linux version 6.6.37-1-lts (linux-lts@archlinux) (gcc (GCC) 14.1.1 20240522, GNU ld (GNU Binutils) 2.42.0) #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 08:04:08 +0000`

**Additional context**
N/A

**Comment by rcmaehl** [comment]
~~NO >:(~~

Okay

**Comment by micwoj92** [comment]
hehe
