### ISSUE TITLE
Edge randomly opening

### ISSUE THREAD

**Issue by androidacy-user** [rcmaehl/MSEdgeRedirect#441]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Service Mode

### Steps to reproduce

Install msedgeredirect
Wait
Edge randomly opens with blank window

### ✔️ Expected Behavior

Edge to not randomly open

### ❌ Actual Behavior

Edge is randomly opening

### Microsoft Windows version

23H2 Build 22631

**Comment by rcmaehl** [comment]
If this is still occurring, can you join the discord and DM me your logs from `%localappdata%\MSEdgeRedirect`
