### ISSUE TITLE
Old Internet Explorer protocols like URL:MK for old apps

### ISSUE THREAD

**Issue by Herkules97** [rcmaehl/MSEdgeRedirect#448]
### Preflight Checklist

- [ ] Microsoft Edge is selected in any "How do you want to open this?" box
- [ ] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

New Install

### Install Mode

Active Mode

### ℹ Behavior

It looks like the program works for certain protocols, but after uninstalling Edge some minutes ago it now gives me "Internet Explorer 11 unsupported" message box, translated from Swedish so may be different, instead of opening in Edge.

Expected is that it had no choice but to open in Firefox, default browser.

The program that does not want to launch in Firefox, presumably because it runs one of the older protocols that only allows Internet Explorer and was re-directed to Edge when it was installed, is Mozilla History View (http://www.nirsoft.net/utils/mozilla_history_view.html).

Is there a mode for this program to force Internet Explorer stuff to also launch default browser?
After uninstalling Internet Explorer 11 now nothing happens when I click "Open Link In Web Browser" in MZHistoryView.

I also found that Europe Mode didn't work while I am in Europe. Maybe those in NA can't uninstall Edge. If so, it definitely is a EU version of Windows. But active mode works, except these older programs using an older protocol or whatever they are doing.
I could be blind, found no way to tell it to open a different browser.

### Microsoft Windows version

Windows 10 Pro 22H2 19045.4291

### Other Software

Mozilla History View v1.65

**Comment by rcmaehl** [comment]
`8:29:46.2740663 PM	MSEdgeRedirect.exe	27080	Process Start		SUCCESS	Parent PID: 4108, Command line: "C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe" "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --from-ie-to-edge=8 -- "file:///C:/Users/rcmaehl/Desktop/index.pdf"`

**Comment by rcmaehl** [comment]
Looks doable. I'll see what I can do

**Comment by rcmaehl** [comment]
TODO: Redirect to default browser instead of just Edge.

**Comment by rcmaehl** [comment]
This is completed for 0.8
