### ISSUE TITLE
Service Mode Duplicating Windows... Again.

### ISSUE THREAD

**Issue by eturk1** [rcmaehl/MSEdgeRedirect#45]
**Describe the bug**\
Search does open Chrome, but it's two windows and second opens hundreds of tabs.
The first windows uses Bing to search, even thought replace to Google was chosen on install. 
Second window are all google searches.

see video

**To Reproduce**
type in a windows search to web

**⚠️ File Upload ⚠️**
video of behavior
https://user-images.githubusercontent.com/525280/147012084-fd57fbb6-cc8a-483b-9a8e-73e6ce94a384.mp4

**Desktop (please complete the following information):**
 - Windows Version 10
 - Windows Build:  latest

**Comment by rcmaehl** [comment]
Are you using service mode? Additionally, was edge open,already as a window running when you ran the search?

**Comment by rcmaehl** [comment]
Okay. Definitely service mode. I'd reinstall in active mode until I can look into this more.

**Comment by eturk1** [comment]
Tried installing with active and got this warning from bitdefender. 
Is this intended behavior from the special mechanism to make it work? 
Is there a way to not trigger this warning in a future build?
![image](https://user-images.githubusercontent.com/525280/147034186-84e49e7e-705d-4516-9a7d-af9d6254fafd.png)

**Comment by rcmaehl** [comment]
"Suspicious.Behavior" is so generic. It may be detecting [Image File Execution Options](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/xperf/image-file-execution-options) being set as suspicious, but all 3 current solutions to redirect microsoft-edge: are using this method.

**Comment by Masamune3210** [comment]
Nothing but another overzelous heuristic engine. There isn't much to do unfortunately other than just report it as a false positive

**Comment by eturk1** [comment]
active works!
great to have choice again :)

**Comment by HarshalKudale** [comment]
> "Suspicious.Behavior" is so generic. It may be detecting [Image File Execution Options](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/xperf/image-file-execution-options) being set as suspicious, but all 3 current solutions to redirect microsoft-edge: are using this method.

How is edge beta and dev are registering for protocol. If we can find that out it will be really easy fix these antivirus issues.

**Comment by rcmaehl** [comment]
Updating tags. I've improved Service Mode as good as I can currently.

#36 should allow additional improvement at the cost of system performance but I don't think the issue will ever be permanently fixed as the code is a race condition in the first place.

**Comment by eturk1** [comment]
update: v0.6.3.0 service mode is still causing many browser tabs to open rapidly

BTW, on Bitdefender, it's giving an a4c4.detection, which seems to come on unsigned apps.

**Comment by rcmaehl** [comment]
Closing. Tracking via #36
