### ISSUE TITLE
Swap to a Metro UI

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#46]
**Describe the request**
https://www.autoitscript.com/forum/files/file/365-metrogui-udf/

**Comment by rcmaehl** [comment]
Redesign installer to MS-like

![image](https://user-images.githubusercontent.com/716581/153738427-856d0d12-4b7c-44ba-9bba-6884fd0bec2e.png)

**Comment by Axer128** [comment]
If you do this, please also support dark mode, as it's part of the MS Metro design language options. (But not all metro apps support it despite this)

**Comment by rcmaehl** [comment]
Fixes: 

https://github.com/rcmaehl/MSEdgeRedirect/issues/170#issuecomment-1258050865

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
