### ISSUE TITLE
Trying to reverse Europe install

### ISSUE THREAD

**Issue by 22350** [rcmaehl/MSEdgeRedirect#462]
### Preflight Checklist

- [X] Microsoft Edge is selected in any "How do you want to open this?" box
- [X] I've ran the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and tried another install

### Install Type

New Install

### Install Mode

Europe Mode

### ℹ Behavior

uninstalled but news and interests stuck in german.   Don't know how to use cleanup tool.  

### Microsoft Windows version

23h2

**Comment by micwoj92** [comment]
Duplicate of #392
