### ISSUE TITLE
everything redirects to bing.com 

### ISSUE THREAD

**Issue by leo1115** [rcmaehl/MSEdgeRedirect#464]
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

i recently updated to windows 11. since then everything opens as bing.com home page. 

for instance i searched wikipedia & clicked on the wikipedia website in the search results. chrome open with 
"https://www.bing.com/WS/redirect/?q=Wikipedia&url=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvV2lraXBlZGlh&form=WSBSTK&cvid=531bd6cd73d848478aa1a28c9f28e6dd&rtk=ZN05Yov36K0xazpvDUdu83ls7RP8lrglVEo3qzW3vLJP%2Fluju8ejvChwYkzKx2B6" 
in the address bar for a brief second and then redirects to "bing.com".

it should have open the wikipedia.com page if it was working as before. 

if i search nytimes & click on the result nytime.com
"https://www.bing.com/WS/redirect/?q=nytimes&url=aHR0cHM6Ly93d3cubnl0aW1lcy5jb20vIzp+OnRleHQ9TGl2ZSBuZXdzLCBpbnZlc3RpZ2F0aW9ucywgb3BpbmlvbiwgcGhvdG9zIGFuZCB2aWRlbyBieQ==&form=WSBSTK&cvid=e6ffcffabccb4a64b43f9cc70f6e345e&rtk=iSmgwD3x%2Bpvd2wffRHsh946JZ8vvfysAsJnjkZTE6KgRntrVL8JtKIiqb3w1u0e3" 
comes in address bar and then qucikly redirects to "bing.com"

instead of opening nytimes.com

please help.

### ✔️ Expected Behavior

open "wikipedia.org"

### ❌ Actual Behavior

everything opens as "bing.com"

### Microsoft Windows version

windows 11 pro; 23H2; 10.0.22631 Build 22631

**Comment by ikkqqstudio** [comment]
same

**Comment by rcmaehl** [comment]
MMMMMMMMMMMMMMMMMMMMMMMMMM Thanks Microsoft, another Redirect Type I have to handle. 😬 I'll get this fixed. Thankfully it's just base64.

**Comment by rcmaehl** [comment]
Should be fixed next release!
