### ISSUE TITLE
Potential bug: "_layouts’s server IP address could not be found." appears in New Outlook when clicking on the OneDrive icon

### ISSUE THREAD

**Issue by umarbutler** [rcmaehl/MSEdgeRedirect#465]
### Preflight Checklist

- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

When I click on the OneDrive icon in New Outlook, I see "_layouts’s server IP address could not be found.". I am not 100% if MSEdgeRedirect is responsible for this however. I don't want to uninstall it and I don't know how to temporarily disable it. My DNS logs do not show any blocked requests when I click on the OneDrive tab.

Is there a way to temporarily disable MSEdgeRedirect without uninstalling to verify if it is the cause?

### Microsoft Windows version

23H2 (OS Build 22631.4317)

**Comment by umarbutler** [comment]
The issue turned out to be my DNS.

**Comment by rcmaehl** [comment]
> The issue turned out to be my DNS.

![image](https://github.com/user-attachments/assets/d91f9a42-d0a3-49cf-8c7e-55851151c7e4)
