### ISSUE TITLE
In 24H2, msedgeredirect stops the quick settings menu from opening.

### ISSUE THREAD

**Issue by Boxersteavee** [rcmaehl/MSEdgeRedirect#467]
### Preflight Checklist

- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Managed Update (Chocolatey, Winget, Etc)

### Install Mode

N/A or Unsure

### Steps to reproduce

Prerequisites: Be on Windows 11 24H2
1. Have MSEdgeRedirect run from boot (may not be required)
2. Try to open the quick settings menu
3. Observe it not opening
4. Go to the up-arrow thingy and quit out of MSEdgeRedirect
5. Try to open the quick settings menu again

### ✔️ Expected Behavior

The quick settings menu works as intended.

### ❌ Actual Behavior

The quick settings menu wouldn't open until I quit MSEdgeRedirect

### Microsoft Windows version

24H2 (26100.2033)

**Comment by rcmaehl** [comment]
Will look into this

**Comment by Taratay** [comment]
Can confirm, same behaviour 24H2(build 26100.2161)

**Comment by rcmaehl** [comment]
Looks like this is fixed in the Dev Build. I should probably release that to stable.

**Comment by DaRealTurtyWurty** [comment]
This appears to recur with **MSEdgeRedirect 0.8.0.0 on Windows 11 25H2**, and I captured Windows events identifying MSEdgeRedirect as the process terminating Quick Settings.

### Environment

- Windows 11 Pro 25H2, build **26200.9445**.
- MSEdgeRedirect executable file version **0.8.0.0**.
- Per-user installation at `%LOCALAPPDATA%\MSEdgeRedirect\MSEdgeRedirect.exe`, running in the background/tray and launched through a user Startup shortcut (Service Mode).
- `ShellHost.exe` file version **10.0.26100.9278**.

### Observed behavior

After using the PC for a while, clicking the network/volume area or pressing Win+A does nothing. Start and Win+N continue to work. `ShellHost.exe` is absent. Starting it manually can restore Quick Settings temporarily, but the problem returns.

Restarting Explorer and ShellExperienceHost, temporarily disabling Nilesoft Shell, and resetting the saved Quick Settings layout did not resolve it. The latter changes were reverted.

### Captured evidence

There were no corresponding ordinary ShellHost crash reports, so I enabled Windows Silent Process Exit Monitoring specifically for `ShellHost.exe`.

On 17 September 2026, the **Microsoft-Windows-ProcessExitMonitor** provider recorded ten **event 3001** entries across two short bursts at 17:33:14–17:33:16 and 17:33:46–17:33:48 (UTC+01:00). Each identified MSEdgeRedirect as the terminating process. Representative message, with the user directory redacted:

```text
The process 'C:\Windows\System32\ShellHost.exe' was terminated by the process
'C:\Users\<user>\AppData\Local\MSEdgeRedirect\MSEdgeRedirect.exe'
with termination code 0.
```

An earlier event naming PowerShell was my deliberate restart to activate diagnostics; it was excluded from the above count. The subsequent MSEdgeRedirect terminations were not deliberate test terminations.

### Isolation / workaround

Stopping MSEdgeRedirect and starting ShellHost restored Quick Settings. It then opened and closed normally, with Windhawk still running. Disabling MSEdgeRedirect's startup shortcut prevents that background instance from returning at sign-in; the application remains installed. This is a workaround, not a long-term validation of a software fix.

### Possible relevant code

In the [0.8.0.0 tagged source, `ReactiveMode`](https://github.com/rcmaehl/MSEdgeRedirect/blob/0.8.0.0/MSEdgeRedirect.au3#L425-L480), the child-process branch calls `ProcessClose` before inspecting the process command line/path and attempting to relaunch non-Edge processes. This looks relevant to the observed behavior, although I have not traced the exact internal branch in the installed binary.

Could this issue be reopened, or would you prefer a separate report for the recurrence on 25H2? I saw the 0.8.0.0 release notes mention a Quick Settings fix, but the installed executable already reports that version.
