### ISSUE TITLE
The App appears in the system tray Windows 11 Pro

### ISSUE THREAD

**Issue by root-host** [rcmaehl/MSEdgeRedirect#49]
Hello, thanks for the development of the app
very useful instead of that bing
on windows 11 there is a bug, after restart or logout the icon appears in the system tray even if I click on the hide icon,
is there any way to fix this?

**Comment by rcmaehl** [comment]
> Hello, thanks for the development of the app very useful instead of that bing on windows 11 there is a bug, after restart or logout the icon appears in the system tray even if I click on the hide icon, is there any way to fix this?

Fixed in 0.6.0.0. If you open `shell:startup`
![image](https://user-images.githubusercontent.com/716581/147840689-27da77ed-a50e-4e57-9149-00feaea583cc.png)

And right click MSEdgeRedirect, then properties

Add `/hide` to `target`

![image](https://user-images.githubusercontent.com/716581/147840698-dfe10011-79bf-4337-9cfe-da8a0a0e9cec.png)

**Comment by root-host** [comment]
Thanks for the replay, I checked the shortcut now and the /hide flag already exist, but after logout log in or restart pc icon comes back to the system tray.

**Comment by rcmaehl** [comment]
> Thanks for the replay, I checked the shortcut now and the /hide flag already exist, but after logout log in or restart pc icon comes back to the system tray.

Odd. I'll look into this

**Comment by rcmaehl** [comment]
I haven't been able to reproduce this from a clean install so far. It does occur if the application is somehow launched twice however. Can you check `shell:startup` and see if you have multiple MSEdgeRedirects?

![image](https://user-images.githubusercontent.com/716581/148493279-519eb829-60a7-4544-901e-2ad32321b16d.png)

**Comment by root-host** [comment]
Hey,sorry for late replay,looks like you fixed the bug,i spin fresh win 11 in VM install latest MSEdgeRedirect after reboot there is no icon in the taskbar,works great thanks.

**Comment by Macleykun** [comment]
You can click on comment and close this issue then. Thanks for letting us know it’s working again :)
