### ISSUE TITLE
Add Translation Support

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#5]
- [ ] Add language selector
- [ ] Create translation guidelines
- [ ] Import existing strings from WhyNotWin11 where possible

**Comment by CryoRenegade** [comment]
Possibly use [crowdin](https://crowdin.com) for this? Allows for simple tracking and patching for UTF languages.

**Comment by ichii731** [comment]
If you need Japanese language support for your software, please contact me!
I'm Japanese, so I can provide accurate translations.

**Comment by rcmaehl** [comment]
Merging with 1.0.0.0 checklist
