### ISSUE TITLE
Issue when installing the 0.6.0.0 update

### ISSUE THREAD

**Issue by ElitePheonix009** [rcmaehl/MSEdgeRedirect#50]
When I am installing 0.6.0.0 in the install setting page when we check the checkbox "replace weather results with", then in the list there isn't a weather service listed.
![image](https://user-images.githubusercontent.com/94096555/147904456-45b1c3a7-153d-455a-a608-f1e56379ab79.png)

**Comment by rcmaehl** [comment]
This will be fixed in 0.6.1.0. In the meantime, this can be fixed by uninstalling from Programs & Features, then running the installer again. It should show `Install MSEdge Redirect 0.6.0.0` instead of `MSEdge Redirect 0.6.0.0 Update`

**Comment by rcmaehl** [comment]
Fix should be available in the test builds: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

I'll probably do some additional fixes for 0.6.1.0 and release it in a day or so.

**Comment by ElitePheonix009** [comment]
I uninstalled the program and then again installed 0.6.0.0 and now when I check the checkbox "replace weather results with", then in the list there are 2 weather services listed.
