### ISSUE TITLE
Allow installer to specify the location of settings.ini

### ISSUE THREAD

**Issue by SamHills** [rcmaehl/MSEdgeRedirect#51]
Please add an optional location parameter to the /silentinstall switch so that the location and filename of setup.ini can be specified, like this:
   MSEdgeRedirect /silentinstall=D:\Installers\MSEdgeRedirect.ini

**Comment by rcmaehl** [comment]
Just tested. Should be good.

https://github.com/rcmaehl/MSEdgeRedirect/wiki/Deploying-MSEdgeRedirect#deploying

Note that the file path to setup.ini must be directly after `/silentinstall`
e.g. `msedgeredirect.exe /silentinstall C:\Users\Public\Documents\Setup.ini`

UNC Paths (network locations without a drive letter) are not currently supported but will eventually be.
