### ISSUE TITLE
Error installing MSEdgeRedirect

### ISSUE THREAD

**Issue by SamHills** [rcmaehl/MSEdgeRedirect#52]
I did the following:
Formatted C:
Installed Windows 10 Pro  and booted to Audit Mode.
I then ran a .bat file from D: which did the following:
  Uninstalled Edge.
  Installed Chocolatey.
  Installed Firefox using Chocolatey.
  Installed Adobe Reader using Chocolatey.
  Installed setdefaultbrowser using Chocolatey, then ran setdefaultbrowser to set Firefox as my default browser.
  Downloaded the latest MSEdgeRedirect from GitHub.
  Created setup.ini in the same directory as MSEdgeRedirect, specifying Mode=Active.
  Ran MSEdgeRedirect with the /silentinstall switch.
The batch file stops running and a window pops up titled "Edge Set As Default" containing the message "You must set a different 
Default Browser to use MSEdgeRedirect!".
I clicked on Start -> Apps -> Default Apps and confirmed that Firefox was set as the default Web browser
Then I clicked the "OK" button in the MSEdgeRedirect pop-up and the .bat file continued.
After SysPrep, I ran installapps.bat again and got the same error.

**Comment by rcmaehl** [comment]
> I did the following: 

Can you run the following 3 commands in command prompt and provide a copy of the output:

`reg query HKCU\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice /s`
`reg query HKCU\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice /s`
`reg query HKCU\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\microsoft-edge\UserChoice /s`

**Comment by rcmaehl** [comment]
Okay, I see `setdefaultbrowser` has the ability to set the default browser in HKLM. I'll look into this if this is what you are using and improve the check.

**Comment by SamHills** [comment]
I added your queries to my batch file along with queries on HKLM and a query on %ERRORLEVEL%, and got the following result:
ERRORLEVEL = 1

HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice
    Hash    REG_SZ    07+Rc4WdgrU=
    ProgId    REG_SZ    FirefoxURL-308046B0AF4A39CB

HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice
    Hash    REG_SZ    LaMN+qNCZFQ=
    ProgId    REG_SZ    FirefoxURL-308046B0AF4A39CB

HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\microsoft-edge\UserChoice
    Hash    REG_SZ    hVbPd+MsK3Y=
    ProgId    REG_SZ    FirefoxURL-308046B0AF4A39CB

The queries on HKLM returned "Not found".

**Comment by rcmaehl** [comment]
> I added your queries to my batch file along with queries on HKLM and a query on %ERRORLEVEL%, and got the following result: ERRORLEVEL = 1

Please be sure your are checking `ERRORLEVEL` not `%ERRORLEVEL%.`

> HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice Hash REG_SZ 07+Rc4WdgrU= ProgId REG_SZ FirefoxURL-308046B0AF4A39CB
> 
> HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice Hash REG_SZ LaMN+qNCZFQ= ProgId REG_SZ FirefoxURL-308046B0AF4A39CB
> 
> HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\microsoft-edge\UserChoice Hash REG_SZ hVbPd+MsK3Y= ProgId REG_SZ FirefoxURL-308046B0AF4A39CB
> 
> The queries on HKLM returned "Not found".

Ah, firefox got set as the microsoft-edge handler. Windows will automatically revert that next time the URI is called but I'll add a patch for it.

**Comment by rcmaehl** [comment]
Fix has been compiled in the latest dev build: https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

Note that error messages are hiden with the silentinstall now as well. However, you can check the exit code per the deploy instructions
