### ISSUE TITLE
How to test if MSEdgeRedirect is running

### ISSUE THREAD

**Issue by SamHills** [rcmaehl/MSEdgeRedirect#55]
What is the best way to test if MSEdgeRedirect is installed and running (Active mode) in a batch or Powershell file?

**Comment by rcmaehl** [comment]
> What is the best way to test if MSEdgeRedirect is installed and running (Active mode) in a batch or Powershell file?

`start-process microsoft-edge:www.google.com` for powershell will launch google in the default browser if successful

**Comment by rcmaehl** [comment]
Alternatively, you can run

`reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\msedge.exe" /s`
