### ISSUE TITLE
(QUESTION) What does "de-embed windows store 'apps'" mean?

### ISSUE THREAD

**Issue by MultiKoopa** [rcmaehl/MSEdgeRedirect#57]
One of the installation options. I'm not sure I understand what exactly this does? couldn't find any answers to this.

**Comment by rcmaehl** [comment]
I'll be adding help options to the installer soon

https://github.com/rcmaehl/MSEdgeRedirect/wiki/Installer-Overview#-de-embed-windows-store-apps

This option converts web apps from the Windows Store to their actual web pages in the browser. Any app that states "This app requires the latest version of Microsoft Edge" is a web app and will be de-embedded if this option is selected. An example of this is the Wikipedia app.

**Comment by MultiKoopa** [comment]
oh I missed that section somehow, sorry. 

that's beautiful. Thank you!
