### ISSUE TITLE
Microsoft has base64 encoded the weather URL

### ISSUE THREAD

**Issue by MultiKoopa** [rcmaehl/MSEdgeRedirect#58]
Search results from the searchbar, and news articles from the Weather/News widget, redirect to a new Chrome tab (or open Chrome if it's closed) just fine. But when I click on "See full forecast", it attempts to open the MSN weather url appended to Weather.com

See attached image, full URL censored because I think it contains my exact location, but it should give the gist of the bug.

I'm on Windows 10 Pro
Build 19044.1466 (Version 21H2)

![edgeweatherredirectweathercom](https://user-images.githubusercontent.com/30543543/149071507-58958a92-c198-4018-830f-b24df600717e.png)

**Comment by rcmaehl** [comment]
Yep. Looks like Microsoft has base64 encoded the Latitude & Longitude now. Nothing I can't fix

**Comment by MultiKoopa** [comment]
Oh I see. Glad to hear it's fixable! Thank you for the fast response

And for the program of course

**Comment by rcmaehl** [comment]
Please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by MultiKoopa** [comment]
> Please try the latest test build:
> 
> https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

We did it!

And by that I mean you did it :) Thank you!
