### ISSUE TITLE
Missing argument...

### ISSUE THREAD

**Issue by gnpaone** [rcmaehl/MSEdgeRedirect#61]
I receive this error from mser saying that Windows couldn't find --continue-active-setup. Could you please look into it?
This error message appears after login after a restart/shutdown and appears only sometimes not always.

![Screenshot (5130)](https://user-images.githubusercontent.com/78990165/149471697-3c6b1b18-92fa-43d5-a2f6-38b9d6b0c84b.png)

**Comment by rcmaehl** [comment]
Do you know when this occured?

**Comment by rcmaehl** [comment]
Odd, I'll exclude this argument from being parsed to see if it fixes it

**Comment by rcmaehl** [comment]
Ugh, github keywords. Please try the latest test build

**Comment by gnpaone** [comment]
> Ugh, github keywords. Please try the latest test build

Sure, but is there any way to test it? I am not sure but my guess is restarting Windows causes the error sometimes or may be the restart after Windows update

**Comment by gnpaone** [comment]
> Odd, I'll exclude this argument from being parsed to see if it fixes it

Hey, the problem occurs **immediately after every Windows build update** and it's confirmed. The patched test version did not throw that error but it's throwing a different error.

Error:
![Screenshot (5227)](https://user-images.githubusercontent.com/78990165/150286472-0e5a582b-7c8e-4411-80db-426bb12a9f02.png)

Clearly I have installed 64 bit version and there is no mser folder in Program Files (x86)...: 
![Screenshot (5228)](https://user-images.githubusercontent.com/78990165/150286658-29742a09-a6b0-4fc0-b404-4f5e141f194a.png)
...but the error says something different

**Comment by rcmaehl** [comment]
Run '"C:\Program Files\MSEdgeRedirect\MSEdgeRedirect.exe" /repair` from an Admin CMD and see if that prevents it from occurring. 

https://github.com/rcmaehl/MSEdgeRedirect/blob/2c07f8d6ed9236217aeff8530610ecea09fc3479/MSEdgeRedirect.au3#L61 should prevent this from occuring but I'll see if I can beef up that check.

**Comment by gnpaone** [comment]
This error again occured after update:
![image](https://user-images.githubusercontent.com/78990165/151489450-871cb411-9f27-4d57-8eb8-6dfb91b50138.png)

**Comment by rcmaehl** [comment]
Microsoft please 😩

**Comment by gnpaone** [comment]
New kind of issue appearance after update
First:
![Screenshot (5547)](https://user-images.githubusercontent.com/78990165/154414161-0eebbcb2-1ebb-4ecc-8fcd-513b1bf58dc5.png)
Next:
![image](https://user-images.githubusercontent.com/78990165/154414232-fe77c02b-46dd-4aa3-a9e9-26e90e0576e5.png)

**Comment by rcmaehl** [comment]
I can only assume that it's passing the file version comparison. I've just added code to skip that check.

**Comment by gnpaone** [comment]
> I can only assume that it's passing the file version comparison. I've just added code to skip that check.

One small issue (installing but a bug), this warning appears for few seconds.......
![Screenshot (5556)](https://user-images.githubusercontent.com/78990165/154513214-f6dfb731-d0eb-483a-a716-3a1019adf2db.png)
.......and then vanishes to show the installer as normal
![image](https://user-images.githubusercontent.com/78990165/154513347-437f9f69-232a-4fb3-a208-d36a3c867ca4.png)

**Comment by rcmaehl** [comment]
> > I can only assume that it's passing the file version comparison. I've just added code to skip that check.
> 
> One small issue (installing but a bug), this warning appears for few seconds....... ![Screenshot (5556)](https://user-images.githubusercontent.com/78990165/154513214-f6dfb731-d0eb-483a-a716-3a1019adf2db.png) .......and then vanishes to show the installer as normal ![image](https://user-images.githubusercontent.com/78990165/154513347-437f9f69-232a-4fb3-a208-d36a3c867ca4.png)
> 
> I tried to install this build - https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1858684749

Yeah that's expected. The latest test build is a release candidate for 0.6.3.1, just trying to fix some bugs related to #28

**Comment by gnpaone** [comment]
> > > I can only assume that it's passing the file version comparison. I've just added code to skip that check.
> > 
> > One small issue (installing but a bug), this warning appears for few seconds....... ![Screenshot (5556)](https://user-images.githubusercontent.com/78990165/154513214-f6dfb731-d0eb-483a-a716-3a1019adf2db.png) .......and then vanishes to show the installer as normal ![image](https://user-images.githubusercontent.com/78990165/154513347-437f9f69-232a-4fb3-a208-d36a3c867ca4.png)
> > 
> > I tried to install this build - https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1858684749
> 
> Yeah that's expected. The latest test build is a release candidate for 0.6.3.1, just trying to fix some bugs related to #28 

Ok ☺️👌

**Comment by gnpaone** [comment]
![image](https://user-images.githubusercontent.com/78990165/155889908-4f7d385d-9564-41e6-bc55-4a7e33595138.png)

Again...😋

**Comment by rcmaehl** [comment]
> ![image](https://user-images.githubusercontent.com/78990165/155889908-4f7d385d-9564-41e6-bc55-4a7e33595138.png)
> 
> Again...😋

:|

**Comment by rcmaehl** [comment]
@gnpaone If you have a discord account can you join the discord?

**Comment by gnpaone** [comment]
> @gnpaone If you have a discord account can you join the discord?
> 
> 

Yah, I have it

**Comment by rcmaehl** [comment]
> > @gnpaone If you have a discord account can you join the discord?
> 
> Yah, I have it 🙂. Sure

pm me on there when you join so I can give you the right roles.

**Comment by gnpaone** [comment]
> > > @gnpaone If you have a discord account can you join the discord?
> > 
> > Yah, I have it 🙂. Sure
> 
> pm or @ me on there when you join so I can give you the right roles.

Done 😉
![Screenshot_2022-02-28-18-52-17-803_com.discord.jpg](https://user-images.githubusercontent.com/78990165/155990472-86769397-7e08-48aa-8983-b34650e65dab.jpg)

**Comment by gnpaone** [comment]
Hey @rcmaehl so far no error occurred in latest build update, will confirm no more error occurring in the next windows build update and probably close this issue then. Also please don't forget disabling the submit mser to winget workflow as discussed in https://github.com/rcmaehl/MSEdgeRedirect/issues/28#issuecomment-1053603873 this thing also confirmed in testing as well as discussion with winget developers

**Comment by gnpaone** [comment]
I recently updated my windows build and there's no error occurring so I think I'll close this issue. I may reopen if the problem occurs again. No error occurred so far (checked with this windows update as well as the last one). (Currently using https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/2002010367)
