### ISSUE TITLE
x86 version not working again

### ISSUE THREAD

**Issue by N2FC** [rcmaehl/MSEdgeRedirect#62]
**Check List**
- [ ] The App appears in the system tray
- [ ] Running `microsoft-edge:https://google.com` redirects successfully

**Describe the bug**\

**To Reproduce**

**⚠️ File Upload ⚠️**

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 11]
 - Windows Build: [e.g. 22494]

**Additional context**\

**Comment by N2FC** [comment]
0.6.1.0 32 bit version not working... still opens links in Edge...

**Comment by rcmaehl** [comment]
I have a feeling cb57ebb83b6c463237c061b455967f744640e8b0 broke this. Give it a few minutes then try the latest test build

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by N2FC** [comment]
That fixed!
