### ISSUE TITLE
Suggestions don't work

### ISSUE THREAD

**Issue by badbcentral** [rcmaehl/MSEdgeRedirect#67]
Hey! I'll try to explain the issue. I'm on the last ver.
![image](https://user-images.githubusercontent.com/67790845/151361244-394da238-cba8-4128-8abf-cde387a740f8.png)
What happens is, I typed "hello", selected the suggestion "hello neighbor" and it googled just "hello" - what I typed initially.
The issue appears only when using built-in redirector, works fine with chrometana.

**Comment by rcmaehl** [comment]
Not sure I can replicate that functionality without creating an addin myself due to how Microsoft has it implemented.

**Comment by rcmaehl** [comment]
I misread. I'll look into this.

**Comment by rcmaehl** [comment]
Found the issue and will be patching it shortly

**Comment by badbcentral** [comment]
@rcmaehl works as it should king
love being your most active contributor
