### ISSUE TITLE
Issues with latest edge update

### ISSUE THREAD

**Issue by N2FC** [rcmaehl/MSEdgeRedirect#68]
Had a strange issue apparently after an MS Edge app update a few days ago...

Started getting errors from: msedge_no_ifeo "couldn't launch app"

1) Attempted to repair by rebooting... no joy
2) Attempted to repair by reinstalling MS Edge--- failed when the reinstaller was redirected to Chrome!
3) Finally uninstalled MSEdgeRedirect, followed by reinstalling MSEdge... THIS WORKED...
4) The reinstalled MSEdgeRedirect all working, EXCEPT:
    "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --profile-directory=Default
Above shortcut gets error in default profile... had to remove that reference from shortcut!!

**Comment by rcmaehl** [comment]
If this occurs again try running the installer with the `/repair` option.

I'll look into fixing 2 and 4 :)

**Comment by rcmaehl** [comment]
4 should be fixed in the latest test build. Working on 2. :)

**Comment by rcmaehl** [comment]
2 should also now be fixed. If this issue reoccurs let me know.
