### ISSUE TITLE
"How do you want to open this" prompt for HTTP/HTTPS

### ISSUE THREAD

**Issue by SamHills** [rcmaehl/MSEdgeRedirect#70]
To reproduce:
1.  Install apps using a .bat file containing the following (minor details omitted for brevity):
<code>
REM Uninstall Edge:
CALL "%~dp0UninstallEdge

REM Install Firefox:
choco install Firefox

REM Install setdefaultbrowser and set Firefox as the default browser:
choco install setdefaultbrowser && (
  for /f "tokens=*" %%b in ('setdefaultbrowser ^| find /i "HKLM Firefox"') do setdefaultbrowser %%b
)

REM Download and install MSEdgeRedirect (Active mode):
POWERSHELL -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest -Uri 'https://github.com/rcmaehl/MSEdgeRedirect/releases/latest/download/MSEdgeRedirect.exe' -OutFile '%MSEdgeRedirectDir%\MSEdgeRedirect.exe'"
"%MSEdgeRedirectDir%\MSEdgeRedirect.exe" /silentinstall
</code>

2.  Run a program such as Wizard101 that exits by displaying a webpage.
3. A window pops up asking how do I want to open this file (offering Edge as the "preferred" choice).
4.  Run setdefaultbrowser from the command line to re-establish Firefox as the default browser.
5. Run Wizard101 again and exit.
6. Firefox opens the Wizard101 "news" page as expected.

**Comment by rcmaehl** [comment]
It shouldn't. I do see that you may be uninstalling Edge as implied with `%~dp0UninstallEdge` which may be part of the issue per #26.

I've commented out the only possible code I can think of that might be causing this issue. Please try the latest test build when you can.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by SamHills** [comment]
I have run several tests to try to determine if my code was part of the problem.  My last few test runs were like this:
1.  Boot the Windows installation medium (USB thumb drive).
2. Format C: but leave D: alone.
3. Install Windows.  Autounattend.xml on the installation drive causes the installation to stop in Audit mode so customizations can be applied.
4. Run ConfigureWindows.bat, which performs the steps listed in my O.P.:
  Uninstall Edge.
  Install Firefox.
  Run setdefaultbrowser to set Firefox as the default browser.
  Install MSEdgeRedirect.
  Perform other customizations and app installations not related to this problem.
5.  Optional: Run Wizard101 and exit.
6. Run Sysprep to finish the Windows installation.
7. Run ConfigureUsers.bat to do user-specific customization.  This includes:
  Run UninstallEdge.bat again (Micro$$$oft tries every way they can to force Edge at us.  What do they have to gain by it?  Something's rotten in the state of Washington, methinks.)
  Run setdefaultbrowser again.
8.  Run Wizard101 and exit.

Latest test results:
If I download and install the latest MSEdgeRedirect release version from GitHub, when Wizard101 exits a window pops up asking how I want to open this file (but no file is listed in the popup).
If I install the "patched" version of MSEdgeRedirect that you sent me on Feb. 2, when Wizard101 exits it opens the Wizard101 "Ravenwood News" page in Firefox.

**Comment by rcmaehl** [comment]
> If I install the "patched" version of MSEdgeRedirect that you sent me on Feb. 2, when Wizard101 exits it opens the Wizard101 "Ravenwood News" page in Firefox.

Okay. I'll mark this as resolved then.

**Comment by SamHills** [comment]
Has this fix been added to the release version yet?

**Comment by rcmaehl** [comment]
> Has this fix been added to the release version yet?

*Should* be fixed in 0.6.3.0
