### ISSUE TITLE
(Bug)it does not redirect to default browser

### ISSUE THREAD

**Issue by dtantono** [rcmaehl/MSEdgeRedirect#71]
**Check List**
- [V] The App appears in the system tray
- [V] Running `microsoft-edge:https://google.com` redirects successfully

**Describe the bug**\
I updated it to 0.6.2 and it does not appear in the system tray and when I press win + r to run microsoft-edge:https://google.com. it does not launch anything. 

**To Reproduce**
1. Go to '.https://github.com/rcmaehl/MSEdgeRedirect/releases/tag/0.6.2.0'
2. Click on 'https://github.com/rcmaehl/MSEdgeRedirect/releases/download/0.6.2.0/MSEdgeRedirect_x86.exe'
3. Follow instruction on the wizard
4. it does not show up on system tray and and when I press win + r to run microsoft-edge:https://google.com. it does not launch anything
5. Instead it shows me popup to redirect it on Edge

**⚠️ File Upload ⚠️**
<img width="283" alt="Screenshot 2022-02-02 121407" src="https://user-images.githubusercontent.com/29157187/152093835-b00bfd50-75b9-4bdd-877f-9272c62c1ae1.png">

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
<img width="942" alt="Screenshot 2022-02-02 121825" src="https://user-images.githubusercontent.com/29157187/152093854-6d592a91-db5d-411a-b888-096523fb3b98.png">

4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files
[AppGeneral.log](https://github.com/rcmaehl/MSEdgeRedirect/files/7983588/AppGeneral.log)
[AppSecurity.log](https://github.com/rcmaehl/MSEdgeRedirect/files/7983589/AppSecurity.log)
[edge.txt](https://github.com/rcmaehl/MSEdgeRedirect/files/7983590/edge.txt)
[URIFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/7983591/URIFailures.log)

**Desktop (please complete the following information):**
Windows 10 Pro 10.0.19044

**Additional context**\
I already rebooted it and it does not worked

**Comment by rcmaehl** [comment]
MSEdgeRedirect will not be in that menu to choose from as that menu is locked. What happens if you select the "Featured" MS Edge and "Always use this app", does it then redirect properly?

**Comment by dtantono** [comment]
yeah the top one redirect me to my default browser. But, by pretend to be "MS edge" while the reality I use different browser (not Edge) is quite confusing. Is there a way to suppress this popup?

**Comment by rcmaehl** [comment]
Yeah, I'm removing the code that causes this issue as it seems to be confusing. It won't affect versions 0.7 and later.
