### ISSUE TITLE
Settings not working

### ISSUE THREAD

**Issue by chjohans** [rcmaehl/MSEdgeRedirect#74]
Using the latest stable version 0.6.0.0 and Edge is updates as well. MSEdge Redirect works, but the "settings" link just opens the GNU license window. When I click "I accept this license" and save nothing else happens, the actual settings window will never be shown.

I've installed MSEdge Redirect  in "Active Mode" for the "Edge Stable" channel, I did chose to replace Bing results with Google and Weather with Weather.com.

Everything is working just fine except the "Settings" cannot be accessed after installing. SOmetimes MSEdge Redirectr gets messed up with new versions of Edge so the settings window would be handy to have so that it coud be disabled and enabled again.

My current workaround is just to re-install and disable MSEdge Redirect when installing, the re-install to enable again. THis works, but it would be much easier to have a working settings menu.

**Comment by rcmaehl** [comment]
Confirmed, broke in ab7c44c71503f024b526344936fdb7e1ef02b949
Will be fixed in 0.6.3.0

**Comment by rcmaehl** [comment]
Please try the latest test build when possible

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
