### ISSUE TITLE
edge the application has failed to start because its sidebyside configuration is

### ISSUE THREAD

**Issue by aisle9** [rcmaehl/MSEdgeRedirect#76]
**Check List**
- [ ] Microsoft Edge is still installed (see #26)
- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

**Installed Mode**
- [x] Active Mode
- [ ] Service Mode

**Describe the bug**

**To Reproduce**

**⚠️ File Upload ⚠️**

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 11]
 - Windows Build: [e.g. 22494.867]

**Additional context**

**Comment by rcmaehl** [comment]
Please try running `MSEdgeRedirect /repair` from an admin cmd.

**Comment by aisle9** [comment]
I've reinstalled it, and it seems to work fine now.
