### ISSUE TITLE
Folder created but FileCopy failed

### ISSUE THREAD

**Issue by lscheffler** [rcmaehl/MSEdgeRedirect#78]
I try to install the [latest stable release](https://github.com/rcmaehl/MSEdgeRedirect/releases/latest/download/MSEdgeRedirect.exe) on an Win10 and on an Win11 machine, both come up with something like _This App could not be run on this machine._ Both machines habe latest Win updates as of today.

**Comment by rcmaehl** [comment]
Does the issue occur with the latest test build? https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by lscheffler** [comment]
Win10: (64) Runs

**Comment by rcmaehl** [comment]
> On Win11 (Admin account) it silently runs, while on Win10 (user account) it raises an install dialog. I'm confused

Sounds like the install might be botched. Run the cleanup script from:

https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1

And see if that improves things

**Comment by rcmaehl** [comment]
Also, if you can grab a screenshot of the full error you get from stable it'd be appreciated.

**Comment by rcmaehl** [comment]
> Ok, not run the cleanup yet, on Win11 (user account) the exe is started directly. I give the cleanup a try next. Screenshot is Deutsch only. Proceed Y/N ? :)

Ja

**Comment by lscheffler** [comment]
System modal message box. Used the phone ..  
![20220217_152930](https://user-images.githubusercontent.com/27769909/154502998-fe2ea111-ebe2-444a-8d2b-85d239a2918f.jpg)
.

**Comment by rcmaehl** [comment]
![image](https://user-images.githubusercontent.com/716581/154503566-ae3c571d-7b01-4d26-a1fe-fc543b187ead.png)

Download is maybe bad? File should be ~900KB - 1MB.

**Comment by lscheffler** [comment]
On Win11 (note, this is first try to install at all)

- _C:\Program Files\MSEdgeRedirect_ No such directory
- _%LOCALAPPDATA%\MSEdgeRedirect_ removed
- on all reg keys mentioned: no entry found

-----
other problem:   
ok, file is smaller

**Comment by lscheffler** [comment]
The test build on Win11 does not run the installer after clean up. It just runs and creates the %LOCALAPPDATA%\MSEdgeRedirect folder.

**Comment by lscheffler** [comment]
To the FF download. It's like
Download runs, after a while it shows ready and after some more tim the tiny dot. Ugly design. 

--- 

For the install on Win11
Only if I download via Chrome on the Win11 it installs. Following the same link on Win10 - FF, copy to thumbstick and run on the Win11 fails. I compared the files, there is no difference.

Now it runs on both machines. So my problem is solved so far.

**Comment by rcmaehl** [comment]
> The test build on Win11 does not run the installer after clean up. It just runs and creates the %LOCALAPPDATA%\MSEdgeRedirect folder.

I'll look into this part.

**Comment by rcmaehl** [comment]
Added failure logging to the installer
