### ISSUE TITLE
Results duplicate if Edge is already open. URI information is lost when a potential new Window is converted into a tab

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#8]
> @gnpaone All builds of edge should now be supported. Latest automatically compiled build is available here:
> 
> https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1451619392
> 
> It works on my machine but if you can test it out, it'd be appreciated :)

Yes, it's working perfectly with dev, but one more issue I found, if I already opened edge manually (any version - stable, dev etc) and if I search something in windows then search results opens in both edge as well as chrome, this doesn't happen (only opens in chrome) if edge is closed

_Originally posted by @gnpaone in https://github.com/rcmaehl/MSEdgeRedirect/issues/3#issuecomment-966816982_

**Comment by rcmaehl** [comment]
Able to reproduce

**Comment by rcmaehl** [comment]
Closing PID will keep the tab open and edge is not happy about it

![image](https://user-images.githubusercontent.com/716581/141412545-0a1abe8f-eb3a-45d2-afb9-b2741241a411.png)

Needed changes:
- [ ] Track if Microsoft Edge is already running
- [ ] Track number of Microsoft Edge windows
- [ ] Track number of Microsoft Edge processes
- [ ] Have Command Line redirection trigger when the number of Processes increases, instead of if process exists

Possible solutions:
- [ ] ~~Get parent process and kill parent~~ - Closes Edge Entirely
- [ ] Send Ctrl-W to Edge

Will investigate more solutions tomorrow

**Comment by rcmaehl** [comment]
Closing the PID sooner, rather than later, seems to resolve this issue. It's still a race to close it before Edge converts it into an existing tab but testing is going well

**Comment by rcmaehl** [comment]
@gnpaone The following dev build should work better:

https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1453806041

Let me know if you still have the issue. Should work the majority of the time but working on improvements

**Comment by gnpaone** [comment]
> @gnpaone The following dev build should work better:
> 
> https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1453806041
> 
> Let me know if you still have the issue. Should work the majority of the time but working on improvements

Yes, it works most of the times, it fails to redirect rarely (not redirects to chrome and opens in edge) (The search result in edge shown in pic opened 2nd time for me)(Similarly it opened 18th time - it fails randomly - not in pic)
![Screenshot (4844)](https://user-images.githubusercontent.com/78990165/141504559-da8c4f59-830a-4b0b-9163-1cced07ff4d6.png)

**Comment by gnpaone** [comment]
Found one more issue, it opens in edge (dev, stable etc) if searched via widgets panel in Windows 11, it doesn't open in Chrome (for reference Edgedeflector opened Widgets panel search in Chrome too)

**Comment by gnpaone** [comment]
> > @gnpaone The following dev build should work better:
> > https://github.com/rcmaehl/MSEdgeRedirect/actions/runs/1453806041
> > Let me know if you still have the issue. Should work the majority of the time but working on improvements
> 
> Yes, it works well, thanks 😊, will surely report if I find any other issues.
> 
> ## --edited to remove this as I thought it occurs rarely:--
> ![Screenshot (4845)](https://user-images.githubusercontent.com/78990165/141505895-6904b3c6-9a9e-42ee-b933-ad7e3defc793.png)

I succssfully replicated this issue (I didn't understand the pattern/what causes the failure but the video may help u)

https://user-images.githubusercontent.com/78990165/141605876-21f5686f-b0b9-4b9c-8d8b-ff6720351b22.mp4

**Comment by rcmaehl** [comment]
Big changes coming soon ;)

**Comment by rcmaehl** [comment]
Just a sneak peak. Thanks to @AveYo for his "ChrEdgeFkOff" work for inspiration.

![image](https://user-images.githubusercontent.com/716581/141927749-cbb6e9cd-cd91-4d06-bf8b-ef1d98395c2e.png)

**Comment by rcmaehl** [comment]
Please use ACTIVE MODE from version 0.4.0.0
