### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by PIRATAONE** [rcmaehl/MSEdgeRedirect#80]
Trying to install this on a brand new Surface Pro 8 with Windows 11 Home installed.
Once executed, instead of seeing the regular installation window, I see the app icon showing in my taskbar, and that's it.

I have another computer with Windows 10 Pro and this doesn't happen. 

Tried build v0.6.3.0 and an older one v0.6.1.0 and both does that on Windows 11 Home.

Can't understand how to force app installation.
Thank you.

**Comment by gnpaone** [comment]
It's probably the Windows Defender blocking the installation or as you see the icon in the tray you can double click it to open the installer

**Comment by rcmaehl** [comment]
I'll be adding in some additional error checking since I've seen one other person reporting an install issue, just to be safe

**Comment by PIRATAONE** [comment]
> It's probably the Windows Defender blocking the installation or as you see the icon in the tray you can double click it to open the installer

If I click the icon it doesn't happen anything. Can't install. Doesn't do this on Windows 10 Pro.

**Comment by rcmaehl** [comment]
Please run the cleanup script

https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1

Then try the latest test build

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by PIRATAONE** [comment]
Just wanted to update that I tried about 5 minutes ago to execute again MSEdgeRedirect.exe on Windows 11 Home only to test it one last time...and it worked: Installation window appeared and I was able to install it correctly like I did on another machine with Windows 10 Pro.
Don't know exactly why now is it working, but I just ended up installing a bunch of software on that Win 11 machine as it is a work computer for a relative.
Other than the usual installing common apps, I needed to install latest Microsoft Visual C++ Redistributable files as for fixing an issue with a .dll with an Adobe app. Don't know if this might be related.
If you find the issue, please share it so to understand how to avoid it in the future.
Thank you.

**Comment by PIRATAONE** [comment]
> Please run the cleanup script
> 
> https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1
> 
> Then try the latest test build
> 
> https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

I can't run the cleaner:
```
cannot be loaded because running scripts is disabled on this system. For more
information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
```
Can I simply uninstall it normally?

**Comment by gnpaone** [comment]
> > Please run the cleanup script
> > https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1
> > Then try the latest test build
> > https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
> 
> I can't run the cleaner:
> 
> ```
> cannot be loaded because running scripts is disabled on this system. For more
> information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
> ```
> 
> Can I simply uninstall it normally?

Open a powershell window in administrator mode and run this command:
`Get-ExecutionPolicy` and note your execution policy
then run `Set-ExecutionPolicy RemoteSigned` (if you get an error `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`)
now execute the ps1 file, after completion of process you can revert back to original execution policy that you noted earlier by running the set command. If you want to avoid this process and do it temporarily then run `powershell -ExecutionPolicy Bypass -File "path/to/Cleanup Tool.ps1"`

**Comment by PIRATAONE** [comment]
> > > Please run the cleanup script
> > > https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1
> > > Then try the latest test build
> > > https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
> > 
> > 
> > I can't run the cleaner:
> > ```
> > cannot be loaded because running scripts is disabled on this system. For more
> > information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can I simply uninstall it normally?
> 
> Open a powershell window in administrator mode and run this command: `Get-ExecutionPolicy` and note your execution policy then run `Set-ExecutionPolicy RemoteSigned` (if you get an error `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`) now execute the ps1 file, after completion of process you can revert back to original execution policy that you noted earlier by running the set command. If you want to avoid this process and do it temporarily then run `powershell -ExecutionPolicy Bypass -File "path/to/Cleanup Tool.ps1"`

No way. I continue to have a lot of error for access denied.
I have cleaned the system manually as watching inside the script. and uninstalling the app using Ashampoo Uninstaller.
I think I have gotten rid off everything.

I tried then your unreleased version you linked me. No difference from the v0.6.3.0 I tested earlier today as working.
So I think I'll use the 0.6.3.0 official version for now as your unreleased version does sometime show that popup about the release being unpublished (it happens not always, but sometimes, and by clicking to some results if searching something in the Windows search bar in Start).

Something that I have noticed regarding the behavior of your deflector (and probably off topic here) is that even having selected Google as default Bing Search, if I search for something in the Windows search bar in Start, for example the word "cat", by clicking directly on any link there I see for a tiny fraction the Bing search provider and not Google. This is annoying specially if I click onto an image: instead of Google image I get Bing again with such image. This doesn't happen if I click the floating "Open results in browser", where I get Chrome opening on Google. It look likes that your deflector works for loading Chrome and using Google on the floating blue button, but not in regular links in the results shown in Start.
I have verified this behavior on both latest stable v0.6.3.0 and unreleased version you linked me.
Hope this might help you.
Thank you.

**Comment by rcmaehl** [comment]
> Something that I have noticed regarding the behavior of your deflector (and probably off topic here) is that even having selected Google as default Bing Search, if I search for something in the Windows search bar in Start, for example the word "cat", by clicking directly on any link there I see for a tiny fraction the Bing search provider and not Google. This is annoying specially if I click onto an image: instead of Google image I get Bing again with such image. This doesn't happen if I click the floating "Open results in browser", where I get Chrome opening on Google. It look likes that your deflector works for loading Chrome and using Google on the floating blue button, but not in regular links in the results shown in Start.

Will look into that. Thanks!

**Comment by PIRATAONE** [comment]
> > Something that I have noticed regarding the behavior of your deflector (and probably off topic here) is that even having selected Google as default Bing Search, if I search for something in the Windows search bar in Start, for example the word "cat", by clicking directly on any link there I see for a tiny fraction the Bing search provider and not Google. This is annoying specially if I click onto an image: instead of Google image I get Bing again with such image. This doesn't happen if I click the floating "Open results in browser", where I get Chrome opening on Google. It look likes that your deflector works for loading Chrome and using Google on the floating blue button, but not in regular links in the results shown in Start.
> 
> Will look into that. Thanks!

Hello there!
Any updates?
Thanks in advance.

**Comment by rcmaehl** [comment]
> > > Something that I have noticed regarding the behavior of your deflector (and probably off topic here) is that even having selected Google as default Bing Search, if I search for something in the Windows search bar in Start, for example the word "cat", by clicking directly on any link there I see for a tiny fraction the Bing search provider and not Google. This is annoying specially if I click onto an image: instead of Google image I get Bing again with such image. This doesn't happen if I click the floating "Open results in browser", where I get Chrome opening on Google. It look likes that your deflector works for loading Chrome and using Google on the floating blue button, but not in regular links in the results shown in Start.
> > 
> > 
> > Will look into that. Thanks!
> 
> Hello there! Any updates? Thanks in advance.

The next update will contain code that fixes the image opening in bing instead of the provider.
