### ISSUE TITLE
Custom Searches not Working

### ISSUE THREAD

**Issue by MuhammadrizoGameDeveloper** [rcmaehl/MSEdgeRedirect#87]
**Describe the request**
A clear and concise description of what the request is.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Build [e.g. 22494]

**Additional context**
Add any other context about the request here.

**Comment by rcmaehl** [comment]
> > > **Describe the request** A clear and concise description of what the request is.
> > > **Screenshots** If applicable, add screenshots to help explain your request.
> > > **Desktop (please complete the following information):**
> > > 
> > > * OS: [e.g. Windows 11]
> > > * Build [e.g. 22494]
> > > 
> > > **Additional context** Add any other context about the request here.
> > 
> > 
> > Does setting `https://search.brave.com/search?q=` as the custom not work?
> 
> it doesn't work for me it redirects to google, (any custom link redirects to google)

That's not good. I'll investigate that

**Comment by rcmaehl** [comment]
Please run the [Cleanup tool](https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1) and reinstall. Let me know if the issue persists.

**Comment by rcmaehl** [comment]
Should be fixed as of 3a6a88d. Was a wider issue with settings saving.
