### ISSUE TITLE
MsEdgeRedirect affecting other apps.

### ISSUE THREAD

**Issue by LightH12** [rcmaehl/MSEdgeRedirect#89]
**Describe the request**
MsEdgeRedirect affecting other apps functionality.

**Screenshots**
If applicable, add screenshots to help explain your request.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Build: 22000

**Additional context**
Discord, spotify, and any other apps that use links in app malfunction when using MsEdgeRedirect.

Example: Switching servers or Chatrooms in discord crashes the app and cause it to reload.

Example 2: Clicking a song's album in Spotify (windows non store version) opens my default browser and opens a link that dosen't load (normally should open album in app not using a browser)

Side notes: 
_Restarting the said programs and reinstalling them didn't help.
_the issue seem to be related to MsER redirecting the in-app links.

The issue stopped as soon as i uninstalled MsEdgeRedirect. (Issue stopped as soon as i unistalled and said apps were still open)

**Comment by rcmaehl** [comment]
Were you using the Microsoft Store versions of the apps or the downloaded .exe installers?

Additionally, where you using active mode?

**Comment by LightH12** [comment]
> Were you using the Microsoft Store versions of the apps or the downloaded .exe installers?
> 
> Additionally, where you using active mode?

I was using the .exe installer version set to used Active Mode.

**Comment by rcmaehl** [comment]
> I was using the .exe installer version

I mean for spotify and discord?

**Comment by LightH12** [comment]
> > I was using the .exe installer version
> 
> I mean for spotify and discord?

Both .exe installed versions

**Comment by LightH12** [comment]
Additional info: 
_Spotify's issue made it open my default browser Brave and tried to load some sort of spotify link. (The app didn't open the album page and continued working like nothing happened)
_Discord's issue reloaded discord (made it do the opening animation) and it didn't open the browser.

**Comment by rcmaehl** [comment]
Haven't been able to reproduce Example 1 despite using the app myself.

Example 2 might be related to HarshalKudale/NoMoreEdge/issues/18

I'll look into it and see what I can do but things are a bit hectic personally right now

**Comment by LightH12** [comment]
> Haven't been able to reproduce Example 1 despite using the app myself.
> 
> Example 2 might be related to [HarshalKudale/NoMoreEdge/issues/18](https://github.com/HarshalKudale/NoMoreEdge/issues/18)
> 
> I'll look into it and see what I can do but things are a bit hectic personally right now

Alright, hope all turn out well!

**Comment by rcmaehl** [comment]
Please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by LightH12** [comment]
> Please try the latest test build:
> 
> https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

I'll try it now.

**Comment by LightH12** [comment]
![image](https://user-images.githubusercontent.com/91688534/158070829-f88419b4-ea24-4efc-9b04-f8c264b85ed6.png)

??? this did not happen last time

**Comment by LightH12** [comment]
> ![image](https://user-images.githubusercontent.com/91688534/158070829-f88419b4-ea24-4efc-9b04-f8c264b85ed6.png)
> 
> ??? this did not happen last time

Aside from this appearing twice, everything works fine now including custom search. (both spotify and discord works like normal)

**Comment by rcmaehl** [comment]
> ![image](https://user-images.githubusercontent.com/91688534/158070829-f88419b4-ea24-4efc-9b04-f8c264b85ed6.png)
> 
> ??? this did not happen last time

443 is HTTPS. Not sure what the IP is but I'm assuming it's the update checker IP
