### ISSUE TITLE
Messenger Windows App errors

### ISSUE THREAD

**Issue by shanekelly55** [rcmaehl/MSEdgeRedirect#94]
**Check List**
- [x ] Microsoft Edge is still installed (see issue 26)
- [x ] Running `microsoft-edge:https://google.com` redirects successfully
- [x ] Reinstall or `/repair` was attempted for System Errors (see issues 25 & 77)
- [x ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

**Install Type**
- [x ] New Install
- [ ] New Deployment (winget/chocolatey/sccm)
- [ ] Update
- [ ] Managed Update (winget/chocolatey/sccm)

**Installed Mode**
- [ x] Active Mode
- [ ] Service Mode
- [ ] Unsure

**Describe the bug**

If you had facebook and messenger apps installed then ran MSEdgeDirect whenever you get a new facebook message, even after uninstalling the apps, Chrome gets called and theres a URL for what looks to be an Edge link.

This site can’t be reached. Check if there is a typo in

"--winrt-background-task-event%3D..........................................."

**To Reproduce**
1. Install Facebook and Facebook Messenger M$ apps.
2. Install MSEdgeRedirect
3. UnInstall Facebook and Facebook Messenger M$ apps.
4. Get a Facebook Message
5. Chrome tab should open with the above error.

**⚠️ File Upload ⚠️**

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
6. Attach the log files

[edge.txt](https://github.com/rcmaehl/MSEdgeRedirect/files/8236308/edge.txt)
[URIFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8236309/URIFailures.log)
[AppGeneral.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8236310/AppGeneral.log)
[AppSecurity.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8236311/AppSecurity.log)

**Desktop (please complete the following information):**
 - Windows Version: [e.g. 11]
 - Windows Build: [e.g. 22494.867]

**Additional context**

**Comment by shanekelly55** [comment]
Windows 11 Home
Windows Build - 22000.556
Version - 21H2

**Comment by shanekelly55** [comment]
I know its Facebook triggered since as soon as i get Facebook message, phone dings and chrome pops up with a failed URL.

**Comment by rcmaehl** [comment]
Run:

https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1

When installing: Make sure that `Windows Store 'Apps'` is deselected

**Comment by rcmaehl** [comment]
I think I see the issue. Apps are getting caught in the safeguards. I'll improve this for the next build

**Comment by shanekelly55** [comment]
THe script didnt work.  Various errors like incorrect Path etc.

**Comment by rcmaehl** [comment]
Please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by shanekelly55** [comment]
I can close Edge now but now the Facebook/Messenger messages engage the chrome tab again.

**Comment by rcmaehl** [comment]
> I can close Edge now but now the Facebook/Messenger messages engage the chrome tab again.

I'll use the apps myself for a few days to reproduce.

**Comment by rcmaehl** [comment]
> I can close Edge now but now the Facebook/Messenger messages engage the chrome tab again.

Try the latest test build one more time. Apparently there was an issue with command line handling that I've fixed

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by vanyamlb** [comment]
I got the same error with Instagram

**Comment by rcmaehl** [comment]
> I got the same error with Instagram

Will look into it!

**Comment by rcmaehl** [comment]
Please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by rcmaehl** [comment]
I've been unable to reproduce on my end after d5584a6de0bd932b474c1a1a73140fc463e05303. If this is still an issue after trying the latest test build, please reopen the issue.
