### ISSUE TITLE
Add Dark Sky (darksky.net) to the weather service options

### ISSUE THREAD

**Issue by Memesy02** [rcmaehl/MSEdgeRedirect#97]
**Describe the request**
Dark Sky is an amazing weather service and I think adding it would further enhance this great app. 

**Screenshots**
If applicable, add screenshots to help explain your request.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Build [e.g. 22494]

**Additional context**
Add any other context about the request here.

**Comment by rcmaehl** [comment]
Had investigated this when originally deciding whether providers to add but only had one person mention it. Can do

**Comment by rcmaehl** [comment]
Added, please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip
