### ISSUE TITLE
Improve update message

### ISSUE THREAD

**Issue by trlkly** [rcmaehl/MSEdgeRedirect#98]
I was just now asked if I wanted to update. However, there is no mention in the dialog what program I'm updating. As such, I didn't dare click on it. 

The update message should say something like "An update to MSEdgeRedirect has been found." It also would be nice if it appeared in the notifications panel, and not a popup window. 

Finally, it would be good if it would just download it. And for there to be an option to say "always download and install update," keeping the same settings.

**Comment by rcmaehl** [comment]
Can do

**Comment by rcmaehl** [comment]
> It also would be nice if it appeared in the notifications panel, and not a popup window.
Looking into this. May be a bit for this specific change but I see no issue with this.

> Finally, it would be good if it would just download it. And for there to be an option to say "always download and install update," keeping the same settings.

Hesitant to implement any sort of automatic updating in case of a [supply chain attack](https://www.wired.com/story/inside-the-unnerving-supply-chain-attack-that-corrupted-ccleaner/). I have my github account locked down pretty well but you never know.

**Comment by ItsMeAubey** [comment]
> Hesitant to implement any sort of automatic updating in case of a [supply chain attack](https://www.wired.com/story/inside-the-unnerving-supply-chain-attack-that-corrupted-ccleaner/). I have my github account locked down pretty well but you never know.

https://github.com/rcmaehl/MSEdgeRedirect/blob/faf2f12ce2e11d79d434ae15226374427d0750c5/MSEdgeRedirect_Wrapper.au3#L680

While I was poking around looking for the update text string I noticed also that the update URL points to your domain, which then seems to redirect to Github via Cloudflare. Just for the sake of transparency and safety in case of a supply chain attack, you might want to change this to just a direct Github link.
